// 도트 스프라이트 — 한 글자가 한 도트다.
// 여기서 정의한 모든 그림은 시작할 때 **하나의 스프라이트시트(아틀라스)**로 구워지고,
// 이후 렌더러는 아틀라스에서 잘라 쓰기만 한다(drawImage의 9인자 형태).
//
//   '.'  투명       'k'  외곽선(어느 팔레트든 검정 한 색이다)
//   나머지 글자의 뜻은 팔레트(PAL)마다 다르다.
//
// 외곽선을 재질 색으로 물들이면 어두운 바닥에 묻혀 실루엣이 흐려진다.
// 검게 따 줘야 그림이 배경에서 떨어져 나온다.
//
// 빛은 **왼쪽 위 한 곳**에서만 온다. 모든 그림이 같은 광원을 쓰기 때문에 아틀라스
// 전체가 한 세트처럼 보인다. 그래서 좌우 대칭(mirror)은 쓰지 않는다 — 대칭인 그림은
// 빛의 방향을 담을 수 없어 납작해 보인다. 대신 재질마다 4~6단 계조를 두고
// 그림자 쪽 실루엣에 반사광을 한 겹 넣는다.
//
// 프레임마다 lift(0/1)를 줄 수 있다 — 굽는 캔버스가 한 줄 더 높고, 1이면 한 줄 떠 있다.
// 발밑(bottom-center) 기준으로 그리므로 lift를 번갈아 주면 걷는 동안 몸이 통통 튄다.
//
// art: 한 월드 단위를 몇 도트로 찍었는지(기본 1). art:2면 같은 크기를 네 배 촘촘하게
// 그린 것이라, 화면에서는 절반 크기로 그려 결과적으로 크기는 그대로 두고 밀도만 올린다.
// 덕분에 그림을 다시 찍어도 이동 속도·판정 반지름 같은 게임 수치는 손대지 않는다.

// ---- 팔레트 ----
export const PAL = {
  // 슬라임 — 젤리 한 덩이. 속이 비쳐 보이도록 밝은 단을 넉넉히 뒀다
  slime: {
    k: '#000000', d: '#0d4a22', g: '#1a7a37', G: '#2ba84f', H: '#4ad468',
    L: '#86f294', l: '#e2fff0', e: '#08160e', E: '#eaffff',
  },
  // 유령 — 차가운 흰빛 천. 아래로 갈수록 어두워진다
  ghost: {
    k: '#000000', v: '#3a4aa8', u: '#5a72cc', g: '#8ea8ec', G: '#c8daff',
    L: '#f4f8ff', e: '#140d33', q: '#5fe8ff', Q: '#e2fbff',
  },
  // 박쥐 — 날개막(w~V)과 털(n~M)을 따로 나눴다
  bat: {
    k: '#000000', w: '#2a1a56', W: '#3f2a80', v: '#5b3eb2', V: '#8462e0', n: '#2e2142',
    N: '#4d3663', m: '#705589', M: '#9d84b4', e: '#ff5a63', E: '#ffe0e2', F: '#f4f0ff',
  },
  // 해골 — 뼈 4단 + 눈구멍에서 타는 불
  bone: {
    k: '#000000', a: '#7a7259', B: '#aaa286', b: '#dcd4b4', w: '#f6efd6', W: '#fffdf4',
    e: '#3a0d0d', q: '#ff6a3a', Q: '#ffd6a0', r: '#5c2418', R: '#8a3a24',
  },
  // 골렘 — 돌 6단, 이끼, 갈라진 틈의 용암
  stone: {
    k: '#000000', o: '#16241f', v: '#2b483e', S: '#436257', M: '#5f8474', m: '#83a892', h: '#b0cebc',
    g: '#2f6b30', G: '#4e9645', j: '#78c46a', d: '#8a3200', e: '#ff8a1a', E: '#ffe6a0',
  },
  // 리치 — 로브 5단 + 뼈 4단 + 왕관의 금
  lich: {
    k: '#000000', r: '#1c0f3c', R: '#2f1a66', T: '#4a2ba4', U: '#6b41d8', V: '#9268f5', a: '#8a8578', B: '#b8b2a0', w: '#eae4ce',
    W: '#fffaea', e: '#1b0f38', q: '#4fe6ff', Q: '#e8ffff', c: '#a8791a', C: '#e8b52c', Y: '#fff0a0', o: '#8f4ce8', O: '#e0c0ff',
  },
  gemBlue: { k: '#000000', g: '#12508f', G: '#2b8de0', L: '#6fc4ff', l: '#d8f0ff', W: '#ffffff' },
  gemGreen: { k: '#000000', g: '#136b32', G: '#2fae55', L: '#75e08e', l: '#dcffe6', W: '#ffffff' },
  gemRed: { k: '#000000', g: '#8e1f34', G: '#e04357', L: '#ff8e9a', l: '#ffe0e4', W: '#ffffff' },
  heart: { k: '#000000', d: '#8e1f34', H: '#e04357', h: '#ff8e9a', l: '#ffe0e4' },
  magnet: {
    k: '#000000', v: '#3d4757', m: '#6c7a90', M: '#a6b3c6',
    l: '#e8eef8', r: '#8e1f34', R: '#e04357', p: '#ff9ea6',
  },
  coin: { k: '#000000', d: '#8a5c10', c: '#c08c1c', C: '#f0bb2c', y: '#ffe07a', Y: '#fff6c8' },
  // 항아리 — 구운 흙에 푸른 무늬
  pot: {
    k: '#000000', d: '#6b3a17', c: '#96592a', C: '#c07840',
    n: '#e0a06c', l: '#f8ddb8', b: '#3f7ff0', B: '#9fd4ff',
  },
  // 상자 — 나무 · 쇠띠 · 금자물쇠
  chest: {
    k: '#000000', d: '#4a2a08', w: '#6e4110', W: '#9c6026', n: '#c98944', l: '#efb87c',
    i: '#2f3742', I: '#59657a', S: '#8e9bb0', c: '#c08c1c', C: '#ffd23f', Y: '#fff2b8',
  },
  rock: {
    k: '#000000', o: '#1f2b23', v: '#36483c', S: '#546a57',
    M: '#758b76', m: '#9aae97', g: '#3a7a36', G: '#5aa84e',
  },
  tuft: { k: '#000000', g: '#2b6b2c', G: '#3f8f3a', j: '#63bb52', y: '#a8d86a' },
  fungus: {
    k: '#000000', d: '#7a1f2a', r: '#c03040', R: '#f05464',
    p: '#ffb0b8', s: '#9a8a70', S: '#cdbfa2', l: '#efe4cf',
  },
  flower: { k: '#000000', y: '#c08c1c', Y: '#ffd23f', c: '#fff2b8', w: '#f0e8ff', g: '#2b6b2c', G: '#3f8f3a' },
  bones: { k: '#000000', a: '#4f4c40', B: '#6b6757', b: '#8f8a76', w: '#b0aa93' },
  stump: {
    k: '#000000', d: '#33200a', w: '#4d3010', W: '#6f4620',
    n: '#96683a', l: '#c19a6b', g: '#2b6b2c', G: '#3f8f3a',
  },
  grave: {
    k: '#000000', o: '#242b34', v: '#3b4551', S: '#5b6673', M: '#7d8896',
    m: '#a3adba', g: '#2b6b2c', G: '#3f8f3a', d: '#20261c',
  },
  arcane: { k: '#000000', v: '#4a2ba8', o: '#6f45e0', q: '#a184ff', O: '#d9c8ff', W: '#ffffff' },
  frost: { k: '#000000', v: '#1c5a8c', b: '#2f8fc4', c: '#5fc8ee', C: '#a8e8ff', W: '#ffffff' },
  rune: { k: '#000000', d: '#7a5416', p: '#a8791a', P: '#d9a01f', y: '#ffd23f', Y: '#fff6c8' },
  fire: { k: '#000000', d: '#8f2a00', f: '#d94e00', F: '#ff8a1a', y: '#ffc93f', Y: '#fff2b0' },
  zap: { k: '#000000', b: '#2b4fb8', z: '#5f9fff', Z: '#bfe0ff', W: '#ffffff' },
  // 바닥 타일 — 다섯 단이 서로 가깝다. 벌어지면 칸 경계가 드러난다
  ground: { a: '#2f4a26', b: '#38562d', c: '#426434', d: '#26401f', e: '#527f3d' },
  moss: { a: '#2b4522', b: '#335029', c: '#3d5e30', d: '#233b1c', e: '#4c7639' },
  path: {
    a: '#3d3527', b: '#473d2d', c: '#524734', d: '#31291e',
    e: '#5e5139', g: '#2a3d24', G: '#31472a', h: '#22331e',
  },
  // 아이템 아이콘 — 공격·패시브가 같은 팔레트를 나눠 쓴다
  item: {
    k: '#000000', r: '#8e1f34', R: '#e04357', p: '#ff9ea6', P: '#ffe0e4', g: '#166b32', G: '#33b558', j: '#7fe89b', b: '#1f4e9c', B: '#3f8ae8', C: '#9fd4ff', y: '#a8791a', Y: '#ffd23f',
    c: '#fff2b8', d: '#8f2a00', o: '#ff8a1a', O: '#ffc93f', a: '#4a5265', w: '#98a3b8', W: '#e8eef8', m: '#4d3010', M: '#96683a', n: '#c19a6b', v: '#4a2ba8', V: '#8a63f0', X: '#d9c8ff',
  },
  // 마법사 — 로브 5단 · 수염 3단 · 살갗 3단 · 지팡이 구슬
  wizard: {
    k: '#000000', q: '#170a3c', r: '#26125e', R: '#3a2296', T: '#5533ce', U: '#7d5cf0', c: '#b8851f', C: '#ffd23f', Y: '#fff2b8', x: '#a9744c', S: '#d89a6a', s: '#f7cba0',
    a: '#9aa6bd', B: '#cdd7ea', b: '#f4f8ff', w: '#5c3a19', W: '#8f6231', n: '#b98a4e', i: '#0b5c94', o: '#1f9fe0', O: '#5fd8ff', z: '#e6fbff', e: '#160e30',
  },
};

// ---- 마법사 ----
// 서 있는 자세 하나와 걸음 둘. lift를 번갈아 주면 걷는 동안 몸이 통통 튄다.
const WIZ = {
  stand: [
    '.......kURk...................',
    '.......kUUrk.......kkkk.......',
    '.......kUUTqk.....kzzzOk......',
    '.......kUUURqk...kzzzOOok.....',
    '.......kUYUTrqk..kzzOOooik....',
    '.......kCYCTRrqk.kOOOooiik....',
    '.......kUCUUTRrqkkOoooiiik....',
    '.......kUUUUTTRqqkoiiiiik.....',
    '.......kUUUUTTRrqqkiiiik......',
    '.......kCCCCCCcccccknWk.......',
    '.......kccccccccccccnWk.......',
    '......kTTTTTTRRRrrqqqWk.......',
    '.......krrrrrrqqqqqqnWk.......',
    '........kksxsssxSxkknwk.......',
    '.........ksessSeSxkknWk.......',
    '.........kssSSSSxxkknWk.......',
    '.........kSSSSSxxxkknWk.......',
    '.........kBSSxxxaxkknWk.......',
    '........kkbbbBBBaakknWk.......',
    '.......kTUbbbBBBaaqknWk.......',
    '.......kTUbbbBBBaaqknWk.......',
    '.......kTUbbbBBaaaTRqwk.......',
    '.......kUUUbbBBaaUTRqWk.......',
    '.......kUUUbbBBaaUTrqWk.......',
    '.......kUUrbbBBaUUTrqWk.......',
    '......kTUUrUbBBaUUTrqWk.......',
    '......kTUUrUUTTRqUTqsWk.......',
    '......kTUUrUUTTRqUsssSk.......',
    '......kTUUrUUTTRqrssSxk.......',
    '......kUUUrUUTTRqrSSxxk.......',
    '......kUUrUUUTTRqrqqnWk.......',
    '.....kTUUrUUUTTRqrqqqWk.......',
    '.....kTUUrUUUTTRqrrqqWk.......',
    '.....kTUUrUUUTTRRqrqqWk.......',
    '.....kTUUrUUUTTRRqrqqWk.......',
    '.....kCCCCCCCCcccccccWk.......',
    '.....kqqqqqqqqqqqqqqqWk.......',
    '......kkkRRRrkRRRrkkkk........',
    '.......kRRRrrkRRrrqk..........',
    '.......krrrqqkrrrqqk..........',
    '........kkqqk.kqqkk...........',
    '..........kk...kk.............',
  ],
  stepA: [
    '.......kURk...................',
    '.......kUUrk.......kkkk.......',
    '.......kUUTqk.....kzzzOk......',
    '.......kUUURqk...kzzzOOok.....',
    '.......kUYUTrqk..kzzOOooik....',
    '.......kCYCTRrqk.kOOOooiik....',
    '.......kUCUUTRrqkkOoooiiik....',
    '.......kUUUUTTRqqkoiiiiik.....',
    '.......kUUUUTTRrqqkiiiik......',
    '.......kCCCCCCcccccknWk.......',
    '.......kccccccccccccnWk.......',
    '......kTTTTTTRRRrrqqqWk.......',
    '.......krrrrrrqqqqqqnWk.......',
    '........kksxsssxSxkknwk.......',
    '.........ksessSeSxkknWk.......',
    '.........kssSSSSxxkknWk.......',
    '.........kSSSSSxxxkknWk.......',
    '.........kBSSxxxaxkknWk.......',
    '.........kbbbBBBaakknWk.......',
    '.........kbbbBBBaaqqnWk.......',
    '........kTbbbBBBaarqnWk.......',
    '........kTbbbBBaaaTRqwk.......',
    '........kTUbbBBaaUTRqWk.......',
    '........kUUbbBBaaUTrqWk.......',
    '........kUUbbBBaUUTrqWk.......',
    '........kUUrbBBaUUTrqWk.......',
    '.......kTUUrUUUTqUTqsWk.......',
    '.......kTUUrUUUTqUsssSk.......',
    '.......kTUUrUUTTTqssSxk.......',
    '.......kTUUrUUTTTqSSxxk.......',
    '.......kTUUrUUTTTqrrqqk.......',
    '.......kUUrUUUTTTqrrqqk.......',
    '.......kUUrUUUTTTRqrqqk.......',
    '......kTUUrUUUTTTRqrqqk.......',
    '......kTUUrUUUTTRRqrqqk.......',
    '......kCCCCCCCcccccccck.......',
    '......kqqqqqqqqqqqqqqqk.......',
    '......kRRRrkkkRRRrkkkk........',
    '......kRRrrqkkRRrrqk..........',
    '......krrrqqkkrrrqqk..........',
    '.......kqqqk..kqqkk...........',
    '........kkk....kk.............',
  ],
  stepB: [
    '.......kURk...................',
    '.......kUUrk.......kkkk.......',
    '.......kUUTqk.....kzzzOk......',
    '.......kUUURqk...kzzzOOok.....',
    '.......kUYUTrqk..kzzOOooik....',
    '.......kCYCTRrqk.kOOOooiik....',
    '.......kUCUUTRrqkkOoooiiik....',
    '.......kUUUUTTRqqkoiiiiik.....',
    '.......kUUUUTTRrqqkiiiik......',
    '.......kCCCCCCcccccknWk.......',
    '.......kccccccccccccnWk.......',
    '......kTTTTTTRRRrrqqqWk.......',
    '.......krrrrrrqqqqqqnWk.......',
    '........kksxsssxSxkknwk.......',
    '.........ksessSeSxkknWk.......',
    '.........kssSSSSxxkknWk.......',
    '.........kSSSSSxxxkknWk.......',
    '.........kBSSxxxaxkknWk.......',
    '.......kkkbbbBBBaakknWk.......',
    '......kTUUbbbBBBaakknWk.......',
    '......kTUUbbbBBBaakknWk.......',
    '......kUUUbbbBBaaaTRqwk.......',
    '......kUUUUbbBBaaUTRqWk.......',
    '.....kTUUUUbbBBaaUTrqWk.......',
    '.....kTUUrUbbBBaUUTrqWk.......',
    '.....kTUUrUUbBBaUUTrqWk.......',
    '.....kTUUrUUTTqRqUTqsWk.......',
    '.....kUUUrUUTTqRqUsssSk.......',
    '.....kUUUrUUTTRqrqssSxk.......',
    '.....kUUrUUUTTRqrqSSxxk.......',
    '....kTUUrUUUTTRqrqqknWk.......',
    '....kTUUrUUUTTRqrqqknWk.......',
    '....kTUUrUUUTTRqrqqknWk.......',
    '....kTUUrUUUTTRqrqqqnWk.......',
    '....kTUUrUUTTTRRqqqqnWk.......',
    '....kCCCCCCCCCccccccnWk.......',
    '....kqqqqqqqqqqqqqqqnWk.......',
    '.....kkkkRRRrkkkRRRrkk........',
    '.......kRRRrrkkRRRrqk.........',
    '.......krrrqqkkrrrqqk.........',
    '........kkqqk..kqqqk..........',
    '..........kk....kkk...........',
  ],
};

const wiz = (pose, lift) => ({ pal: 'wizard', art: 2, lift, rows: WIZ[pose] });

// ---- 프레임 목록 ----
// name → { pal, rows, art?, lift?, flat? }
export const MAPS = {
  'wizard.idle0': wiz('stand', 0),
  'wizard.idle1': wiz('stand', 1),
  'wizard.walk0': wiz('stepA', 1),
  'wizard.walk1': wiz('stand', 0),
  'wizard.walk2': wiz('stepB', 1),
  'wizard.walk3': wiz('stand', 0),

  // ---- 적 ----
  // 박쥐 — 날개를 올린 프레임과 내린 프레임
  'bat.0': {
    pal: 'bat', art: 2, lift: 1,
    rows: [
      '..........k......k...........',
      'kk.......kMk....kmk.......kk.',
      'VVkkk....kMMkkkkNmk....kkkWWk',
      'VVVVVkk..kMMMMmNmmk..kkWWWWWk',
      'VVVVVVVkkkMMMMmmmk.kkvWWWwvwv',
      'vvVvVVVVVkMMMmmNNmkvWWWWvwvwk',
      'vvWvVVVVVmmmEeNEenWWvvvvvwwwk',
      'kkkWvvvVVNmNeeneenvvvwwwwkkk.',
      '..kWvkWVVVNNnnnnnnvvvvkwwk...',
      '...kkkWvvvMnnFnFnWwwwwkkk....',
      '.....kWvWWMMnnnNnnwwwwk......',
      '......kWkvmmmmNNnnwkwk.......',
      '.......kkvmmNNNnnmwkk........',
      '.........kNNNNnnnmk..........',
      '.........kmNnnnnmwk..........',
      '..........kmnnnmmk...........',
      '...........kmmmmk............',
      '............kkkk.............',
    ],
  },
  'bat.1': {
    pal: 'bat', art: 2, lift: 0,
    rows: [
      '..........k......k...........',
      '.........kMk....kmk..........',
      '.........kMMkkkkNmk..........',
      '.........kMMMMmNmmk..........',
      '.........kMMMMmmmk...........',
      '.........kMMMmmNNmk..........',
      '........kmmmEeNEemk..........',
      '........kmmNeeneemk..........',
      '.......kkkNNnnnnnnvkk........',
      '...kkkkVVVMnnFnFnWvvvkkkk....',
      'kkkVVVVVVVMMnnnNnnwvvWvWWkkk.',
      'VVVVVVVVVvmmmmNNnnwwvvvWvWWWk',
      'VVVvVVvVvWmmNNNnnnwwwvwvvwvWk',
      'VvVvVWWvvWNNNNnnnnwwwwwwvwvwv',
      'vvWWvkWvWWnNnnnnnwwkwwkwwwwwk',
      'WWkWWkWWkkWmnnnmmwkkwwkwwkwwk',
      'Wk.kk.kk..kkmmmmkk..kk.kk.kwk',
      'k...........kkkk...........k.',
    ],
  },
  // 슬라임 — 통통 튈 때 몸이 눌린다
  'slime.0': {
    pal: 'slime', art: 2,
    rows: [
      '.........kkkkkkkk.........',
      '......kkkLLLLHHGGkkk......',
      '.....kllllLLLHHHGGgHk.....',
      '....kllllllLHHHHGGggHk....',
      '...kLllllllHHHHGGGgggHk...',
      '..kLLllllllHHHGGGggggdHk..',
      '.kLLLLllllHHHGGGGgggdddHk.',
      '.kLLLLLHHHHHGGGGgggddddHk.',
      'kHHHLLHHHHGGGGGggggdddddHk',
      'kHHHLLHeeeGGGggeeeddddddHk',
      'kGHHHHGeEeGGgggeEeddddddHk',
      'kGGGGGGeeegggggeeeddddddHk',
      'kGGGGGGeeeggggdeeeddddddHk',
      'kgggggggegggddddedddddddHk',
      'kHggggGGGGGedddedddddddHHk',
      '.kdggGGGGGGGeeeddddddddHk.',
      '.kHddGGGGGGGGdddddddddHHk.',
      '..kHddGGGGGGdddddddddHHk..',
      '...kHdddddddddddddddHHk...',
      '....kHHgggggggggggHHHk....',
      '.....kkHHHHHHHHHHHHkk.....',
    ],
  },
  'slime.1': {
    pal: 'slime', art: 2,
    rows: [
      '........kkkkkkkkkk.........',
      '......kkllLLHHHHGGkk.......',
      '....kklllllLLHHHGGGHkk.....',
      '...kLllllllLHHHHGGGggHk....',
      '..kLLllllllHHHHGGGgggdHk...',
      '.kLLLLllllHHHHGGGggggddHk..',
      'kHLLLLLHHHHHGGGGggggddddHk.',
      'kHHHLLHeeeGGGGGeeegdddddHk.',
      'HHHHHHHeEeGGGggeEedddddddHk',
      'GGGGGGGeeeGggggeeedddddddHk',
      'GGGGGGGeeeggggdeeedddddddHk',
      'HgGGggGGeGGGddddedddddddHHk',
      'kggggGGGGGGeGddeddddddddHk.',
      'kHgggGGGGGGGeeeddddddddHHk.',
      '.kHdddGGGGGGddddddddddHHk..',
      '..kHdddddddddddddddddHHk...',
      '...kHHgggggggggggggHHHk....',
      '....kkHHHHHHHHHHHHHHkk.....',
    ],
  },
  // 해골 — 다리가 번갈아 나간다
  'skeleton.0': {
    pal: 'bone', art: 2, lift: 0,
    rows: [
      '......kWWWwwk......',
      '.....kWWWWwwbk.....',
      '....kWWWWwwbbbk....',
      '...kWWeewweeBBbk...',
      '...kweQqeeQqeabk...',
      '...kbwqqebqqeabk...',
      '...kbbeeWWeeabbk...',
      '....kbWWWebbbbk....',
      '.....kwwwbBBbk.....',
      '.....kwewewewk.....',
      '....kkWWWWwwbkk....',
      '...kwwwwwbbBBabk...',
      '....kbBBaaaabbbk...',
      '...kbkwwwbbbbkbk...',
      '...kbbkkkbbkkbbbk..',
      '...kbbkkkbbkkbkbk..',
      '...kbwwwwbbbbbkbk..',
      '..kbbkkkkbbkkkkbbk.',
      '..kbkbbwwbbbabkkbk.',
      '..kbkwwkkbbkbbkkbk.',
      '..kbkkbkkbbkbk.kbk.',
      '.kWbkkWWWWwbbk.kWk.',
      'kWwbkwWwwwbBBbkWwbk',
      'kbbbkbbbbaBabbkbbbk',
      '.kbk.kbbbbbbbk.kbk.',
      '..k...kbkkkkbk..k..',
      '......kbk..kbk.....',
      '......kbk..kbk.....',
      '......kbk..kbk.....',
      '......kbk..kbk.....',
      '.....kbk...kbk.....',
      '.....kbk...kbk.....',
      '....kkbk...kbk.....',
      '...kwwk...kbbk.....',
    ],
  },
  'skeleton.1': {
    pal: 'bone', art: 2, lift: 1,
    rows: [
      '......kWWWwwk......',
      '.....kWWWWwwbk.....',
      '....kWWWWwwbbbk....',
      '...kWWeewweeBBbk...',
      '...kweQqeeQqeabk...',
      '...kbwqqebqqeabk...',
      '...kbbeeWWeeabbk...',
      '....kbWWWebbbbk....',
      '.....kwwwbBBbk.....',
      '.....kwewewewk.....',
      '....kkWWWWwwbkk....',
      '...kwwwwwbbBBabk...',
      '....kbBBaaaabbbk...',
      '...kbkwwwbbbbkbk...',
      '...kbbkkkbbkkbbbk..',
      '...kbbkkkbbkkbkbk..',
      '...kbwwwwbbbbbkbk..',
      '..kbbkkkkbbkkkkbbk.',
      '..kbkbbwwbbbabkkbk.',
      '..kbkwwkkbbkbbkkbk.',
      '..kbkkbkkbbkbk.kbk.',
      '.kWbkkWWWWwbbk.kWk.',
      'kWwbkwWwwwbBBbkWwbk',
      'kbbbkbbbbaBabbkbbbk',
      '.kbk.kbbbbbbbk.kbk.',
      '..k...kbkkkkbk..k..',
      '......kbk..kbk.....',
      '......kbk..kbk.....',
      '......kbk..kbk.....',
      '.......kbk.kbk.....',
      '......kbk..kbk.....',
      '......kbk...kbk....',
      '......kbk...kbk....',
      '.....kwwk...kbbk...',
    ],
  },
  // 유령 — 자락의 물결이 프레임마다 어긋난다
  'ghost.0': {
    pal: 'ghost', art: 2, lift: 0,
    rows: [
      '.........kkkkkk.........',
      '.......kkLLLLggkk.......',
      '......kLLLLLLGgggk......',
      '.....kLLLLLLLGGgugk.....',
      '....kLLLLLLLLGGggugk....',
      '...kLLLLLLLLLGGgguvgk...',
      '..kLLLLLLLLLGGGgguuvgk..',
      '..kLLLLeeLLLGGGeeuuvgk..',
      '..kLLLeeeeLLGGeeeeuvgk..',
      '..kLLeQqeeLGGGeQqeevgk..',
      '..kLLeqqqeGGGGeqqeevgk..',
      '.kLLLeqqqeGGGGeqqeevvgk.',
      '.kLLLLeqeLGGGGgeqeuvvgk.',
      '.kLLLLLeLLGGGGggeuuvvgk.',
      '.kLLLLLLLLGGGGggguuvvgk.',
      '.kLLLLLLLLGGGGggguuvvgk.',
      '.kLLLLLLLLeGGGegguuvvgk.',
      '.kLLLLLLLLGeeegguuuvvgk.',
      '.kLLLLLLLGGGGggguuuvvgk.',
      'kGLLLLLLGGGGGggguuvvvvgk',
      'kGLLLLLGGGGGggguuuvvvvgk',
      'kGLLLLGGGGGGggguuuvvvvgk',
      'kGGLLGGGGGGgggggguvvvggk',
      '.kGGGkGkkkgggggkkkvvvkk.',
      '..kGkGk...kgggk...kvkgk.',
      '...kGk...kgkgk.....kgk..',
      '....k.....kgk.......k...',
      '...........k............',
    ],
  },
  'ghost.1': {
    pal: 'ghost', art: 2, lift: 1,
    rows: [
      '.........kkkkkk.........',
      '.......kkLLLLggkk.......',
      '......kLLLLLLGgggk......',
      '.....kLLLLLLLGGgugk.....',
      '....kLLLLLLLLGGggugk....',
      '...kLLLLLLLLLGGgguvgk...',
      '..kLLLLLLLLLGGGgguuvgk..',
      '..kLLLLeeLLLGGGeeuuvgk..',
      '..kLLLeeeeLLGGeeeeuvgk..',
      '..kLLeQqeeLGGGeQqeevgk..',
      '..kLLeqqqeGGGGeqqeevgk..',
      '.kLLLeqqqeGGGGeqqeevvgk.',
      '.kLLLLeqeLGGGGgeqeuvvgk.',
      '.kLLLLLeLLGGGGggeuuvvgk.',
      '.kLLLLLLLLGGGGggguuvvgk.',
      '.kLLLLLLLLGGGGggguuvvgk.',
      '.kLLLLLLLLeGGGegguuvvgk.',
      '.kLLLLLLLLGeeegguuuvvgk.',
      '.kLLLLLLLGGGGggguuuvvgk.',
      'kGLLLLLLGGGGGggguuvvvvgk',
      'kGLLLLLGGGGGggguuuvvvvgk',
      'kGLLLLGGGGGGggguuugggvgk',
      'kGGkkGGGGGGgggguuugkkggk',
      '.kk..kGGGGgkkkuuukgk.kgk',
      '......kGGGk...kuggk...k.',
      '.......kGk...kgkgk......',
      '......kGk.....kgk.......',
      '.......k.......k........',
    ],
  },
  // 골렘(엘리트) — 이끼 낀 바위 덩어리. 가슴의 균열에서 용암이 샌다
  'golem.0': {
    pal: 'stone', art: 2, lift: 0,
    rows: [
      '..................kkkkkk...................',
      '................kkooooookk.................',
      '...............kooGGGggMook................',
      '...............kogggggMGSok................',
      '..............koGhhmGMMSvook...............',
      '..............kommEeMMEevook...............',
      '..............kommeeMSeeoook.kkk...........',
      '..........kkk.koMMMSSvvooookkoookkk........',
      '.......kkkoookkoSSooooooooooojjjoook.......',
      '......kooojGGookovvvooooooohjjjGGgook......',
      '.....koojGGGggGooooooooooohhGGggggvook.....',
      '....kooGgggggMSvooooooooomhGmmmGSSvook.....',
      '....kohhGmmMGSSvoohhoommommmmMMSSvoook.....',
      '....kommmmMMSSvooohhhmmmoMMMMSSvvoooook....',
      '...kooMMMMSSvvovvvhhhmmmoSSSSvvvoooooMok...',
      '..kohoSSSSvvvvvooohhhmmmMovvvvoooooooMok...',
      '..kohoovvvvoooooohhhhmmmMoovvvoooooomMSok..',
      '.kohhhoooooooooodhhhhmmMMMSooovoooommMvok..',
      '.kohhmmoooooooohhehhmmmMMMSvvoooohhmMSvok..',
      '.kohhmMSvoooohhhhdehmmmMMSSvoookohmmMSvok..',
      '.kohmmMSvokkohhhhhdemmmMMSSvookommmMSSvvok.',
      'kommmMSSvvokohhhhhhemmmMMSSvookoMmMMSvvvok.',
      'koMmMMSvvvokohhhhhhdemmMMSSdookoMMMSSvvvok.',
      'koMMMSSvvvokohhhhhhhEEmMMSdvookkoMSSvvvok..',
      '.koMSSvvvokkohhhhhhhmEEEMSdoookkoSSvvvvok..',
      '.koSSvvvvok.kohhhhhhmmmdeSdook.kooooooook..',
      '.kooooooook.kohhhhhhmmMMSdvook.koohhhmMSok.',
      'kohhhhmMook.kohdhhhhmmMMSSvook.kohhhmmMSook',
      'oohhhmMMSok.kohhddhhmmMMSSvookkomhmmMMSvvok',
      'ohhmmMMSvvokkohhhhdhmmMMSvvookkommmMMSvvvok',
      'ommMMMSvvvokkkohhhhdmmMMSvookkkoMMMSSvvvvok',
      'oMMSSSvvvvoohhohhhhmmmMMSvooSvokoSvvvvvvook',
      'ooSvvvvvvokohhohhhhmmmMMSvooSvokoovvvvvvok.',
      'kovvvvvvookohhhhmMvokkohhhmMSvokkoooooook..',
      '.koooooookkohhhmmSvokkohhhmMSvok.kkkkkkk...',
      '..kkkkkkk.kohhhmmSvokkohhhmMSook...........',
      '..........kohhhmMSvokkohhhmMSook...........',
      '..........kohhhmMSvokkohhhmMSook...........',
      '..........kohhhmMSookkohhhmMSook...........',
      '...........kohhmMSookkohhhmMSok............',
      '...........kohhmMSookkohhhhmMok............',
      '...........khhhmmMSokkhhhmmMSSvk...........',
      '..........kmmmmMMSvvkkmmMMSSvvvk...........',
      '..........kMMMSSvvvvkkSSSvvvvvvk...........',
    ],
  },
  'golem.1': {
    pal: 'stone', art: 2, lift: 1,
    rows: [
      '..................kkkkkk...................',
      '................kkooooookk.................',
      '...............kooGGGggMook................',
      '...............kogggggMGSok................',
      '..............koGhhmGMMSvook...............',
      '..............kommEeMMEevook...............',
      '..........kkk.kommeeMSeeoook...............',
      '.......kkkoookkoMMMSSvvooook.kkk...........',
      '......kooohmGoooSSoooooooookkoookkk........',
      '.....koojjjGGgSoovvvooooookoojjGoook.......',
      '....koojjGGGggGvooooooooooohGGggggook......',
      '....kohGgggggSSvoooooooooohGhhmGMSvook.....',
      '....kommGmMMGSvooohhoommomhhmmmMSSvook.....',
      '...kooMMMMSSvvoooohhhmmmommmmMMSSvoook.....',
      '..kohoSSSSvvvoovvvhhhmmmoMMMMSSvvoooook....',
      '..kohoovvvvovvvoohhhhmmmoSvSSvvvoooooMok...',
      '.kohhhooooooooooohhhhmmmMovvvvoooooooMok...',
      '.kohhmmoooooooohdhhhhmmMMooooovooooomMSok..',
      '.kohhmMSvoooohhhhehhmmmMMMSoooooooommMvok..',
      '.kohmmMSvokohhhhhdehmmmMMSSvooooohhmMSvok..',
      'kommmMSSvvokohhhhhdemmmMMSSvookkohmmMSvok..',
      'koMmMMSvvvokohhhhhhemmmMMSSvookommmMSSvvok.',
      'koMMMSSvvvokohhhhhhdemmMMSSdookoMmMMSvvvok.',
      '.koMSSvvvokkohhhhhhhEEmMMSdvookoMMMSSvvvok.',
      '.koSSvvvvokkohhhhhhhmEEEMSdoookkoMSSvvvok..',
      '.kooooooook.kohhhhhhmmmdeSdook.koSSvvvvok..',
      'kohhhhmMook.kohhhhhhmmMMSdvook.kooooooook..',
      'oohhhmMMSok.kohdhhhhmmMMSSvook.koohhhmMSok.',
      'ohhmmMMSvvokkohhddhhmmMMSSvook.kohhhmmMSook',
      'ommMMMSvvvokkohhhhdhmmMMSvvookkomhmmMMSvvok',
      'oMMSSSvvvvokkkohhhhdmmMMSvookkkommmMMSvvvok',
      'ooSvvvvvvokohhohhhhmmmMMSvooSvooMMMSSvvvvok',
      'kovvvvvvookohhohhhhmmmMMSvooSvokoSvvvvvvook',
      '.koooooookkohhhhmMvokkohhhmMSvokoovvvvvvok.',
      '..kkkkkkk.kohhhmmSvokkohhhmMSvokkoooooook..',
      '..........kohhhmmSvokkohhhmMSook.kkkkkkk...',
      '..........kohhhmMSvokkohhhmMSook...........',
      '..........kohhhmMSvokkohhhmMSook...........',
      '..........kohhhmMSookkohhhmMSook...........',
      '...........kohhmMSookkohhhmMSok............',
      '...........kohhhmMookkohhhmMSok............',
      '..........khhhmmMMSvkkohhhmmMSk............',
      '..........kmmMMMSvvvkkmmmmMMSvvk...........',
      '..........kSSSvvvvvvkkMMMSSvvvvk...........',
    ],
  },
  // 리치(보스) — 왕관 쓴 해골. 가슴의 마력 핵이 프레임마다 부푼다
  'lich.0': {
    pal: 'lich', art: 2, lift: 0,
    rows: [
      '.................kkrrrrrrkk.................',
      '...............kkrrVVcYUUrrkk...............',
      '..............krrVVVVcCUUUTrrk..............',
      '.............krrVcYVVcCUUcYTrrk.............',
      '............kcYVVcCeecCeecCTRcYk............',
      '............kYCCYCCYCCYCCYCCYCCYk...........',
      '...........krccccccccccccccccccck...........',
      '...........krVVVeeWWWWWwwBeeRrrrk...........',
      '..........krrVVeeWWWWWWwwBBeerrrrk..........',
      '..........krUVVeeWWWWWwwwBBeerrrrk..........',
      '..........krUUeeWWeeeweeeBaaeerrrk..........',
      '..........krUUeeWeQqewQqqeaaeerrrk..........',
      '..........krTUeeweqqeweqqeaaeerrrk..........',
      '..........krTTeewweqeBeqeaaaeerrrk..........',
      '..........krTTeeBBBBBWWaaaaaeerrrk..........',
      '.....kkkkkkrrTeeeBBWWWewBaaeeerrrkkkkkk.....',
      '...kkrrrrrrrrRReeaWWwwwBBaaeerrrrrrrrrrkk...',
      '..krrVVVVVUUrRReeewwBBBaaaeeerrrVVVVUUTrrk..',
      '.krrVVVVVVVUUrrreeeeweweweeerrrVVVVVVUURrrk.',
      'krrVVVVVVUUUTrrreeeeeaaeeeeerrrVVVVUUUTTrrrk',
      'krUVVUUUUUUTTTrrrreeeeeeeerrrrVUUUUUUTTTrrrk',
      'krUUUUUTTTTTTTrrrrreeeeeerrrrUUUUTTTTTTTrrrk',
      'krTTTTTTTTTTrrrrrrrrroorrrrrTTTTTTTTTTrrrrrk',
      'krrRRRRRrrrrrrrrrVVooooooUTrrRRRRRrrrrrrrrrk',
      '.krrVVVVVUTRrrrrVVooOOOOooTTrrrVVVVVUUTRrrk.',
      '..krVVVVVUTRrrrVVVoOWWWOOoRTTrrVVVVVUTTrrk..',
      '..krVVVVVUTRrVVVVooOWWWOOooTTTRrVVVVUTRrrk..',
      '...krVVVVUTRrVVVVooOWWOOOooTTTRrVVVVUTRrk...',
      '...krVVVUUTRrVVVVRoOOOOOOoRTTTRrVVVVUTRrk...',
      '...krVVVUUTRrVVVVRooOOOOooRTTTRrVVVVUTRrk...',
      '...krVVVUUTrrVVVVRToooooorRTTTRrVVVVUTRrk...',
      '...krVVVUUTrrVVVVRTVVooUUrRTTTTrVVVUUTRrk...',
      '...krVVVUURrrVVVVRTVVVUUUrRTTTTrVVVUUTrrk...',
      '...krVVVUTRrVVVVVRTVVVUUUrRTTTTRrVVUUTrrk...',
      '....krVVUTRrVVVVVRTVVVUUUrRTTTTRrVVUURrk....',
      '....krVVUTRrVVVVVRTVVVUUUrRTTTTRrVVUTRrk....',
      '....kraaaaRrVVVVRTVVVVUUUrRTTTTRrVaaaark....',
      '....kaWWwBarVVVVRTVVVUUUUrRTTTTRraWWWwak....',
      '...kaWWWwBarVVVVRTVVVUUUUrRTTTTTraWWwBaak...',
      '...kawwwBaaaVVVVRTVVVUUUUUrRTTTTawwwBBaak...',
      '...kaBBBaaaVVVVVRTVVVUUUUUrRTTTTRaBBBaaak...',
      '...kUaaaaaaVVVVVRTVVVUUUUUrRTTTTRaaaaaark...',
      '...kUVaaaaVVVVVVRTVVVUUUUUrRTTTTRRaaaarrk...',
      '..kUVVVRTVVVVVVVRTVVUUUUUUrRTTTTRRrRrrrrrk..',
      '..kUVVVRTVVVVVVVRTVVUUUUUUrRTTTTRRRrRrrrrk..',
      '..kUVkkRTVVVVVVVRTVVUUUUUUrRTTTTRRRrRkkrrk..',
      '.kUUk..kVVVVVVVRTVVVUUUUUUrRTTTTRRRrRk.krrk.',
      '.kUk...kVVVVVVVRTVVVUUUUUUrRTTTTRRRrRk..krk.',
      '..k.....kVVVVVVkkkVVUUUUUUkkkTTTTRRkk....k..',
      '........kVVVVVk...kUUUUUUk...kTTTRRk........',
      '.........kVVVVk...kUUUUUUk...kTTTRk.........',
      '..........kVkk.....kUUUUk.....kkTk..........',
      '...........k........kUUk........k...........',
      '.....................kk.....................',
    ],
  },
  'lich.1': {
    pal: 'lich', art: 2, lift: 1,
    rows: [
      '.................kkrrrrrrkk.................',
      '...............kkrrVVcYUUrrkk...............',
      '..............krrVVVVcCUUUTrrk..............',
      '.............krrVcYVVcCUUcYTrrk.............',
      '............kcYVVcCeecCeecCTRcYk............',
      '............kYCCYCCYCCYCCYCCYCCYk...........',
      '...........krccccccccccccccccccck...........',
      '...........krVVVeeWWWWWwwBeeRrrrk...........',
      '..........krrVVeeWWWWWWwwBBeerrrrk..........',
      '..........krUVVeeWWWWWwwwBBeerrrrk..........',
      '..........krUUeeWWeeeweeeBaaeerrrk..........',
      '..........krUUeeWeQqewQqqeaaeerrrk..........',
      '..........krTUeeweqqeweqqeaaeerrrk..........',
      '..........krTTeewweqeBeqeaaaeerrrk..........',
      '..........krTTeeBBBBBWWaaaaaeerrrk..........',
      '.....kkkkkkrrTeeeBBWWWewBaaeeerrrkkkkkk.....',
      '...kkrrrrrrrrRReeaWWwwwBBaaeerrrrrrrrrrkk...',
      '..krrVVVVVUUrRReeewwBBBaaaeeerrrVVVVUUTrrk..',
      '.krrVVVVVVVUUrrreeeeweweweeerrrVVVVVVUURrrk.',
      'krrVVVVVVUUUTrrreeeeeaaeeeeerrrVVVVUUUTTrrrk',
      'krUVVUUUUUUTTTrrrreeeeeeeerrrrVUUUUUUTTTrrrk',
      'krUUUUUTTTTTTTrrrrreeeeeerrrrUUUUTTTTTTTrrrk',
      'krTTTTTTTTTTrrrrrrroooooorrrTTTTTTTTTTrrrrrk',
      'krrRRRRRrrrrrrrrrVooOOOOooTrrRRRRRrrrrrrrrrk',
      '.krrVVVVVUTRrrrrVooOOOOOOooTrrrVVVVVUUTRrrk.',
      '..krVVVVVUTRrrrVVoOOWWWOOOoTTrrVVVVVUTTrrk..',
      '..krVVVVVUTRrVVVVoOOWWWOOOoTTTRrVVVVUTRrrk..',
      '...krVVVVUTRrVVVVoOOWWWOOOoTTTRrVVVVUTRrk...',
      '...krVVVUUTRrVVVVoOOOOOOOOoTTTRrVVVVUTRrk...',
      '...krVVVUUTRrVVVVooOOOOOOooTTTRrVVVVUTRrk...',
      '...krVVVUUTrrVVVVRooOOOOooRTTTRrVVVVUTRrk...',
      '...krVVVUUTrrVVVVRToooooorRTTTTrVVVUUTRrk...',
      '...krVVVUURrrVVVVRTVVVUUUrRTTTTrVVVUUTrrk...',
      '...krVVVUTRrVVVVVRTVVVUUUrRTTTTRrVVUUTrrk...',
      '....krVVUTRrVVVVVRTVVVUUUrRTTTTRrVVUURrk....',
      '....krVVUTRrVVVVVRTVVVUUUrRTTTTRrVVUTRrk....',
      '....kraaaaRrVVVVRTVVVVUUUrRTTTTRrVaaaark....',
      '....kaWWwBarVVVVRTVVVUUUUrRTTTTRraWWWwak....',
      '...kaWWWwBarVVVVRTVVVUUUUrRTTTTTraWWwBaak...',
      '...kawwwBaaaVVVVRTVVVUUUUUrRTTTTawwwBBaak...',
      '...kaBBBaaaVVVVVRTVVVUUUUUrRTTTTRaBBBaaak...',
      '...kUaaaaaaVVVVVRTVVVUUUUUrRTTTTRaaaaaark...',
      '...kUVaaaaVVVVVVRTVVVUUUUUrRTTTTRRaaaarrk...',
      '..kUVVVRTVVVVVVVRTVVUUUUUUrRTTTTRRrRrrrrrk..',
      '..kUVVVRTVVVVVVVRTVVUUUUUUrRTTTTRRRrRrrrrk..',
      '..kUVVVRTVVVVVVVRTVVUUUUUUrRTTTTRRRrRrrrrk..',
      '...kVVRTVVVVVVVRTVVVUUUUUUrRTTTTRRRrRrrrk...',
      '...kVVRTVVkkkVVRTVVVUUUUUUrRTTTkkkRrRrrrk...',
      '....kVRTVk..kVVRTVVVUkkUUUrRTTTk..krRrrk....',
      '....kVRTk....kVRTVVUk..kUUrRTTk....krRrk....',
      '.....kkk......kRTVVk....kUrRTk......kkk.....',
      '..............kVVVVk....kUUTTk..............',
      '...............kVkk......kkTk...............',
      '................k..........k................',
    ],
  },

  // ---- 주워 먹는 것 ----
  // 경험치 보석 — 같은 형태에 팔레트만 갈아 끼운다
  'gem.blue': {
    pal: 'gemBlue', art: 2,
    rows: [
      '....klLGk....',
      '...kllLGk....',
      '..kllLLGGk...',
      '.klWWLLGGGk..',
      'kllWlLLLGGGk.',
      'lllllLLLGGGGk',
      'LLLLLLGGGGGGG',
      'LLLLGGLGggggk',
      'kLLLGGLgggggk',
      'kLLLLGLggggk.',
      '.kLLLGLgggk..',
      '..kLLGLggk...',
      '..kLLGLggk...',
      '...kLLLgk....',
      '....kLLk.....',
    ],
  },
  'gem.green': {
    pal: 'gemGreen', art: 2,
    rows: [
      '....klLGk....',
      '...kllLGk....',
      '..kllLLGGk...',
      '.klWWLLGGGk..',
      'kllWlLLLGGGk.',
      'lllllLLLGGGGk',
      'LLLLLLGGGGGGG',
      'LLLLGGLGggggk',
      'kLLLGGLgggggk',
      'kLLLLGLggggk.',
      '.kLLLGLgggk..',
      '..kLLGLggk...',
      '..kLLGLggk...',
      '...kLLLgk....',
      '....kLLk.....',
    ],
  },
  'gem.red': {
    pal: 'gemRed', art: 2,
    rows: [
      '....klLGk....',
      '...kllLGk....',
      '..kllLLGGk...',
      '.klWWLLGGGk..',
      'kllWlLLLGGGk.',
      'lllllLLLGGGGk',
      'LLLLLLGGGGGGG',
      'LLLLGGLGggggk',
      'kLLLGGLgggggk',
      'kLLLLGLggggk.',
      '.kLLLGLgggk..',
      '..kLLGLggk...',
      '..kLLGLggk...',
      '...kLLLgk....',
      '....kLLk.....',
    ],
  },
  'heart': {
    pal: 'heart', art: 2,
    rows: [
      '.kkhhk..khhkk..',
      'khhhhHkkhhhhHk.',
      'hhhllldhhhhHHdk',
      'hhhlllhhhhHHHdk',
      'hHHlllHhHHHHddd',
      'hhhhHHHHHHddddd',
      'hhhhHHHHHHddddk',
      'khhhhHHHHddddk.',
      '.khhhHHHHdddk..',
      '..khhHHHHddk...',
      '...khhHHddk....',
      '...khhHHddk....',
      '....khhddk.....',
      '.....kkdk......',
    ],
  },
  'magnet': {
    pal: 'magnet', art: 2,
    rows: [
      '...kvvvvvvk....',
      '..kvmmMmvvvk...',
      '.kvmMMlmmmvvk..',
      'kvmMllkkmmmvvk.',
      'kmMllk..kmmmvk.',
      'vmMlk....kmmvvk',
      'vmMlk....klMmvk',
      'vmMlk....klMmvk',
      'vmMlk....klMmvk',
      'vmMlk....klMmvk',
      'vmMlk....klMmvk',
      'rRRpk....kpRRrk',
      'rRRpk....kpRRrk',
      'rRRpk....kpRRrk',
      'kkkk......kkkk.',
    ],
  },
  'coin': {
    pal: 'coin', art: 2,
    rows: [
      '..kkyyyCkk...',
      '.kyyyyyCCck..',
      'kyyYYYYyCcck.',
      'kyYYYYyyCcck.',
      'yyYYYydCCcddk',
      'CyYyydCdccddk',
      'CCyydCYcdcddk',
      'cCCCCdcdccddk',
      'kcccccdcccdk.',
      'kddccccccddk.',
      '.kddddddddk..',
      '..kkddddkk...',
      '....kkkk.....',
    ],
  },

  // ---- 부술 수 있는 물건 ----
  // 상자 — 엘리트와 보스가 떨군다
  'chest': {
    pal: 'chest', art: 2,
    rows: [
      '.....kkkkkkkkkk......',
      '....kIlllllnnWWk.....',
      '..kkSIllllnnwWWIkk...',
      '.kllSIlllnnnwWWIidk..',
      '.kllSIlnwnnWwWwIidk..',
      'knllSInnwWWWwwwIiddk.',
      'knwnSInWwCCCwwwIiddk.',
      'kWwWSIWWwCccwddIiddk.',
      'kdddSIdddCccdddIidddk',
      'nnwnSInnwCYcwWWIiwddk',
      'nnwnSInnwCkcwWWIidddk',
      'WnwnSInnwCccwWWIidddk',
      'WnwnSInnwCccwWWIidddk',
      'WnwnSInnwnnWwWwIidddk',
      'WnwnSInnwnWWwWwIidddk',
      'WnwnSInnwnWWwWwIidddk',
      'knwnSInnwnWWwwwIidddk',
      'kdddddddddddddddddddk',
    ],
  },
  // 항아리 — 부수면 금화 · 회복 · 자석이 나온다
  'pot': {
    pal: 'pot', art: 2,
    rows: [
      '.....kkkkkkkk.....',
      '...kkllCCCCnCkk...',
      '..kllCkkkkkddcck..',
      '..knnnddddddccck..',
      '...kCccccccccCk...',
      '..kCnnnnnCCcddCk..',
      '..kCnnnnnCCccdCk..',
      '.klnnlnnnCCccddCk.',
      '.kCnlllnnCCccddCk.',
      'kllllllnnnCCcccdCk',
      'knnnlllnCCCcccddCk',
      'knnBBBBBbbbbbbbbCk',
      'kCnbbbbbbbbbbbbbCk',
      'kCCCCCcccccdddddCk',
      'kccccccccddddddCCk',
      '.kccccdddddddddCk.',
      '.kCCdddddddddCCCk.',
      '..kkCdddddddCCkk..',
      '....kCCCCCCCCk....',
      '.....kkkkkkkk.....',
    ],
  },

  // ---- 배경 장식 ----
  'rock': {
    pal: 'rock', art: 2,
    rows: [
      '....kkkkkk.....',
      '..kkmmmmMSkk...',
      '.kmmmmmMMGGvk..',
      'kmmmmmmMGGGvok.',
      'kmmmmmMMvggvok.',
      'MmmmmmMSvSvvook',
      'MMmmmSSSvvvoook',
      'SMMSSSSvvvvoook',
      'SSSSSvvvoovoook',
      'kvvvvvoooooook.',
    ],
  },
  'tuft': {
    pal: 'tuft', art: 2,
    rows: [
      '.......k.......',
      '...k..kjk......',
      '..kyk.kjk..k...',
      'k..kykkGk.kjk..',
      'yk.kjkkGkkjk..k',
      'yk.kjkkGkGk..kj',
      'kjkkjkkGkGkkkjk',
      '.kjkjkkGkGkgkk.',
      '.kjgjgkGgGgggk.',
      '..kjgjgGgGgggk.',
    ],
  },
  'mushroom': {
    pal: 'fungus', art: 2,
    rows: [
      '.....kk......',
      '..kkkppkkk...',
      '.kpppppRRrk..',
      'kpppppRRRrdk.',
      'ppppppRRrrddk',
      'RRRRRRrrpdddk',
      'RRRprrrrddddk',
      'rdddddddddpdk',
      'kdddddpddddk.',
      '.kddddddddk..',
      '..kllddssk...',
      '..kSllSssk...',
      '..klllSSsk...',
    ],
  },
  'flower': {
    pal: 'flower', art: 2,
    rows: [
      '....k....',
      '..kkYkk..',
      '.kwcYYyk.',
      '.kcccYkk.',
      'kYYcYYkyk',
      '.kYYYYkk.',
      '.kYkgkyk.',
      '..kkYkk..',
      '.kGkgGk..',
      'kgkkgGGk.',
      '.k.kgGk..',
      '...kgGk..',
    ],
  },
  'bones': {
    pal: 'bones', art: 2,
    rows: [
      'kkkk........kkkk.',
      'wwbBk......kwwbBk',
      'wbBBk......kwbBBk',
      'BBBBBkkk.kkkBBBBk',
      'kkkbbbBBkBBbbbkk.',
      '...kkkbkBkbkkk...',
      'kkkkkBBbbbBBkkkk.',
      'wwbBBkbkkkbkwwbBk',
      'wbBBbbk...kbwbBBk',
      'BBBBkk.....kBBBBk',
      'kkkk........kkkk.',
    ],
  },
  'stump': {
    pal: 'stump', art: 2,
    rows: [
      '.....kkkkkk.....',
      '..kkkllllllkkk..',
      '.kllllnnnWllllk.',
      'klllnnnllnWnlllk',
      'kllnnnllllnWnllk',
      'knlllnnnnnnlWldk',
      'kWnnllllllllwddk',
      'kWdGddwddwddwddk',
      'kGGGgnwnWwWwwddk',
      'kGgggnwnWwWwwddk',
      'kWggnnwnWwWwwddk',
      '.knwnnwnWwwwwdk.',
      '.knwnnwnWwwwwdk.',
      '.knnnnnnWWwwddk.',
    ],
  },
  'grave': {
    pal: 'grave', art: 2,
    rows: [
      '....kkmMkk.....',
      '...kmmmMMSk....',
      '..kmmmMMSSvk...',
      '..kmmMMSSvok...',
      '.kMMMSvovoook..',
      '.kMSSSooooook..',
      '.kMvvoooooook..',
      '.kMMooooooook..',
      '.kMMMMooSvvok..',
      '.kMMMMooSvvok..',
      '.kGGMMooSvvok..',
      '.kGGgMooSvvok..',
      'kGgggMMSSvvook.',
      'kSggMMMSSvvook.',
      'vSMMMMMSSvvoodk',
      'vSMMMMMSSvvoodk',
      'kdddddddddddddk',
    ],
  },

  // ---- 바닥 타일 ----
  // 잡티를 칸마다 흩뿌리면 노이즈로 보인다. 덩어리로 뭉치고 결을 넣어야 풀밭이 된다.
  // 가장자리는 기본색만 남겨 이웃 타일과의 이음새를 감춘다.
  'tile.grass0': {
    pal: 'ground', art: 2, flat: true,
    rows: [
      'bbaaaaabbbbbbbbbaaaaaaaaaaaebbbb',
      'bbaaaabbbbbbbbbbaaaaeaaaaaebbbbb',
      'baaaabbbbbbbbbbbdcdeaaaaaadabbbb',
      'aaaabbbbbbbbbbbdcdceaaaaadaaaaaa',
      'aaaaabbbbbbbbbadcdccaaaaddaaaaaa',
      'aaaaaabbbbbbbaacccccaaadaaaaaaaa',
      'aaaaadaaaaaaaaaccccccccdaaaaaaaa',
      'aaaaadaaaaaaaaaccccccccccaaaaaaa',
      'aaaaabbbbbaaaaaaccccccccccaaadaa',
      'aaaabbbbbbbaaaaaacccccccccaadaaa',
      'aaaaabbbbeaaaaaaacccccccccaadaaa',
      'adaaaaaaeaaaaaaaaacccccccaaadaaa',
      'adaaaaaeeaaaaaaaaaaacceaaaadeaaa',
      'aaaaaaeaaaaaaaaaaaaaaaeaaaadaaaa',
      'aaaabaeaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaabbbbbbaaaadaaaaaaaaaaaaabaaaa',
      'aabbbbbbbbaaadaaaaaaaaaabbbbebba',
      'aabbbbbbbaaaaaaaaaaaaaabbbbebbbd',
      'aabbbbbaaaaaaaaaaaaaaaabbbbebbbd',
      'aaabbbaaaaaaaaaaaeeaaaabbbbbbbbb',
      'aaaabdaaaaaaaaaaeebbdddabbbbbbba',
      'aaaaadaaaaaaaaadeebbddddaaabaaaa',
      'aaaaaaaaaaaaabaabbbbbddaaaaaaaaa',
      'aaaaaaaaaabbbbbbbdbbbaaaaaaaaaaa',
      'aaaaaaaaebbbbbbbbdbbbaaaaaaaaaaa',
      'aaaaaaaeaabbbbbbbbbbbbbbbaaaaaaa',
      'aaeaaaaeaaaaabaaabbbbbbbbbaeaaaa',
      'aeaaaaaaaaaaaaaaaabbbbbbbbbeaaaa',
      'bdaaaaaaaaaaaaaaaaabbbbbbbaabbbb',
      'dbaaaaaaaaaaaaaaaaaabbbbbaabbebb',
      'dbaaaaaaaaaaaaaaaaaaaaaaaaabebbb',
      'bbaaaaaaaaabaaaaaaaaaaaaaaabebbb',
    ],
  },
  'tile.grass1': {
    pal: 'ground', art: 2, flat: true,
    rows: [
      'bbbbbbbdddedddddaeaaaaaaaaaacccc',
      'ccabaadddddddddddaaaaaaaaaeccccc',
      'ccaaaaadddddddddaaaeaaaaaeaccccc',
      'ccaaeaaaadddddaaaaeaaaaaaeaccecc',
      'caaaeaaaaaaaaaaaaaeeaaaaaaaacecc',
      'caaaaaaaaaaaaaaaaaeaaaaaaaabcecc',
      'aaaaaeaaaaaaaaaaaaeaaaaaaaaeebcb',
      'baccceaaaaaaaaaaaaaaaaaaaaedebbb',
      'cccccccaaaaaaaaaaaaaaaaaaaebbbbb',
      'cccccccaaaaaaaaaaaaaaaaadadbbbbb',
      'ccccccdcaaaaaaaaaaaaaaadaaaabbba',
      'ccccccdcaaaaaaaaaaaaaaadaaaaaaaa',
      'ccccccccaaaaaaaaaaaaaaaaaaaaaaaa',
      'cccccccaaaaaaaaaaaaaaaaaaaaaaaaa',
      'cccccccaaaaacccccabbbbbaaaaaaaaa',
      'aaeccaaaeaaccccccbbbbbbbdaaaaaaa',
      'aeaaaaaeaaccccccbbbebbbbdaaaaaaa',
      'aeaaaaaeaaccccccbbebbbbbbaaeaaaa',
      'aaaaaaaaaaccccccbbebbbbbbaaeaaaa',
      'bbbbbaaaaabbbccccbbbbebbbbaaaaaa',
      'bbbbbaaaabbbbbcccabbebbbbbbaaeaa',
      'bbbbbbaaabbbbbaaaaaaeabbbbbaaeaa',
      'bbbbbbaabbbbbbbaaaaaaabbbbbaaaaa',
      'bbbbbbdaabbbbbaaaaaaaabbbbbabaad',
      'bbbbedaaabbbbbaaaaaaaabdbbbbbbbb',
      'bbbebaaaaabbbaaaaaaaaadbbbbbbbbb',
      'bbbebbbaaaaaaaaaaaaaaadabbbbbbbe',
      'bbbbbbbbaaaaaaaaaaaaaaabbbbbbbeb',
      'bbbbbbbbaaaaabbbaaaaaaaabbbbbbee',
      'bbbbbbbbaaaabbbbbaaaaaaaebbbbbbe',
      'bbbbbbbbaaaaabbbaaaaaaaeabbbbbbb',
      'bbbbbbbbaaadaaaaaaaaaaaeaaaabaca',
    ],
  },
  'tile.moss0': {
    pal: 'moss', art: 2, flat: true,
    rows: [
      'cccccccaabbbbbddadaaaaaaaaaeeaaa',
      'ccceccccaaabaadadaaaaaaaaaaeaaaa',
      'cccecccccaaaaaaadaeaaaaaaaaaaaac',
      'ccccccccaaaaaaaaaaeaabbbbbaaaaaa',
      'cccccccaaaaaaaaaaaabbbbbbbbbaaaa',
      'aacccaaaaaaaaaabbbbbbbbbbbbbadaa',
      'aabbbaaaaaaaaabbbbbbbbbbbbebadaa',
      'abbbbbaaaaaaabbbbbbbbbbbbbebaaae',
      'abbbbbaaaaaeaabbbbbbbbbbbbbbaaae',
      'abbbbbaaaaeaaaabbbbbbebbbbaaaaaa',
      'aabbbaaaaaeaaadddbbbeadaaaaaaaaa',
      'aaaaaaaaaaaaadddddaaedaaaaaaaaaa',
      'aaaaaaaaaaaaaddddddccdaaaaaaaaaa',
      'aaaaaaaaaaaaadddddccccaaaaaaaaaa',
      'aaaaaaaaaaaaadddddcccccaaaaaaaaa',
      'aaaaadaaaaaaaacccccccccaaaaaaaaa',
      'addddddddeaaaaccdccccccaaaaaaaaa',
      'ddddddddeddaaaacdcccccaaaaaaaaaa',
      'adddddddedaaaaaacccccaaaaaaaaaaa',
      'aaaaadaaaaaaaaaaaadddddaaaaaaadd',
      'aaaaaaaaaaaaaaaadddddddddaaaeadd',
      'aaaaaaadaaaaaaadddddddddddbebebb',
      'baaaaadaaaaaaaaadddddddddbbebebb',
      'bbbaaadaaaaaaaeeaadddddabbbbbbbb',
      'bbbaaaaaaaaaaeaeaaaaaaaabbbbbbdb',
      'bbbbaaaaaaaaaeaaaaaaaaaabbbbbbdb',
      'bbbaaaaaaaaadaaaaaaaaaaabbebdbbb',
      'bbbaadadaaadaaaaaaaaaaabbebbdbbb',
      'badddddddebdbbaaaaaaaaabbebbbbbb',
      'aadddddddebbbbdaaaaaaaabbbbbaaaa',
      'aadddddddbbbbbdaaaaaaaaaaaaaaaaa',
      'aaaaadaabbbbbbbaaaaaaaaaaaaaaaaa',
    ],
  },
  'tile.moss1': {
    pal: 'moss', art: 2, flat: true,
    rows: [
      'aaaacccaaaaaaadaaaaaaaaaaaaaaaaa',
      'aaacccccaaaaadaaaaaaaaaaaaaaaaaa',
      'aacccccccaaaadaabbbbbaaaaaaaaaaa',
      'aacccccccaaaaaabbbbbbbaaaaaaaaaa',
      'aacccccccaaaaabbbbbbbbbaaaaaaada',
      'aaecccccaaaaaaabbebbbbbbaaaaaada',
      'cecacccaaaaaaaaebebbbbbbaaaaaaaa',
      'cecccaaaaeaaeaaebbbbbbbbaaaaaaac',
      'cccccaaaaeaeaaaabbbbbbbaaaaaaaac',
      'cccecdaaaaaeabbbbbbbbbaaaaaaaaac',
      'cceadaaaaaaaabbbbbaaaaaaaaaaaaaa',
      'aaeadaaaaaaaabbbbbaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaeaaaaaaaaaaaaaaaaaaa',
      'aaaaeaaaaaaaeaaaaaaaaaaaaaaaaaaa',
      'aaaeaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaeaaaaaaadaaaaaaaaaaaaaaaaaaaa',
      'aaaadbbbbadbbbaaaaaeaaaaaaaaaaae',
      'aaadbbbbccdbbbbaaaaeaaaaaaaaaaea',
      'aaadbbcccecccbbaaaaadaadaaaaabeb',
      'bbabbcccceccccbaaaaadaadaaabbbbb',
      'beabbcccccccccaaaaaaeaaaaadbbbbb',
      'ebaabcccccccccaaaaaaeaaaadabbbbb',
      'ebaacccccccccbbdbbcccaaabdbbbbbb',
      'beaacccccccbbbbdbbbbcbbbbbbbbbbb',
      'ebeacccececbbbbbbbbbbebbbbbbbbbb',
      'eebaaaaeaeabbbbbbbbbebbbbbbbbbbb',
      'beaaaaaaaaaaabbbbbabebbbbbbbbbbb',
      'bbbbaeaaaaaaaaaaaeabbbbbbbbbbbba',
      'bbbbbeaaaaaaaaaaeaaabbbbbbbdaaab',
      'bbbbaaaaaaaaaaaaeaaaabbbbbadaaaa',
    ],
  },
  'tile.path': {
    pal: 'path', art: 2, flat: true,
    rows: [
      'gGhaGhgbhgbbbGhaGhgGhaGhgGhgahge',
      'gahaGagGhbGhgGhgahaGaaGhaGhaGhgG',
      'gGaaaaaahbbaaaaaaaaGhaahaahaaagG',
      'aaaaaaaaaaaaaaaaaaaaaaGaaaaaaagG',
      'gaaaaaaaaaaaaaaaaaaaaaaaaaaaaagG',
      'gaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaG',
      'gaaaaaaaaaaaaaaaaadddaaaaaaaahgG',
      'gaaaaaaaaaaaaaaaaaaaaaaaaaaaaagd',
      'gGhaaaaaaaaaaaaaaaaaaaaaaaaaaagG',
      'gaaaaaaaaaeaaaaaaaaaaaaaaaaaahaG',
      'gGhaaaaaaaeaaadaaaaadaaaaaaaaagG',
      'gbhgbaaaaaaaadaaaaadaaaaaaaaGaaG',
      'gbbbbbbaaaaaadaaaaadaaaaaaabbhgG',
      'gbbbbbbaaaaaaaaaaaaaaaaaaaabbhgb',
      'gGbbbbbaaaaaaaaaaaaaaaaabbbbbbgG',
      'bGbbbbbaaaaaadaaaabbbbbbeebbbbgG',
      'gGbbbbbbbaaadaacccbbbbbbddbbbbgG',
      'gGbbbbbbbbbbdacccccbbbbbbbbbbbbG',
      'aGbbbbbbbbbbbbcccccabbbbbbbbbbbG',
      'gGbbbbbbbbbbbbcccccabbbbbbbbbbgG',
      'gGbebbbbbbbbbbcccccabbbbbbbbbhaa',
      'gchebbbbbbbbbbcccccaabbbaaaaaaaG',
      'gGccccbbbbbbbbbcccaaaaaaaaaaaacG',
      'gGcccccaabbbbbbbaacccccaaaaaaagG',
      'gGccccaaaaabbbaaaacccccaaaaaahaa',
      'aGhaaaaaaaaaaaaaaacccccaaaaaGhgG',
      'gGhaaaaaaaaaaaaaaeeaaaaaaaaaaaaG',
      'gGhaaaaaaaaaaaaaaddaaaaaaaaaahaa',
      'gaaaaaaaaaaaaGaaaaaahaaaaaaaahgG',
      'aGeaGagGhgahaahaaagaaaahgaaaaagG',
      'gGeeeegGhgGhaGaaahaGhgahgahgaagG',
      'gehgGhaGhgGhgGhgGhgGhaGagGhgahgG',
    ],
  },

  // ---- 투사체 ----
  // 마력 화살 — 어느 방향으로 날아가도 같게 보이도록 둥근 핵으로 그렸다
  'bolt.0': {
    pal: 'arcane', art: 2,
    rows: [
      '...kkkvvkkk....',
      '..kvvvvvvvvk...',
      '.kvvvvOOvvvvk..',
      'kvvvOOOOOOvvvk.',
      'kvvOOOOOOqqvvk.',
      'kvvOOWWWOqqvvk.',
      'vvOOOWWWWqqqvvk',
      'vvOOOWWWqqqqvvk',
      'kvvqqqWqqqqvvk.',
      'kvvqqqqqqqqvvk.',
      'kvvvqqqqqqvvvk.',
      '.kvvvvqqvvvvk..',
      '..kvvvvvvvvk...',
      '...kkkvvkkk....',
      '......kk.......',
    ],
  },
  'bolt.1': {
    pal: 'arcane', art: 2,
    rows: [
      '...kvvvvvvk....',
      '..kvvvvvvvvk...',
      '.kvvvOOOOvvvk..',
      'kvvOOOOOOOqvvk.',
      'vvvOOOWOOOqvvvk',
      'vvOOOWWWOqqqvvk',
      'vvOOWWWWWqqqvvk',
      'vvOOOWWWWqqqvvk',
      'vvOOqqWWqqqqvvk',
      'vvvqqqqqqqqvvvk',
      'kvvqqqqqqqqvvk.',
      '.kvvvqqqqvvvk..',
      '..kvvvvvvvvk...',
      '...kvvvvvvk....',
      '....kkkkkk.....',
    ],
  },
  'shard': {
    pal: 'frost', art: 2,
    rows: [
      '.......kkWkk.......',
      '.....kkWWWWWkk.....',
      '...kkWWWWWWWWWkk...',
      '.kkWWWWWWWWCCCCCkk.',
      'kWWWWWWCCCCCCCCccck',
      'kWCCCCCCCCcccccccck',
      'kCCCCCcccccccbbbbbk',
      '.kkccccccbbbbbbbkk.',
      '...kkbbbbbbbbbkk...',
      '.....kkbbbbbkk.....',
      '.......kkbkk.......',
    ],
  },
  'rune.0': {
    pal: 'rune', art: 2,
    rows: [
      '....kkkkkk....',
      '..kkddddddkk..',
      '.kddyyyyyyddk.',
      '.kdyyyyyyyPdk.',
      'kdyyYddddPyPdk',
      'kdyydYdddyPPdk',
      'kdyyddYdydPPdk',
      'kdyydddyddPPdk',
      'kdPPddydYdPPdk',
      'kdPPPydddYPPdk',
      '.kdPyPPPPPYdk.',
      '.kddPPPPPPddk.',
      '..kkddddddkk..',
      '....kkkkkk....',
    ],
  },
  'rune.1': {
    pal: 'rune', art: 2,
    rows: [
      '....kkkkkk....',
      '..kkddddddkk..',
      '.kddyyyyyyddk.',
      '.kdyyyYYyyPdk.',
      'kdyyydYYdPPPdk',
      'kdyyddYYddPPdk',
      'kdyyyyyyyyyPdk',
      'kdyyyyyyyyyPdk',
      'kdPPddYYddPPdk',
      'kdPPPdYYdPPPdk',
      '.kdPPPYYPPPdk.',
      '.kddPPPPPPddk.',
      '..kkddddddkk..',
      '....kkkkkk....',
    ],
  },
  'flame.0': {
    pal: 'fire', art: 2,
    rows: [
      '...kfk.....',
      '..kFfdk....',
      '.kFFfddk...',
      'kFFfffddk..',
      'FFFffffddk.',
      'FFFffffdddk',
      'FFFffffdddk',
      'FFFffffdddk',
      'FFFffffdddk',
      'FFFyyyydddk',
      'kFFyyyydddk',
      'kFFFyyyddk.',
      '.kFFyyyddk.',
      '.kFFyYyddk.',
      '..kFyYyddk.',
      '..kFFYydk..',
      '...kFYfdk..',
      '....kydk...',
      '.....kfk...',
    ],
  },
  'flame.1': {
    pal: 'fire', art: 2,
    rows: [
      '.....kfk.....',
      '....kFfk.....',
      '...kFffdk....',
      '..kFFfffdk...',
      'kkFFFfffddkk.',
      'FFFFfffffdddk',
      'kFFFfffffddk.',
      'kFFFffffdddk.',
      'kFFFffffdddk.',
      'kFFFyyyydddk.',
      '.kFFyyyyddk..',
      '.kFFyyyyddk..',
      '.kFFyyyyddk..',
      '..kFFYYfdk...',
      '..kFFYYddk...',
      '..kFFYYddk...',
      '...kFyydk....',
      '....kFfk.....',
      '.....kfk.....',
    ],
  },
  'flame.2': {
    pal: 'fire', art: 2,
    rows: [
      '.....kFk....',
      '....kFFdk...',
      '...kFFffdk..',
      '..kFFFffddk.',
      '.kFFFffffddk',
      'kFFFFffffddd',
      'kFFFFffffddk',
      'kFFFFffffddk',
      'kFFFFffffddk',
      'kFFFyyyydddk',
      'kFFFyyyyddk.',
      '.kFFyyyfddk.',
      '.kFFyyyddk..',
      '.kFFyYyddk..',
      '.kFFyYydk...',
      '..kFyYddk...',
      '..kFFYdk....',
      '...kFyk.....',
      '....kfk.....',
    ],
  },
  'zap.0': {
    pal: 'zap', art: 2,
    rows: [
      '......kZWzbk....',
      '......kZWzbk....',
      '.....kZWzbk.....',
      '.....kZWzbk.....',
      '....kZkzkbk.....',
      '....kZWzbk......',
      '....kZWzbk......',
      '...kZWzbk.......',
      '...kZzzbk.......',
      '..kkzZWzbk......',
      '.kzzkkZWzbk.....',
      'kzkk..kZWzbk....',
      '.k.....kZWzbk...',
      '........kZzzbk..',
      '........kZkzk...',
      '.......kZWzbzk..',
      '......kZkzkbkzk.',
      '......kZWzbk.kzk',
      '......kZkbk...k.',
      '.....kZWzbk.....',
      '....kZkzkbk.....',
      '....kZWzbk......',
      '....kZWzbk......',
      '....kZkzkbk.....',
      '.....kZWzbk.....',
      '.....kZWzbk.....',
      '.....kZWzbk.....',
      '......kZkbk.....',
      '......kZWzbk....',
      '......kZWzbk....',
    ],
  },
  'zap.1': {
    pal: 'zap', art: 2,
    rows: [
      '....kZWzbk......',
      '.....kZWzbk.....',
      '.....kZWzbk.....',
      '......kZWzbk....',
      '......kZWzbk....',
      '.......kZWzbk...',
      '.......kZWzbk...',
      '.....k..kZWzbk..',
      '....kzkkZWzbk...',
      '..kkzk.kZWzbk...',
      '.kzzk.kZWzbk....',
      'kzkk.kZWzbk.....',
      '.k..kZWzbkk.....',
      '....kZWzbkzk....',
      '...kZWzbk.kzk...',
      '....kZkbk..kzk..',
      '....kZWzbk..kzk.',
      '....kZkzkbk..kzk',
      '.....kZWzbk...k.',
      '......kZkbk.....',
      '......kZWzbk....',
      '......kZkzkbk...',
      '.......kZWzbk...',
      '.......kZWzbk...',
      '......kZWzbk....',
      '......kZWzbk....',
      '.....kZWzbk.....',
      '.....kZWzbk.....',
      '....kZWzbk......',
      '....kZWzbk......',
    ],
  },

  // ---- 아이템 아이콘 ----
  // HUD 칸(11도트)에 맞춰 규격을 통일한다. flat이라 아랫줄을 더 두지 않는다.
  'item.bolt': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '..............kk.k.',
      '.............kWWkXk',
      '............kWWWWk.',
      '............kWWWWk.',
      '...........kkXWWVk.',
      '.........kkXXXVVk..',
      '........kXXXXVVVk..',
      '.......kVVVVXVVVk..',
      '........kkVVVVVVk..',
      '.........kvVVVVk...',
      '........kvVkVVVk...',
      '.......kvVk.kVVk...',
      '......kvVk...kVk...',
      '.....kvVk.....k....',
      '....kvVk...........',
      '.kkkvVkvk..........',
      'kvVVVVVk...........',
      '.kvVVVk............',
      '..kvVk.............',
      '...kvk.............',
    ],
  },
  'item.shard': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.........kkk.........',
      '........kWWWk........',
      '......kkWWWWWkk......',
      '.....kWWWWWWWWWk.....',
      '...kkWWWWWWWWWWCkk...',
      '.kkWWWWWWWCCCCCCCCkk.',
      'kWWWWWCCCCCCCCCCBBBBk',
      'kCCCCCCCCCCBBBBBBBBBk',
      'kCCCCCCBBBBBBBBBbbbbk',
      '.kkBBBBBBBBbbbbbbbkk.',
      '...kkBBbbbbbbbbbkk...',
      '.....kbbbbbbbbbk.....',
      '......kkbbbbbkk......',
      '........kbbbk........',
      '.........kkk.........',
    ],
  },
  'item.rune': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.....kkkyykkk......',
      '...kkyyyyyyyykk....',
      '..kyycccccccYyyk...',
      '.kyycccccccccYyyk..',
      '.kyccccccycccYYyk..',
      'kycccccccyccYYYYyk.',
      'kycccccccycYYYYYyk.',
      'kycccccycyYYYYYYyk.',
      'yyccccccyyYYYYYYyyk',
      'yyccyyyyycyyyyyYyyk',
      'kycccYYYYyyYYYYYyk.',
      'kyYYYYYYYyYyYYYYyk.',
      'kyYYYYYYYyYYyYYYyk.',
      '.kyYYYYYYyYYYYYyk..',
      '.kyyYYYYYyYYYYyyk..',
      '..kyyYYYYYYYYyyk...',
      '...kkyyyyyyyykk....',
      '.....kkkyykkk......',
      '........kk.........',
    ],
  },
  'item.aura': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '........kdk..........',
      '..k...kkkokkkk...k...',
      '.kdkkkddddddddkkkdk..',
      '.koodddoooooodddook..',
      '..kddooOOOOOOooddk...',
      '.kddoOOkkkkkkOOoddk..',
      '.kdoOOk.kkkk.kOOodk..',
      'kddoOk.kOOOOk.kOoddk.',
      'kdoOk.kOOOOook.kOodk.',
      'kdoOk.kOOOOook.kOodkk',
      'oooOk.kOOooook.kOodoo',
      'kdoOk.kooooook.kOodkk',
      'kddoOk.kooook.kOoddk.',
      '.kdoOOk.kkkk.kOOodk..',
      '.kddoOOkkkkkkOOoddk..',
      '..kddooOOOOOOooddk...',
      '.koodddoooooodddook..',
      '.kdkkkddddddddkkkdk..',
      '..k...kkkkokkk...k...',
      '.........kok.........',
      '.........kdk.........',
    ],
  },
  'item.zap': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '......kWWBBk',
      '.....kWWBBk.',
      '.....kWWBBk.',
      '....kWWBBk..',
      '....kWWBBk..',
      '...kWWBBk...',
      '...kWWBBkkk.',
      '..kWWBBBBBBk',
      '..kWWBBBBBk.',
      '.kWWBBBBBBk.',
      '..kkkkWWBk..',
      '....kWWBk...',
      '....kWWBk...',
      '...kWWBk....',
      '...kWWk.....',
      '..kWWk......',
      '..kWWk......',
      '.kWWk.......',
      '.kWk........',
      'kWWk........',
      'kWk.........',
    ],
  },
  'item.brand': {
    pal: 'item', art: 2, flat: true,
    rows: [
      'kOOOOooodddk',
      'kOOOOooodddk',
      'kOOOOooodddk',
      'kOOOOooodddk',
      'kOOOOooodddk',
      'kOOOOccodddk',
      '.kOOOccoddk.',
      '.kOOOccoddk.',
      '..kOOccddk..',
      '...kOccdkk..',
      '..knnndnnnk.',
      '..kMMMMMMMk.',
      '...knnMmkk..',
      '...knnMmk...',
      '...knnMmk...',
      '...knnMmk...',
      '...knnMmk...',
      '...knnMmk...',
      '...kMnMmk...',
      '...kMnMmk...',
      '...knnMmk...',
    ],
  },
  'item.might': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '......kkkkkk......',
      '....kkXXXXVVkk....',
      '...kXXXXXXVVVVk...',
      '..kXXXXXXXVVVvVk..',
      '.kXXWWWWXVVVvvvVk.',
      '.kXWWWWWWVVVvvvVk.',
      'kXXWWWWWWVVvvvvvVk',
      'kXXXWWWWVVvvvvvvVk',
      'kVVVVVVVVvvvvvvvVk',
      'kVVVVVVvvvvvvvvvVk',
      'kVVVVvvvvvvvXvvvVk',
      'kvvvvvvvvvvvvvvvVk',
      'kVvvvvvvvvXvvvXVVk',
      '.kvvvvvvvvvvvvvVk.',
      '.kVvvvvvvvvvXvVVk.',
      '..kVvvvvvvvvvVVk..',
      '...kVVvvvvvVVVk...',
      '....kkVVVVVVkk....',
      '......kkkkkk......',
    ],
  },
  'item.swift': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '..............kk.',
      '...........kkkaak',
      '.........kkwwawk.',
      '.......kkwwWWaak.',
      '......kwwwwWaaak.',
      '....kkwaaaWawak..',
      '...kwwwwWWWaaak..',
      '...kwwwwWWawaak..',
      '..kwwaaaWawwaak..',
      '.kwwwwWWWawaak...',
      '..kwwwWWawaaak...',
      '.kwaaaWwawaaak...',
      '.kwwWWWawaaak....',
      '.kwwWWawaaak.....',
      'kaaaWWawaak......',
      '.kwwWawaak.......',
      '.kwWawaak........',
      '.kwWaaak.........',
      '..kaaak..........',
      '..kakk...........',
      '...k.............',
    ],
  },
  'item.vigor': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.....kkkkkk.....',
      '....knnnnnnk....',
      '....kMMMMMMk....',
      '....kMMMMMMk....',
      '...kWWWWWWWWk...',
      '...kppppRRRRk...',
      '...kppppRRRRRk..',
      '..kRWWpppRRRRk..',
      '.kppWWWppRRRRRk.',
      '.kppWWWpRRRRRRk.',
      '.kppWWWRRRRRRRk.',
      'kRpppWRRRRRRRRRk',
      'kRRRRRRRRRRRRRRk',
      '.kRRRRRRRRRRRRk.',
      '.kRRRRRRRRRRRRk.',
      '.kRRRRRRRRRRRRk.',
      '..kRRRRRRRRRRk..',
      '...kRRRRRRRRk...',
      '....kkkRRkkk....',
      '.......kk.......',
    ],
  },
  'item.regen': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.....kkkkkk.....',
      '....knnnnnnk....',
      '....kMMMMMMk....',
      '....kMMMMMMk....',
      '...kWWWWWWWWk...',
      '...kjjjjGGGGk...',
      '...kjjjjGGGGGk..',
      '..kGWWjjjGGGGk..',
      '.kjjWWWjjGGGGGk.',
      '.kjjWWWjGGGGGGk.',
      '.kjjWWWGGGGGGGk.',
      'kGjjjWGGGGGGGGGk',
      'kGGGGGGGGGGGGGGk',
      '.kGGGGGGGGGGGGk.',
      '.kGGGGGGGGGGGGk.',
      '.kGGGGGGGGGGGGk.',
      '..kGGGGGGGGGGk..',
      '...kGGGGGGGGk...',
      '....kkkGGkkk....',
      '.......kk.......',
    ],
  },
  'item.focus': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.knnnnnnnnnnnnnk',
      '.kMMMMMMMMMMMMMk',
      '.kMMMMMMMMMMMMMk',
      'kWWkkkkkkkkkkkWk',
      '.kWYYYYYyyyyyWk.',
      '..kWYYYYyyyyWk..',
      '..kWWYYYyyyyWk..',
      '...kWYYYyyyWk...',
      '....kWYYyyWk....',
      '....kWWYyyWk....',
      '.....kWWcWk.....',
      '.....kWWcWk.....',
      '....kWWkckWk....',
      '....kWWkkkWk....',
      '...kWYYYyyyWk...',
      '..kWWYYYyyykWk..',
      '..kWYYYYyyyyWk..',
      '.kWWYYYYyyyykWk.',
      '.knnnnnnnnnnnnnk',
      '.kMMMMMMMMMMMMMk',
      '.kMMMMMMMMMMMMMk',
    ],
  },
  'item.area': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '......kkkkkkkk.......',
      '....kkbbbbbbbbkk.....',
      '...kbbbbCCCCbbbbk....',
      '..kbbCCCCCCCCBBbbk...',
      '.kbbWWWCCCCCCBBBbbk..',
      'kbbCWWWkkkkkkBBBbbbk.',
      'kbbCWkk......kkBbbbk.',
      'kbCCCk........kbbbbk.',
      'bbCCk..........kbbbbk',
      'bbBCk..........kbbbbk',
      'kbBBBk........kbbbbk.',
      'kbbBBkk......kkbbbbk.',
      'kbbBBBBkkkkkkbbbbbbk.',
      '.kbbbbbbbbbbbbbbbbk..',
      '..kbbbbbbbbbbbbbbk...',
      '...kbbbbbbbbbbbbk....',
      '....kkbbbbbbbbkk.....',
      '......kkkkkkkk.......',
    ],
  },
  'item.wisdom': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '..........k..........',
      '.........kXk.........',
      '........kVvvk........',
      '......kkWVvvwkk......',
      '....kkWWWVvvwwwkk....',
      '..kkWWWWWVvvwwwwwkk..',
      '.kWWaaaaaVvvaaaaawwk.',
      'kWWWWWWWWVvvwwwwwwwwk',
      'kWWWaaaaaVvvaaaaawwwk',
      'kWWWWWWWWVvvwwwwwwwwk',
      'kWWWWWWWWVvvwwwwwwwwk',
      'kaWWaaaaaVvvaaaaawwak',
      'kaaaaaWWWVvvwwwaaaaak',
      '.kkkkaaaaVvvaaaakkkk.',
      '.....kkkkVvvkkkk.....',
      '........kVvvk........',
      '.........kkk.........',
    ],
  },
};

// ---- 5×7 비트맵 글꼴(HUD 전용) ----
// 캔버스 위 숫자·라벨은 도트로 찍는다. 한글 문구는 DOM 오버레이가 맡는다.
export const FONT = {
  0: ['01110', '10001', '10011', '10101', '11001', '10001', '01110'],
  1: ['00100', '01100', '00100', '00100', '00100', '00100', '01110'],
  2: ['01110', '10001', '00001', '00010', '00100', '01000', '11111'],
  3: ['11111', '00010', '00100', '00010', '00001', '10001', '01110'],
  4: ['00010', '00110', '01010', '10010', '11111', '00010', '00010'],
  5: ['11111', '10000', '11110', '00001', '00001', '10001', '01110'],
  6: ['00110', '01000', '10000', '11110', '10001', '10001', '01110'],
  7: ['11111', '00001', '00010', '00100', '01000', '01000', '01000'],
  8: ['01110', '10001', '10001', '01110', '10001', '10001', '01110'],
  9: ['01110', '10001', '10001', '01111', '00001', '00010', '01100'],
  A: ['01110', '10001', '10001', '11111', '10001', '10001', '10001'],
  B: ['11110', '10001', '10001', '11110', '10001', '10001', '11110'],
  C: ['01110', '10001', '10000', '10000', '10000', '10001', '01110'],
  D: ['11110', '10001', '10001', '10001', '10001', '10001', '11110'],
  E: ['11111', '10000', '10000', '11110', '10000', '10000', '11111'],
  F: ['11111', '10000', '10000', '11110', '10000', '10000', '10000'],
  G: ['01110', '10001', '10000', '10111', '10001', '10001', '01111'],
  H: ['10001', '10001', '10001', '11111', '10001', '10001', '10001'],
  I: ['01110', '00100', '00100', '00100', '00100', '00100', '01110'],
  J: ['00111', '00010', '00010', '00010', '00010', '10010', '01100'],
  K: ['10001', '10010', '10100', '11000', '10100', '10010', '10001'],
  L: ['10000', '10000', '10000', '10000', '10000', '10000', '11111'],
  M: ['10001', '11011', '10101', '10101', '10001', '10001', '10001'],
  N: ['10001', '11001', '10101', '10011', '10001', '10001', '10001'],
  O: ['01110', '10001', '10001', '10001', '10001', '10001', '01110'],
  P: ['11110', '10001', '10001', '11110', '10000', '10000', '10000'],
  Q: ['01110', '10001', '10001', '10001', '10101', '10010', '01101'],
  R: ['11110', '10001', '10001', '11110', '10100', '10010', '10001'],
  S: ['01111', '10000', '10000', '01110', '00001', '00001', '11110'],
  T: ['11111', '00100', '00100', '00100', '00100', '00100', '00100'],
  U: ['10001', '10001', '10001', '10001', '10001', '10001', '01110'],
  V: ['10001', '10001', '10001', '10001', '10001', '01010', '00100'],
  W: ['10001', '10001', '10001', '10101', '10101', '11011', '10001'],
  X: ['10001', '01010', '00100', '00100', '00100', '01010', '10001'],
  Y: ['10001', '10001', '01010', '00100', '00100', '00100', '00100'],
  Z: ['11111', '00001', '00010', '00100', '01000', '10000', '11111'],
  '+': ['00000', '00100', '00100', '11111', '00100', '00100', '00000'],
  '-': ['00000', '00000', '00000', '11111', '00000', '00000', '00000'],
  ':': ['00000', '01100', '01100', '00000', '01100', '01100', '00000'],
  '/': ['00001', '00010', '00010', '00100', '01000', '01000', '10000'],
  '!': ['00100', '00100', '00100', '00100', '00100', '00000', '00100'],
  '.': ['00000', '00000', '00000', '00000', '00000', '01100', '01100'],
  ' ': ['00000', '00000', '00000', '00000', '00000', '00000', '00000'],
};

// ---- 검증 ----
// 픽셀맵은 손으로 찍는다 — 줄 길이가 하나만 어긋나도 그림이 밀린다.
// 굽기 전에 직사각형인지, 팔레트에 없는 글자가 없는지 본다.
export function validateMaps() {
  const bad = [];
  for (const [name, m] of Object.entries(MAPS)) {
    const pal = PAL[m.pal];
    if (!pal) { bad.push(`${name}: 팔레트 '${m.pal}' 없음`); continue; }
    const w = m.rows[0].length;
    m.rows.forEach((row, y) => {
      if (row.length !== w) bad.push(`${name}: ${y}번째 줄 길이 ${row.length} (기대 ${w})`);
      for (const ch of row) {
        if (ch !== '.' && !pal[ch]) bad.push(`${name}: ${y}번째 줄에 모르는 글자 '${ch}'`);
      }
    });
  }
  return bad;
}

// ---- 굽기 ----
// 모든 프레임을 선반(shelf) 방식으로 하나의 캔버스에 채운다.
// 반환: { canvas, tinted, frames } — frames[name] = { x, y, w, h }
const SHEET_W = 384;
const GAP = 1;

// 캐릭터 프레임은 한 줄 더 높게 굽는다(lift용).
// flat은 그 여유 줄을 빼는 것 — 바닥 타일(이어 붙여야 한다)과 아이콘(가운데 정렬)에 쓴다.
// art:2인 프레임은 여유 줄도 두 줄이어야 한 월드 단위만큼 뜬다.
export function frameSize(m) {
  const art = m.art || 1;
  return {
    w: m.rows[0].length,
    h: m.rows.length + (m.flat ? 0 : art),
    art,
  };
}

function paintFrame(ctx, m, ox, oy) {
  const pal = PAL[m.pal];
  const top = oy + (m.flat || m.lift ? 0 : (m.art || 1));
  for (let y = 0; y < m.rows.length; y += 1) {
    const row = m.rows[y];
    for (let x = 0; x < row.length; x += 1) {
      const ch = row[x];
      if (ch === '.') continue;
      ctx.fillStyle = pal[ch];
      ctx.fillRect(ox + x, top + y, 1, 1);
    }
  }
}

// 외곽선('k')만 다시 찍는다 — 흰 사본에서 실루엣을 살리는 데 쓴다
function paintOutline(ctx, m, ox, oy) {
  const top = oy + (m.flat || m.lift ? 0 : (m.art || 1));
  ctx.fillStyle = PAL[m.pal].k;
  for (let y = 0; y < m.rows.length; y += 1) {
    const row = m.rows[y];
    for (let x = 0; x < row.length; x += 1) {
      if (row[x] === 'k') ctx.fillRect(ox + x, top + y, 1, 1);
    }
  }
}

export function buildSheet() {
  const problems = validateMaps();
  if (problems.length) console.error('스프라이트 픽셀맵 오류:\n' + problems.join('\n'));

  const names = Object.keys(MAPS);
  // 높은 것부터 채우면 선반 낭비가 준다
  const order = [...names].sort((a, b) => frameSize(MAPS[b]).h - frameSize(MAPS[a]).h);

  const frames = {};
  let x = GAP;
  let y = GAP;
  let shelf = 0;
  for (const name of order) {
    const { w, h, art } = frameSize(MAPS[name]);
    if (x + w + GAP > SHEET_W) { x = GAP; y += shelf + GAP; shelf = 0; }
    frames[name] = { x, y, w, h, art };
    x += w + GAP;
    if (h > shelf) shelf = h;
  }
  const height = y + shelf + GAP;

  const canvas = document.createElement('canvas');
  canvas.width = SHEET_W;
  canvas.height = height;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  for (const name of order) paintFrame(ctx, MAPS[name], frames[name].x, frames[name].y);

  // 피격 순간에 쓸 흰 사본 — 같은 좌표계라 프레임 표를 그대로 쓴다.
  // 통째로 하얗게 칠하면 형태가 사라져 옛날 게임처럼 보인다. 외곽선은 검게 남긴다.
  const tinted = document.createElement('canvas');
  tinted.width = canvas.width;
  tinted.height = canvas.height;
  const tc = tinted.getContext('2d');
  tc.drawImage(canvas, 0, 0);
  tc.globalCompositeOperation = 'source-atop';
  tc.fillStyle = 'rgba(255,255,255,.86)';
  tc.fillRect(0, 0, tinted.width, tinted.height);
  tc.globalCompositeOperation = 'source-over';
  for (const name of order) paintOutline(tc, MAPS[name], frames[name].x, frames[name].y);

  return { canvas, tinted, frames };
}
