// 도트 스프라이트 — 한 글자가 한 도트다.
// 여기서 정의한 모든 그림은 시작할 때 **하나의 스프라이트시트(아틀라스)**로 구워지고,
// 이후 렌더러는 아틀라스에서 잘라 쓰기만 한다(drawImage의 9인자 형태).
//
//   '.'  투명       'k'  외곽선(어느 팔레트든 검정 한 색이다)
//   나머지 글자의 뜻은 팔레트(PAL)마다 다르다.
//
// 그림의 규칙은 셋이다.
//
//   1) **머리가 큰 2등신.** 몸을 줄이고 머리·모자를 키운다. 화면에서 실제로 보이는 크기는
//      한 뼘 남짓이라, 사람 비례로 그리면 얼굴이 뭉개져 무엇인지 알 수 없다.
//   2) **면을 몇 개로 끊은 셀 셰이딩.** 재질마다 그늘 · 기본 · 밝음 세 단만 쓰고 경계를
//      칼같이 끊는다. 계조를 부드럽게 깔면 90년대 에어브러시처럼 보인다.
//   3) **검은 외곽선 + 진한 접지 그늘(D).** 배경이 어두워도 형태가 배경에서 떨어져 나온다.
//
// 빛은 왼쪽 위 한 곳에서만 온다. 모든 그림이 같은 광원을 쓰기 때문에 아틀라스 전체가
// 한 세트처럼 보인다. 그래서 좌우 대칭은 쓰지 않는다 — 대칭인 그림은 빛의 방향을 담지 못한다.
//
// 프레임마다 lift(0/1)를 줄 수 있다 — 굽는 캔버스가 한 줄 더 높고, 1이면 한 줄 떠 있다.
// 발밑(bottom-center) 기준으로 그리므로 lift를 번갈아 주면 걷는 동안 몸이 통통 튄다.
//
// art: 한 월드 단위를 몇 도트로 찍었는지(기본 1). art:2면 같은 크기를 네 배 촘촘하게
// 그린 것이라, 화면에서는 절반 크기로 그려 결과적으로 크기는 그대로 두고 밀도만 올린다.
// 덕분에 그림을 다시 찍어도 이동 속도·판정 반지름 같은 게임 수치는 손대지 않는다.

// ---- 팔레트 ----
export const PAL = {
  commando: {
    k: '#000000', d: '#1d2a4a', m: '#2f4470', l: '#4c6aa0', D: '#121a30', r: '#8a3320', R: '#d4552e', p: '#ff9a5c', x: '#b5764a',
    s: '#e8a877', S: '#ffd2a8', a: '#2a2f3d', w: '#5b6478', W: '#9aa4b8', q: '#1f8ad4', Q: '#7fe2ff', c: '#a8791a', C: '#ffd23f',
  },
  lemurian: {
    k: '#000000', D: '#5c1a08', d: '#a83a10', m: '#e86a24', l: '#ffa55c',
    b: '#f4e4c8', e: '#160c08', q: '#ffd23f', Q: '#fff6c0',
  },
  wisp: {
    k: '#000000', D: '#101a2e', d: '#2a3c5c', m: '#4a6390', l: '#8aa4d0',
    i: '#1f6ad4', o: '#4fc4ff', O: '#c8f4ff', w: '#ffffff',
  },
  jelly: {
    k: '#000000', D: '#3a1a5c', d: '#7a2ea8', m: '#c04ce0',
    l: '#f0a8ff', q: '#3fe0ff', Q: '#d8ffff', e: '#1a0c2e',
  },
  beetle: {
    k: '#000000', D: '#2a1c10', d: '#5c3d1c', m: '#96692e', l: '#c99a55',
    e: '#160c08', q: '#ff8a1a', Q: '#ffd23f', a: '#3a2a18',
  },
  guard: {
    k: '#000000', D: '#241a12', d: '#4a3a24', m: '#7d6640', l: '#b39a68',
    i: '#2f3742', I: '#6b7789', e: '#160c08', q: '#ff8a1a', Q: '#ffd23f',
  },
  titan: {
    k: '#000000', D: '#1a2028', d: '#3b4553', m: '#63707f', l: '#98a6b4',
    g: '#2f6b4a', G: '#4fa870', q: '#2f9fe8', Q: '#c8f0ff', w: '#ffffff',
  },
  gemBlue: { k: '#000000', d: '#0f3a7a', m: '#2b8de0', l: '#8fd8ff', w: '#ffffff' },
  gemGreen: { k: '#000000', d: '#0e5c2c', m: '#2fae55', l: '#8fefaa', w: '#ffffff' },
  gemRed: { k: '#000000', d: '#7a1230', m: '#e04357', l: '#ff9eb0', w: '#ffffff' },
  heart: { k: '#000000', d: '#8e1230', m: '#e8394f', l: '#ff8a9c', w: '#ffffff' },
  magnet: { k: '#000000', d: '#3a4457', m: '#7d8ba3', l: '#dbe4f2', r: '#8e1230', R: '#e8394f', p: '#ff9eb0' },
  coin: { k: '#000000', d: '#8a5c10', m: '#f0bb2c', l: '#ffe98a', w: '#ffffff' },
  barrel: {
    k: '#000000', D: '#2e1a08', d: '#5c3a14', m: '#8f5f28', l: '#c49255',
    i: '#2f3742', I: '#7d8b9e', q: '#ff8a1a', Q: '#ffd23f',
  },
  // 상자 — 나무 · 쇠띠 · 금자물쇠
  chest: {
    k: '#000000', D: '#2e1a06', d: '#5f380f', m: '#9c6026', l: '#d99a5a',
    i: '#2f3742', I: '#7d8b9e', c: '#d9a01f', C: '#ffd23f',
  },
  rock: { k: '#000000', D: '#1b2427', d: '#3a484c', m: '#5f7276', l: '#91a4a6', g: '#2f7a33', G: '#4fb04a' },
  tuft: { k: '#000000', d: '#1f5423', m: '#357a30', l: '#5aa84a' },
  fungus: { k: '#000000', D: '#5c1220', d: '#a8203a', m: '#e8394f', l: '#ff9eb0', s: '#a89a80', S: '#e8ddc4' },
  flower: { k: '#000000', d: '#a8791a', m: '#ffd23f', l: '#fff2b8', g: '#2f7a33', G: '#4fb04a' },
  bones: { k: '#000000', d: '#5c5748', m: '#8f8a76', l: '#c2bda8' },
  stump: { k: '#000000', D: '#2a1a08', d: '#4d3010', m: '#8a5423', l: '#c19a6b', g: '#2f7a33', G: '#4fb04a' },
  grave: { k: '#000000', D: '#1a2028', d: '#3b4551', m: '#697585', l: '#a3b0bf', g: '#2f7a33', G: '#4fb04a' },
  arcane: { k: '#000000', d: '#a8791a', m: '#ffb03a', l: '#ffe07a', w: '#ffffff' },
  ember: { k: '#000000', d: '#8a2a00', m: '#ff6a1a', l: '#ffc93f', w: '#fff2b8' },
  missile: { k: '#000000', d: '#2a3040', m: '#6b7789', l: '#dbe4f2', r: '#a82a00', o: '#ff7a1a', y: '#ffd23f' },
  grenade: { k: '#000000', d: '#14400f', m: '#2f6b28', l: '#5aa84a', a: '#2a3040', w: '#8d99ad', y: '#ffd23f' },
  frost: { k: '#000000', d: '#a83a00', m: '#ff9a1a', l: '#ffe07a', w: '#ffffff' },
  fire: { k: '#000000', d: '#a82a00', m: '#ff7a1a', l: '#ffd23f', w: '#fff2b8' },
  zap: { k: '#000000', d: '#2b4fb8', m: '#5f9fff', l: '#cfe6ff', w: '#ffffff' },
  // 바닥 타일 — 다섯 단이 서로 가깝다. 벌어지면 칸 경계가 드러난다
  ground: { a: '#2b3a3c', b: '#334345', c: '#3c4e4f', d: '#222e30', e: '#48605c' },
  moss: { a: '#293a33', b: '#2f4238', c: '#374d3f', d: '#212f2a', e: '#436049' },
  path: {
    a: '#2f3a38', b: '#374340', c: '#3f4d49', d: '#26302f',
    e: '#4a5a54', g: '#2b3a3c', G: '#334345', h: '#222e30',
  },
  // 아이템 아이콘 — 공격·패시브가 같은 팔레트를 나눠 쓴다
  item: {
    k: '#000000', r: '#8e1230', R: '#e8394f', p: '#ff9eb0', g: '#146b32', G: '#33b558', j: '#7fe89b', b: '#1f4e9c', B: '#3f8ae8', C: '#a8dcff', y: '#a8791a', Y: '#ffd23f', c: '#fff2b8', d: '#a82a00',
    o: '#ff7a1a', O: '#ffd23f', a: '#2a3040', w: '#6b7789', W: '#dbe4f2', m: '#4d3010', M: '#96683a', n: '#c19a6b', v: '#4a2ba8', V: '#8a5cf0', X: '#d9c8ff', q: '#1f8ad4', Q: '#7fe2ff',
  },
};

// ---- 코만도(주인공) ----
// 서 있는 자세 하나와 걸음 둘. lift를 번갈아 주면 걷는 동안 몸이 통통 튄다.
const HERO = {
  stand: [
    '..........kkkkkkkk............',
    '........kkllllllmmkk..........',
    '.......klllllllmmmmdk.........',
    '......klllllllmmmmdddk........',
    '......klllllmmmmmddddk........',
    '......kmmmmmmmmddddddk........',
    '......kmmmmmdddddddddk........',
    '......kDDDDDDDDDDDDDDk........',
    '......kDDDDDDDDDDDDDDDk.......',
    '......ksaaaaaaaaaaaaak........',
    '......ksaQqqqaaaQqqqak........',
    '......kxaqqqqaaaqqqqak........',
    '.......kxxxxxxxxxxxxk.........',
    '........kxxxxxxxxxxk..........',
    '.......kpxxxxxxxxxxrk..kk.....',
    '......kRRRRxxxxxxrrrrkkaak....',
    '...kkkkkRRRrrrrrrrRRrkkaak....',
    '..kWWWWkmrrrrrrrrrRRrWWaak....',
    '..kwwwwkmmmmmmmmddRRrwwwwk....',
    '..kwwwwkmmmmmmmmddrrrwwwwk....',
    '.ksssxxxmmmmmddmddrrrssxxxk...',
    '..kxxxxmmmmmmddmdddddxxxxk....',
    '...kxxkmmmmmmddmddddddxxk.....',
    '....kkkmmmmmmddmddddddkk......',
    '......kmmmmmmddmddddddk.......',
    '......kmmmmmmddmddddddk.......',
    '.....kmmmmmmmddmdddddddk......',
    '.....kmmmmmmmddmdddddddk......',
    '.....kmmmmmmmddmdddddddk......',
    '.....kDDDDDDDDDDDDDDDDDk......',
    '......kkkDDDDDDDDDDDkkk.......',
    '........kDDDDDDDDDDDk.........',
  ],
  stepA: [
    '..........kkkkkkkk............',
    '........kkllllllmmkk..........',
    '.......klllllllmmmmdk.........',
    '......klllllllmmmmdddk........',
    '......klllllmmmmmddddk........',
    '......kmmmmmmmmddddddk........',
    '......kmmmmmdddddddddk........',
    '......kDDDDDDDDDDDDDDk........',
    '......kDDDDDDDDDDDDDDDk.......',
    '......ksaaaaaaaaaaaaak........',
    '......ksaQqqqaaaQqqqak........',
    '......kxaqqqqaaaqqqqak........',
    '.......kxxxxxxxxxxxxk.........',
    '........kxxxxxxxxxxk..........',
    '.......kpxxxxxxxxxxrk..kk.....',
    '......kRRRRxxxxxxrrrrkkaak....',
    '...kkkkkRRRrrrrrrrRRrkkaak....',
    '..kWWWWkkrrrrrrrrrRRrWWaak....',
    '..kwwwwkmmmmmmmmddRRrwwwwk....',
    '..kwwwwkmmmmmmmmddrrrwwwwk....',
    '.ksssxxxmmmmmddmddrrrssxxxk...',
    '..kxxxxkmmmmmddmdddddxxxxk....',
    '...kxxkkmmmmmddmddddddxxk.....',
    '....kkkmmmmmmddmdddddddk......',
    '......kmmmmmmddmdddddddk......',
    '......kmmmmmmddmdddddddk......',
    '......kmmmmmmddmdddddddk......',
    '......kmmmmmmddmmddddddk......',
    '......kmmmmmmddmmddddddk......',
    '......kDDDDDDDDDDDDDDDDDk.....',
    '......kDDDDDDkDDDDDDkkkk......',
    '......kDDDDDDkDDDDDDk.........',
  ],
  stepB: [
    '..........kkkkkkkk............',
    '........kkllllllmmkk..........',
    '.......klllllllmmmmdk.........',
    '......klllllllmmmmdddk........',
    '......klllllmmmmmddddk........',
    '......kmmmmmmmmddddddk........',
    '......kmmmmmdddddddddk........',
    '......kDDDDDDDDDDDDDDk........',
    '......kDDDDDDDDDDDDDDDk.......',
    '......ksaaaaaaaaaaaaak........',
    '......ksaQqqqaaaQqqqak........',
    '......kxaqqqqaaaqqqqak........',
    '.......kxxxxxxxxxxxxk.........',
    '........kxxxxxxxxxxk..........',
    '.......kpxxxxxxxxxxrk..kk.....',
    '......kRRRRxxxxxxrrrrkkaak....',
    '...kkkkkRRRrrrrrrrRRrkkaak....',
    '..kWWWWmmrrrrrrrrrRRrWWaak....',
    '..kwwwwmmmmmmmmdddRRrwwwwk....',
    '..kwwwwmmmmmmmmdddrrrwwwwk....',
    '.ksssxxxmmmmmdddddrrrssxxxk...',
    '..kxxxxmmmmmmddddddddxxxxk....',
    '...kxxmmmmmmmddddddddkxxk.....',
    '....kkmmmmmmmdddddddddkk......',
    '.....kmmmmmmmdddddddddk.......',
    '.....kmmmmmmmdddddddddk.......',
    '.....kmmmmmmmdddddddddk.......',
    '.....kmmmmmmmdddddddddk.......',
    '.....kmmmmmmmdddddddddk.......',
    '....kDDDDDDDDDDDDDDDDDk.......',
    '.....kkkkDDDDDkkDDDDDk........',
    '........kDDDDDkkDDDDDk........',
  ],
};

const hero = (pose, lift) => ({ pal: 'commando', art: 2, lift, rows: HERO[pose] });

// ---- 프레임 목록 ----
// name → { pal, rows, art?, lift?, flat? }
export const MAPS = {
  'commando.idle0': hero('stand', 0),
  'commando.idle1': hero('stand', 1),
  'commando.walk0': hero('stepA', 1),
  'commando.walk1': hero('stand', 0),
  'commando.walk2': hero('stepB', 1),
  'commando.walk3': hero('stand', 0),

  // ---- 몬스터 ----
  // 레무리안 — 이 판의 기본 적. 두 발로 서는 작은 도마뱀
  'lemurian.0': {
    pal: 'lemurian', art: 2, lift: 0,
    rows: [
      '............kkkkkk.......',
      '...........klllllmk......',
      '..........klllllmmmk.....',
      '.........kllllllmmmdk....',
      '........klllllmQeedddk...',
      '........kllllmmeeedddk...',
      '........kmmmmmmeeedddkkk.',
      '........kmmmmmdddddlllllk',
      '........kdmddddddddmmmmmk',
      '........kddddddddddbmbmmk',
      '.......kdmmddddddddDDDDDk',
      '.......kdmmmdddddddkkkkk.',
      '.......kmmmmmmdddddk.....',
      '.......kmmmmmmdddddk.....',
      '.......kmmmmmmdddddk.....',
      '.......kmmmmmmdddddk.....',
      'k......kmmmmmmdddddk.....',
      'Dkk....kmmmmmmdddddk.....',
      'DDDkkkkkmmmmmmdddddk.....',
      'kDDDDDDmmmmmmmddddddk....',
      '.kkDDDDDDmmmDDddddDDk....',
      '...kkkkkkmmmkkmmmmkk.....',
      '........kmmmkddddddk.....',
      '.......kdddddDDDDDDk.....',
      '.......kDDDDDkkkkkk......',
    ],
  },
  'lemurian.1': {
    pal: 'lemurian', art: 2, lift: 1,
    rows: [
      '............kkkkkk.......',
      '...........klllllmk......',
      '..........klllllmmmk.....',
      '.........kllllllmmmdk....',
      '........klllllmQeedddk...',
      '........kllllmmeeedddk...',
      '........kmmmmmmeeedddkkk.',
      '........kmmmmmdddddlllllk',
      '........kdmddddddddmmmmmk',
      '........kddddddddddbmbmmk',
      '.......kdmmddddddddDDDDDk',
      '.......kdmmmdddddddkkkkk.',
      '.......kmmmmmmdddddk.....',
      '.......kmmmmmmdddddk.....',
      '.......kmmmmmmdddddk.....',
      '.......kmmmmmmdddddk.....',
      '.......kmmmmmmdddddk.....',
      'k......kmmmmmmdddddk.....',
      'Dkk....kmmmmmmdddddk.....',
      'DDDkkkkmmmmmmmddddddk....',
      'kDDDDDDDDmmmDDddddDDk....',
      '.kkDDDDDkmmmkkmmmmkk.....',
      '...kkkkkdddddkmmmmk......',
      '.......kDDDDDddddddk.....',
      '........kkkkkDDDDDDk.....',
    ],
  },
  // 레서 위습 — 쇠 테 안에서 타는 불꽃. 떠다닌다
  'wisp.0': {
    pal: 'wisp', art: 2, lift: 1,
    rows: [
      '.....kk.......kk.....',
      '....kDDk.....kDDk....',
      '...kDDmmk.k.kmmDDk...',
      '..kDDmddkkokkddmDDk..',
      '.kDkmdkokkkkkokdmkDk.',
      '.kDmdkkkOOOOokkkdmDk.',
      'kDmmdkOOOOOOooikddmDk',
      'kDmdkkOOwwwoooikkdmDk',
      'kDmdkOOOwwwwoiiikdmDk',
      'klllkOOwwwwwiiiikdddk',
      'klllkooowwwwiiiikdddk',
      'klllkoooowwiiiiikdddk',
      'kDmdkkiiiiiiiiikkdmDk',
      'kDmddkiiiiiiiiikdmmDk',
      '.kDmdkkkiiiiikkkdmDk.',
      '.kDkmdkkkkkkkkkdmkDk.',
      '..kDDmddk...kddmDDk..',
      '...kDDmmk...kmmDDk...',
      '....kDDk.....kDDk....',
      '.....kk.......kk.....',
    ],
  },
  'wisp.1': {
    pal: 'wisp', art: 2, lift: 0,
    rows: [
      '.....kk.......kk.....',
      '....kDDk..k..kDDk....',
      '...kDDmmkkokkmmDDk...',
      '..kDDmddkkkkkddmDDk..',
      '.kDkmdkoOOOOookdmkDk.',
      '.kDmdkkOOOOOookkdmDk.',
      'kDmmdkOOOOOOooikddmDk',
      'kDmdkOOOwwwwooiikdmDk',
      'kDmdkOOwwwwwoiiikdmDk',
      'klllkOOwwwwwwiiikdddk',
      'klllkoowwwwwiiiikdddk',
      'klllkooowwwwiiiikdddk',
      'kDmdkiiiiiiiiiiikdmDk',
      'kDmddkiiiiiiiiikdmmDk',
      '.kDmdkkiiiiiiikkdmDk.',
      '.kDkmdkkiiiiikkdmkDk.',
      '..kDDmddkkkkkddmDDk..',
      '...kDDmmk...kmmDDk...',
      '....kDDk.....kDDk....',
      '.....kk.......kk.....',
    ],
  },
  // 해파리 — 둥실 떠다니다 몸을 부풀려 터진다
  'jellyfish.0': {
    pal: 'jelly', art: 2, lift: 1,
    rows: [
      '........kkkkkkk........',
      '......kklllllmmkk......',
      '....kkllllllllmmmkk....',
      '...klllllllllmmmmmdk...',
      '..kllllllllllmmmmmddk..',
      '.kllllllllllmmmmmmdddk.',
      '.kllllQeelQQqQeemddddk.',
      '.klllleeeQQQqeeemddddk.',
      'kmlllleeeQqqqeeeddddddk',
      'kmmmmmmmqqqqqqqdddddddk',
      'kmmmmmmmmqqqqqddddddddk',
      'kDmmmmmmmmqqqddddddddDk',
      '.kmmmmmmmddddddddddddk.',
      'kdddddddddddddddddddddk',
      'kDDDDDdDDDDdDdDDdDDDDDk',
      '.kkkkkDkkkkDkDkkDkkkkk.',
      '......kDkkDkDkkDk......',
      '....kkDkDkkDk..kDk.....',
      '...kqkkqk..kqk..kqkk...',
      '..kqk..kqk..kqk..kkqk..',
      '...kqk..kqk..kqk.kqk...',
      '....k....k....k...k....',
    ],
  },
  'jellyfish.1': {
    pal: 'jelly', art: 2, lift: 0,
    rows: [
      '........kkkkkkk........',
      '......kklllllmmkk......',
      '....kkllllllllmmmkk....',
      '...klllllllllmmmmmdk...',
      '..kllllllllllmmmmmddk..',
      '.klllllllllQmmmmmmdddk.',
      '.kllllQeeQQQqQeemddddk.',
      '.klllleeeQQqqeeemddddk.',
      'kmlllleeeQqqqeeeddddddk',
      'kmmmmmmmqqqqqqqdddddddk',
      'kmmmmmmmqqqqqqqdddddddk',
      'kDmmmmmmmqqqqqdddddddDk',
      '.kmmmmmmmddqdddddddddk.',
      'kdddddddddddddddddddddk',
      'kDDDDDdDdDDdDDDDdDDDDDk',
      '.kkkkkDkDkkDkkkkDkkkkk.',
      '...kDkkDk..kDk..kDkk...',
      '..kDk..kDk..kDk..kkDk..',
      '...kqk..kqk..kqk.kqk...',
      '....kqk..kqk.kqkkqk....',
      '.....kqk..kqkqkkqk.....',
      '......k....k.k..k......',
    ],
  },
  // 비틀 — 등껍질을 이고 달려든다
  'beetle.0': {
    pal: 'beetle', art: 2, lift: 0,
    rows: [
      '......kkkkkkkkkkk........',
      '....kklllllDllmmmkk......',
      '...klllllllDllmmmmdk.....',
      '..kllllllllDlmmmmmddk....',
      '.kllldlllllDmmmmmddddk...',
      'klllldllllmDmmmmmdddddkk.',
      'klllldllmmmDmmmmddllllmdk',
      'kmmmmdmmmmmDmmdddlllQeedd',
      'kmmmmdmmmmmDmddddllmeeedd',
      'kmmmmdmmmmdDdddddmmmmdddd',
      'kDmmmdmddddDddddddddddddD',
      '.kDddddddddDddddddddDDDDk',
      '..kddddddddDddddddddkkkk.',
      '..kaDDdddddDdddddDDakk...',
      '..kakkDdDDdDdDDdDkkkkak..',
      '.kak..kakkakakkak..kak...',
      '..k...kak.k.k.kak...k....',
    ],
  },
  'beetle.1': {
    pal: 'beetle', art: 2, lift: 1,
    rows: [
      '......kkkkkkkkkkk........',
      '....kklllllDllmmmkk......',
      '...klllllllDllmmmmdk.....',
      '..kllllllllDlmmmmmddk....',
      '.kllldlllllDmmmmmddddk...',
      'klllldllllmDmmmmmdddddkk.',
      'klllldllmmmDmmmmddllllmdk',
      'kmmmmdmmmmmDmmdddlllQeedd',
      'kmmmmdmmmmmDmddddllmeeedd',
      'kmmmmdmmmmdDdddddmmmmdddd',
      'kDmmmdmddddDddddddddddddD',
      '.kDddddddddDddddddddDDDDk',
      '..kDdddddddDddddddddkkkk.',
      '...kDDdddddDdddddDDak....',
      '..kakkDdDDDDDdDdDkkakk...',
      '..kak.kakkkakakak..kkak..',
      '.kak...k.kakak.k...kak...',
    ],
  },
  // 비틀 가드(엘리트) — 어깨에 갑판을 얹은 큰 벌레
  'guard.0': {
    pal: 'guard', art: 2, lift: 0,
    rows: [
      '.....kkkkkkkkkkkkkkkkkkkkkkkkkkkk.....',
      '....kIIIIIIIillllllDllmmmIIIIIIIik....',
      '...kIIIIIIIIiilllllDllmmIIIIIIIIiik...',
      '...kIIIIIIIiiilllllDllmmIIIIIIIiiik...',
      '...kIIIIIiiiiilllllDlmmmIIIIIiiiiik..k',
      '...kiiiiiiiiiilllllDmmmmiiiiiiiiiik.kI',
      '....kiiiiiiiilllllmDmmmmmiiiiiiiik.kIk',
      '.....kllllldllllmmmDmmmmmdddddddkkkIk.',
      '....klllllldllmmmmmDmmmmddddlllllmmk..',
      '....kmmlllmdmmmmmmmDmmdddddlllllmmmdk.',
      '....kmmmmmmdmmmmmmmDmdddddllllQeeedddk',
      '....kDmmmmmdmmmmmmdDddddddlllmeeeedddk',
      '.....kmmmmmdmmmmdddDddddddmmmmeeeedddk',
      '.....kDmmmmddddddddDdddddddmmdddddddDk',
      '......kDdddddddddddDdddddddddddddddDk.',
      '.kkkkk.kDddddddddddDdddddddddDdddddk..',
      'kmmmddk.kDDddddddddDdddddddDDkmmmddk..',
      'kmmmddk..kkDdddddddDdddddDDkkkmmmddk..',
      'kmmmddk....kmddddDDDddddDkk..kmmmddk..',
      'kmmmddk....kmmmddkkmmmddk....kmmmddk..',
      'kmmdddk....kmmdddkkmmdddk....kmmdddk..',
      'kmmdddk....kmmdddkkmmdddk....kmmdddk..',
      'kmmdddk....kmmdddkkmmdddk....kmmdddk..',
      'kmmdddk....kDDDDDkkmmdddk....kDDDDDk..',
      'kDDDDDk...kDDDDDDDkDDDDDk...kDDDDDDDk.',
      'DDDDDDDk..kDDDDDDDDDDDDDDk..kDDDDDDDk.',
      'DDDDDDDk...kkkkkkkDDDDDDDk...kkkkkkk..',
    ],
  },
  'guard.1': {
    pal: 'guard', art: 2, lift: 1,
    rows: [
      '.....kkkkkkkkkkkkkkkkkkkkkkkkkkkk.....',
      '....kIIIIIIIillllllDllmmmIIIIIIIik....',
      '...kIIIIIIIIiilllllDllmmIIIIIIIIiik...',
      '...kIIIIIIIiiilllllDllmmIIIIIIIiiik...',
      '...kIIIIIiiiiilllllDlmmmIIIIIiiiiik..k',
      '...kiiiiiiiiiilllllDmmmmiiiiiiiiiik.kI',
      '....kiiiiiiiilllllmDmmmmmiiiiiiiik.kIk',
      '.....kllllldllllmmmDmmmmmdddddddkkkIk.',
      '....klllllldllmmmmmDmmmmddddlllllmmk..',
      '....kmmlllmdmmmmmmmDmmdddddlllllmmmdk.',
      '....kmmmmmmdmmmmmmmDmdddddllllQeeedddk',
      '....kDmmmmmdmmmmmmdDddddddlllmeeeedddk',
      '.....kmmmmmdmmmmdddDddddddmmmmeeeedddk',
      '.....kDmmmmddddddddDdddddddmmdddddddDk',
      '......kDdddddddddddDdddddddddddddddDk.',
      '.kkkkk.kDddddddddddDdddddddddDdddddk..',
      'kmmmddk.kDDddddddddDdddddddDDkmmmddk..',
      'kmmmddk..kkDdddddddDdddddDDkkkmmmddk..',
      'kmmmddk....kmddddDDDddddDkk..kmmmddk..',
      'kmmmddk....kmmmddkkmmmddk....kmmmddk..',
      'kmmdddk....kmmdddkkmmdddk....kmmdddk..',
      'kmmdddk....kmmdddkkmmdddk....kmmdddk..',
      'kmmdddk....kmmdddkkmmdddk....kmmdddk..',
      'kDDDDDk....kmmdddkkDDDDDk....kmmdddk..',
      'DDDDDDDk...kDDDDDkDDDDDDDk...kDDDDDk..',
      'DDDDDDDk..kDDDDDDDDDDDDDDk..kDDDDDDDk.',
      'kkkkkkk...kDDDDDDDkkkkkkk...kDDDDDDDk.',
    ],
  },
  // 스톤 타이탄(보스) — 먼 곳의 횃대를 지키는 바위 거인
  'titan.0': {
    pal: 'titan', art: 2, lift: 0,
    rows: [
      '..................kGGGgggmmk..................',
      '.................kgggggglmmmk.................',
      '................klllllllmmmddk................',
      '...............klllllQQQqmmdddk...............',
      '...............kllllQwwwqqddddk...............',
      '...............klllQQwwwqqqdddk...............',
      '...............kmmmqqwwwqqqdddk...............',
      '...............kmmmqqqqqqqqdddk.kkkkkk........',
      '..........kk...kDdddqqqqqqdddDkklllllmkk......',
      '.......kkkGGkkk.kDddddddddddDklGGGGGgmmdk.....',
      '.....kkGGGGGGggkkkDddddddddDklGGGGGgggmddk....',
      '....kllGGGgggggddkkDDDDDDDDklllggggggmddddk...',
      '....klllggggggmddDDDDDDDDDDDDDllmmmmmdddddk...',
      '...klllllmmmmmddddmmmmmmmmddmmmmmmmmddddddmk..',
      '...kmlmmmmmmmdddddmmmmmmmmddmmmmmdddddddddmdk.',
      '..klmmmmmmmdddddddmmmmmmmmdddddddddddddddmmdk.',
      '.klldmmmddddddddddmmmmmmmmdddddddddddddddmmddk',
      '.klllddddddddddddmmmmmmmmmdddddddddddddlmmmddk',
      'klllllddddddddddmmmmmmmmmmddddddddddlllmmmdddk',
      'klllllmmddddddmmmmmmmmmmmddddddddddlllmmmmdddk',
      'kllllmmmdddmmmmmmmmmmmmmmddddddddddllmmmmddddk',
      'klllmmmmdddDmmmmmmmmmmmmmddddddddddmmmmmmddddk',
      'kmmmmmmddddkmmmmmmmmmmmmmddddddddddmmmmmdddddk',
      'kmmmmmdddddkmmmmmmmmmmmmmdddddddddDmmmmddddddk',
      'kmmmmddddddkmmmmmmmmmmmmmdddddddddkdmddddddddk',
      'kmmmdddddddkmmmmmmmmmmmmmdddddddddkDddddddddDk',
      'kddddddddddkmmmmmmmmmmmmmdddddddddkkdddlllmdk.',
      'kDddddddddDkmmmmmmmmmmmmmdddddddddkkdlllllmmmk',
      '.klllllmddkkDmmmmmmmmmmmmdddddddddkklllllmmmdd',
      'klllllmmmdk.kmmmmmmmmmmmmddddddddDklllllmmmmdd',
      'lllllmmmmddkkmmmmmmmmmmmmddddddddkklllmmmmmddd',
      'llllmmmmdddkkmmmmmmmmmmmmddddddddkkmmmmmmddddd',
      'lmmmmmmddddkkmmmmmmmmmmmmddddddddkkmmmmddddddd',
      'mmmmmddddddkkmmmmmmmmmmmmddddddddkkddddddddddD',
      'mmddddddddDmmmmmmmmmmmmmmdddddddddddDDddddddDk',
      'DddddddddDkmmmmmmmmmmmmmmdddddddddddkkDDDDDDk.',
      'kDDddddDDkkmmmmmmmmmmmDDDdddddddddddk.kkkkkk..',
      '.kkDDDDkk.kmmmmmmdddddkkkmmmmmmdddddk.........',
      '...kkkk...kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kDDDDDDDDDDDk.kmmmmmmdddddk.........',
      '...........kkkkkkkkkkk..kDDDDDDDDDDDk.........',
    ],
  },
  'titan.1': {
    pal: 'titan', art: 2, lift: 1,
    rows: [
      '..................kGGGgggmmk..................',
      '.................kgggggglmmmk.................',
      '................klllllllmmmddk................',
      '...............klllllQQQqmmdddk...............',
      '...............kllllQwwwqqddddk...............',
      '...............klllQQwwwqqqdddk...............',
      '...............kmmmqqwwwqqqdddk...............',
      '........kkkkkk.kmmmqqqqqqqqdddk...............',
      '......kklllllmkkDdddqqqqqqdddDk...kk..........',
      '.....kllGGGGGGmdkDddddddddddDk.kkkGGkkk.......',
      '....kllGGGGGGggddkDddddddddDkkkGGGGgggmkk.....',
      '...klllGGGggggdddDkDDDDDDDDkkllggggggmmddk....',
      '...kllllgggggddddDDDDDDDDDDDDDlllllmmmmddk....',
      '..klmmmmmmmmddddddmmmmmmmmmdlllllmmmmmddddk...',
      '.kllmmmmmdddddddddmmmmmmmmmdmlmmmmmmmdddddk...',
      '.klllddddddddddddmmmmmmmmmddmmmmmmmdddddddmk..',
      'kllllddddddddddddmmmmmmmmmdddmmmddddddddddmdk.',
      'klllllmddddddddmmmmmmmmmmmdddddddddddddddmmdk.',
      'kllllmmmdddDmmmmmmmmmmmmmmddddddddddddddmmmddk',
      'klllmmmmdddkmmmmmmmmmmmmmmddddddddddddllmmmddk',
      'kllmmmmddddkmmmmmmmmmmmmmmddddddddddlllmmmdddk',
      'kmmmmmmddddkmmmmmmmmmmmmmmddddddddddllmmmmdddk',
      'kmmmmmdddddkmmmmmmmmmmmmmmdddddddddmmmmmmddddk',
      'kmmmmddddddkDmmmmmmmmmmmmmdddddddddmmmmmdddddk',
      'kdmddddddddkkmmmmmmmmmmmmmdddddddddmmmmddddddk',
      'kDddddddddDkkmmmmmmmmmmmmmdddddddddmmmdddddddk',
      '.kdlllmdddk.kmmmmmmmmmmmmmdddddddddddddddddddk',
      'kllllllmmdk.kmmmmmmmmmmmmmdddddddddDddddddddDk',
      'llllllmmmdk.kmmmmmmmmmmmmmddddddddDkddllllmmk.',
      'lllllmmmdddkkDmmmmmmmmmmmmddddddddkkllllllmmmk',
      'lllmmmmddddk.kmmmmmmmmmmmmddddddddkllllllmmmdd',
      'mmmmmmdddddk.kmmmmmmmmmmmmddddddddklllllmmmddd',
      'mmmmdddddddk.kmmmmmmmmmmmmddddddddkllmmmmmdddd',
      'DdddddddddDkkkmmmmmmmmmmmmddddddddkmmmmmdddddd',
      'kDddddddDDkmmmmmmmmmmmmmmmdddddddddmmmdddddddd',
      '.kDDDDDDkkkmmmmmmmmmmmmmmmddddddddddDddddddddD',
      '..kkkkkk..kmmmmmmmmmmmDDDmddddddddddkDDddddDDk',
      '..........kmmmmmmdddddkkkmmmmmmdddddkkkDDDDkk.',
      '..........kmmmmmmdddddk.kmmmmmmdddddk..kkkk...',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kmmmmmmdddddk.........',
      '..........kmmmmmmdddddk.kDDDDDDDDDDDk.........',
      '..........kDDDDDDDDDDDk..kkkkkkkkkkk..........',
    ],
  },

  // ---- 주워 먹는 것 ----
  // 경험치 결정 — 같은 형태에 팔레트만 갈아 끼운다
  'gem.blue': {
    pal: 'gemBlue', art: 2,
    rows: [
      '.....klmmk....',
      '....kllmmk....',
      '...klllmmmk...',
      '..kwwllmmmmk..',
      '.klwlllmmmmmk.',
      'kllllmlmmmmmmk',
      'lllllmlmmmmmmm',
      'kmmmmmlddddddk',
      'kmmmmmlddddddk',
      '.kmmmmldddddk.',
      '..kmmmlddddk..',
      '..kmmmlddddk..',
      '...kmmldddk...',
      '....kmlddk....',
      '....kmlddk....',
      '.....kldk.....',
    ],
  },
  'gem.green': {
    pal: 'gemGreen', art: 2,
    rows: [
      '.....klmmk....',
      '....kllmmk....',
      '...klllmmmk...',
      '..kwwllmmmmk..',
      '.klwlllmmmmmk.',
      'kllllmlmmmmmmk',
      'lllllmlmmmmmmm',
      'kmmmmmlddddddk',
      'kmmmmmlddddddk',
      '.kmmmmldddddk.',
      '..kmmmlddddk..',
      '..kmmmlddddk..',
      '...kmmldddk...',
      '....kmlddk....',
      '....kmlddk....',
      '.....kldk.....',
    ],
  },
  'gem.red': {
    pal: 'gemRed', art: 2,
    rows: [
      '.....klmmk....',
      '....kllmmk....',
      '...klllmmmk...',
      '..kwwllmmmmk..',
      '.klwlllmmmmmk.',
      'kllllmlmmmmmmk',
      'lllllmlmmmmmmm',
      'kmmmmmlddddddk',
      'kmmmmmlddddddk',
      '.kmmmmldddddk.',
      '..kmmmlddddk..',
      '..kmmmlddddk..',
      '...kmmldddk...',
      '....kmlddk....',
      '....kmlddk....',
      '.....kldk.....',
    ],
  },
  'heart': {
    pal: 'heart', art: 2,
    rows: [
      '.kkllkk.kkllkk..',
      'kllllmmkllllmmk.',
      'lllllmmlllllmmdk',
      'llllwwdlllmmmddk',
      'llmmwwdlmmmmdddk',
      'lllmmmmmmmmddddd',
      'dlllmmmmmmdddddk',
      'kdllmmmmmmddddk.',
      '.kdllmmmmmdddk..',
      '..kllmmmmddddk..',
      '...kllmmmdddk...',
      '....klmmmddk....',
      '.....klmddk.....',
      '......kkdk......',
    ],
  },
  'magnet': {
    pal: 'magnet', art: 2,
    rows: [
      '...kdddddddk...',
      '..kddmmmmdddk..',
      '.kdmmmlllmmddk.',
      'kddmllkkkmmmddk',
      'kdmmlk...kmmddk',
      'kdmlk.....kmddk',
      'kdmlk.....klmdk',
      'kdmlk.....klmdk',
      'kdmlk.....klmdk',
      'kdmlk.....klmdk',
      'kdmlk.....klmdk',
      'krRpk.....kpRrk',
      'krRpk.....kpRrk',
      'krRpk.....kpRrk',
      '.kkk.......kkk.',
    ],
  },
  'coin': {
    pal: 'coin', art: 2,
    rows: [
      '..kllllmmk...',
      '.klllllmmmk..',
      'kllwllllmmdk.',
      'lllllllllmddk',
      'lllllldlmmddk',
      'mllllllmmmddk',
      'mmlldldmdmddk',
      'mmllmmmmmmddk',
      'dmdmmmdmmdddk',
      'kdddmmmmdddk.',
      '.kddddddddk..',
      '..kddddddk...',
      '...kkkkkk....',
    ],
  },

  // ---- 부술 수 있는 물건 ----
  // 상자 — 엘리트와 보스가 떨군다
  'chest': {
    pal: 'chest', art: 2,
    rows: [
      '.......kkkkkkkk.......',
      '.....kkllllllmmkk.....',
      '....killlllllmmmIk....',
      '...kIillllllmmmmIik...',
      '..klIilllllmmmmmIidk..',
      '.kllIilllmmmmmmmIiddk.',
      '.kllIilmmmmmmmmdIiddk.',
      'kmmmIimmmmCCCmddIidddk',
      'kDDDIiDDDDCccDDDIiDDDk',
      'kDDDDDDDDDCccDDDDDDDDk',
      'kmmmIimmmmCkcdddIidddd',
      'kmmmIimmmmCccdddIidddd',
      'kmmmIimmmmCccdddIidddd',
      'kDmmIimmmmCccdddIidddD',
      '.kmmIimmmmmmmdddIidddk',
      '.kmmIimmmmmmmdddIidddk',
      '.kmmIimmmmmmmdddIidddk',
      '.kDDIiDDDDDDDDDDIiDDDk',
      '..kkkkkkkkkkkkkkkkkkk.',
    ],
  },
  // 배럴 — 부수면 금화 · 회복 · 자석이 나온다
  'barrel': {
    pal: 'barrel', art: 2,
    rows: [
      '...kkkkkkkkkkk....',
      '.kklllllllmmmdkk..',
      'kllllllmmmmmddddk.',
      'kmmmdmmmdddddddddk',
      'kmmddddddddddddddk',
      'kmmmdmmmdmdddddddk',
      'kIIIIIIIIiiiiiiiik',
      'kiiiiiiiiiiiiiiiik',
      '.kmmdmmmdmddddddk.',
      '.kmmdmmmdmddddddk.',
      '.kmmdmQQQqqdddddk.',
      '.kmmdmQQQqqdddddk.',
      '.kmmdmqqqqqdddddk.',
      '.kmmdmmmdmddddddk.',
      '.kmmdmmmdmddddddk.',
      '.kmmdmmmdmddddddk.',
      '.kIIIIIIIiiiiiiik.',
      '.kiiiiiiiiiiiiiik.',
      '.kmmdmmmdmddddddk.',
      '.kmmdmmmdmddddddk.',
      '.kDDDDDDDDDDDDDDk.',
      '..kkkkkkkkkkkkkk..',
    ],
  },

  // ---- 배경 장식 ----
  'rock': {
    pal: 'rock', art: 2,
    rows: [
      '....kkkkkk.....',
      '..kkllllmmkk...',
      '.kllllllmmGdk..',
      'klllllllGGGddk.',
      'kllllllmmggddk.',
      'lllllmmmmmddddk',
      'mlmmmmmmmdddddk',
      'mmmmmmmdddddddk',
      'DmmmmmdddddddDk',
      'kDDDDDDDDDDDDk.',
    ],
  },
  'tuft': {
    pal: 'tuft', art: 2,
    rows: [
      '.......k......',
      '....k.kmk.....',
      '...klkkmk...k.',
      'k..klkkmk..kmk',
      'lk.klkkmk.kmk.',
      'lk.klkkmk.kmk.',
      'klkklkkmkkmk..',
      'kldkldkmdkmdk.',
      '.kldkldmdkmdk.',
    ],
  },
  'mushroom': {
    pal: 'fungus', art: 2,
    rows: [
      '....kkkk.....',
      '..kklllmkk...',
      '.klllllmmmk..',
      'klllllmmmmdk.',
      'lllllmmmldddk',
      'mlmlmmmmddddk',
      'mmmmmmdddlddk',
      'DDDDDDlDDDDDD',
      'kkkkSSSsskkkk',
      '...kSSSssk...',
      '...kSSSssk...',
      '...kSSSssk...',
      '..kSSSSsssk..',
    ],
  },
  'flower': {
    pal: 'flower', art: 2,
    rows: [
      '....k....',
      '..kklkk..',
      '.kllmmmk.',
      '.klmmdkk.',
      'klmmddkmk',
      '.kddddkk.',
      '.klkgkmk.',
      '..kklkk..',
      '..kkgGk..',
      '.kGkgk...',
      '..kkgk...',
      '...kgk...',
    ],
  },
  'bones': {
    pal: 'bones', art: 2,
    rows: [
      'kkkk.......kkkk.',
      'llmdk.....kllmdk',
      'mmddk.....kmmddk',
      'ddddmkk..kkddddk',
      'kkkddmmkkmmddkk.',
      '...kkddmmddkk...',
      'kkkkkmmddmmkkkk.',
      'llmdmddkkddllmdk',
      'mmdddkk..kkmmddk',
      'ddddk.....kddddk',
      'kkkk.......kkkk.',
    ],
  },
  'stump': {
    pal: 'stump', art: 2,
    rows: [
      '.....kkkkk......',
      '..kkklllllkkk...',
      '.kllllmmmllllk..',
      'kllmmmlllmmmllk.',
      'kllmmmlllmmmlldk',
      'kmllmmmmmmmllddk',
      'kDDlllllllllDDDk',
      'kDDDDDDDDDDDDDDk',
      'kGGGgmmmmddddddk',
      'kGGggmmmmddddddk',
      '.kgggmmmmdddddDk',
      '.kmmmmmmmdddddk.',
      '.kmmmmmmmdddddk.',
      '.kDDDDDDDDDDDDk.',
    ],
  },
  'grave': {
    pal: 'grave', art: 2,
    rows: [
      '....kkkkkk.....',
      '...kllllmmk....',
      '..kllllmmmdk...',
      '..klllDDmddk...',
      '.kmlmmDDddddk..',
      '.kmmDDDDDDDddk.',
      '.kmmDDDDDDDddk.',
      '.kmdDDDDDDDddk.',
      '.kmmddDDdddddk.',
      '.kmmmmDDdddddk.',
      '.kGGmmDDdddddk.',
      '.kGGgmDDdddddk.',
      '.kgggmmmdddddk.',
      'kkggmmmmdddddk.',
      'DDmmmmmmdddddDk',
      'DDDDDDDDDDDDDDk',
      'kkDDDDDDDDDDkk.',
    ],
  },

  // ---- 바닥 타일 ----
  // 잡티를 칸마다 흩뿌리면 노이즈로 보인다. 덩어리로 뭉치고 결을 넣어야 땅이 된다.
  // 가장자리는 기본색만 남겨 이웃 타일과의 이음새를 감춘다.
  'tile.grass0': {
    pal: 'ground', art: 2, flat: true,
    rows: [
      'bbaaaaabbbbbbbbbaaaaaaaaaaaebbbb',
      'bbaaaabbbbbbbbbbaaaaeaaaaaebbbbb',
      'baaaabbbbbbbbbbbdcdeaaaaaadabbbb',
      'aaaabbbbbbbbbbbdcdceaaaaadaaaaaa',
      'aaaaabbbbbbbbbadcdccaaaaddaaaaaa',
      'aaaaaabbbbbbbaacccccaaadaaaaaaaa',
      'aaaaadaaaaaaaaaccccccccdaaaaaaaa',
      'aaaaadaaaaaaaaaccccccccccaaaaaaa',
      'aaaaabbbbbaaaaaaccccccccccaaadaa',
      'aaaabbbbbbbaaaaaacccccccccaadaaa',
      'aaaaabbbbeaaaaaaacccccccccaadaaa',
      'adaaaaaaeaaaaaaaaacccccccaaadaaa',
      'adaaaaaeeaaaaaaaaaaacceaaaaadaaa',
      'aaaaaaeaaaaaaaaaaaaaaaeaaaaaaaaa',
      'aaaabaeaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaabbbbbbaaaadaaaaaaaaaaaaabaaaa',
      'aabbbbbbbbaaadaaaaaaaaaabbbbdbba',
      'aabbbbbbbaaaaaaaaaaaaaabbbbdbbbd',
      'aabbbbbaaaaaaaaaaaaaaaabbbbdbbbd',
      'aaabbbaaaaaaaaaaaeeaaaabbbbbbbbb',
      'aaaabaaaaaaaaaaaeebbdddabbbbbbba',
      'aaaaaaaaaaaaaaadeebbddddaaabaaaa',
      'aaaaaaaaaaaaabaabbbbbddaaaaaaaaa',
      'aaaaaaaaaabbbbbbbdbbbaaaaaaaaaaa',
      'aaaaaaaaebbbbbbbbdbbbaaaaaaaaaaa',
      'aaaaaaaeaabbbbbbbbbbbbbbbaaaaaaa',
      'aaeaaaaeaaaaabaaabbbbbbbbbaeaaaa',
      'aeaaaaaaaaaaaaaaaabbbbbbbbbeaaaa',
      'bdaaaaaaaaaaaaaaaaabbbbbbbaabbbb',
      'dbaaaaaaaaaaaaaaaaaabbbbbaabbebb',
      'dbaaaaaaaaaaaaaaaaaaaaaaaaabebbb',
      'bbaaaaaaaaabaaaaaaaaaaaaaaabebbb',
    ],
  },
  'tile.grass1': {
    pal: 'ground', art: 2, flat: true,
    rows: [
      'bbbbbbbdddedddddaeaaaaaaaaaacccc',
      'ccabaadddddddddddaaaaaaaaaeccccc',
      'ccaaaaadddddddddaaaeaaaaaeaccccc',
      'ccaaeaaaadddddaaaaeaaaaaaeaccecc',
      'caaaeaaaaaaaaaaaaaeeaaaaaaaacecc',
      'caaaaaaaaaaaaaaaaaeaaaaaaaabcdcc',
      'aaaaaeaaaaaaaaaaaaeaaaaaaaaedbcb',
      'baccceaaaaaaaaaaaaaaaaaaaaeddbbb',
      'cccccccaaaaaaaaaaaaaaaaaaaebbbbb',
      'cccccccaaaaaaaaaaaaaaaaadadbbbbb',
      'ccccccdcaaaaaaaaaaaaaaadaaaabbba',
      'ccccccdcaaaaaaaaaaaaaaadaaaaaaaa',
      'ccccccccaaaaaaaaaaaaaaaaaaaaaaaa',
      'cccccccaaaaaaaaaaaaaaaaaaaaaaaaa',
      'cccccccaaaaacccccabbbbbaaaaaaaaa',
      'aaeccaaaeaaccccccbbbbbbbdaaaaaaa',
      'aeaaaaaeaaccccccbbbdbbbbdaaaaaaa',
      'aeaaaaaeaaccccccbbdbbbbbbaaeaaaa',
      'aaaaaaaaaaccccccbbdbbbbbbaaeaaaa',
      'bbbbbaaaaabbbccccbbbbebbbbaaaaaa',
      'bbbbbaaaabbbbbcccabbebbbbbbaaaaa',
      'bbbbbbaaabbbbbaaaaaaeabbbbbaaaaa',
      'bbbbbbaabbbbbbbaaaaaaabbbbbaaaaa',
      'bbbbbbdaabbbbbaaaaaaaabbbbbabaad',
      'bbbbedaaabbbbbaaaaaaaabdbbbbbbbb',
      'bbbebaaaaabbbaaaaaaaaadbbbbbbbbb',
      'bbbebbbaaaaaaaaaaaaaaadabbbbbbbe',
      'bbbbbbbbaaaaaaaaaaaaaaabbbbbbbeb',
      'bbbbbbbbaaaaabbbaaaaaaaabbbbbbee',
      'bbbbbbbbaaaabbbbbaaaaaaabbbbbbbe',
      'bbbbbbbbaaaaabbbaaaaaaaaabbbbbbb',
      'bbbbbbbbaaadaaaaaaaaaaaaaaaabaca',
    ],
  },
  'tile.moss0': {
    pal: 'moss', art: 2, flat: true,
    rows: [
      'cccccccaabbbbbddadaaaaaaaaaeeaaa',
      'cccdccccaaabaadadaaaaaaaaaaeaaaa',
      'cccdcccccaaaaaaadaeaaaaaaaaaaaac',
      'ccccccccaaaaaaaaaaeaabbbbbaaaaaa',
      'cccccccaaaaaaaaaaaabbbbbbbbbaaaa',
      'aacccaaaaaaaaaabbbbbbbbbbbbbadaa',
      'aabbbaaaaaaaaabbbbbbbbbbbbebadaa',
      'abbbbbaaaaaaabbbbbbbbbbbbbebaaae',
      'abbbbbaaaaaeaabbbbbbbbbbbbbbaaae',
      'abbbbbaaaaeaaaabbbbbbebbbbaaaaaa',
      'aabbbaaaaaeaaadddbbbeadaaaaaaaaa',
      'aaaaaaaaaaaaadddddaaedaaaaaaaaaa',
      'aaaaaaaaaaaaaddddddccdaaaaaaaaaa',
      'aaaaaaaaaaaaadddddccccaaaaaaaaaa',
      'aaaaaaaaaaaaaaddddcccccaaaaaaaaa',
      'aaaaadaaaaaaaacccccccccaaaaaaaaa',
      'addddddddeaaaaccdccccccaaaaaaaaa',
      'ddddddddeddaaaacdcccccaaaaaaaaaa',
      'adddddddedaaaaaacccccaaaaaaaaaaa',
      'aaaaadaaaaaaaaaaaadddddaaaaaaadd',
      'aaaaaaaaaaaaaaaadddddddddaaaeadd',
      'aaaaaaadaaaaaaadddddddddddbebebb',
      'baaaaadaaaaaaaaadddddddddbbebebb',
      'bbbaaadaaaaaaadeaadddddabbbbbbbb',
      'bbbaaaaaaaaaadaeaaaaaaaabbbbbbdb',
      'bbbbaaaaaaaaadaaaaaaaaaabbbbbbdb',
      'bbbaaaaaaaaadaaaaaaaaaaabbebdbbb',
      'bbbaadadaaadaaaaaaaaaaabbebbdbbb',
      'badddddddbbdbbaaaaaaaaabbebbbbbb',
      'aadddddddbbbbbdaaaaaaaabbbbbaaaa',
      'aadddddddbbbbbdaaaaaaaaaaaaaaaaa',
      'aaaaadaabbbbbbbaaaaaaaaaaaaaaaaa',
    ],
  },
  'tile.moss1': {
    pal: 'moss', art: 2, flat: true,
    rows: [
      'aaaacccaaaaaaadaaaaaaaaaaaaaaaaa',
      'aaacccccaaaaadaaaaaaaaaaaaaaaaaa',
      'aacccccccaaaadaabbbbbaaaaaaaaaaa',
      'aacccccccaaaaaabbbbbbbaaaaaaaaaa',
      'aacccccccaaaaabbbbbbbbbaaaaaaada',
      'aaecccccaaaaaaabbebbbbbbaaaaaada',
      'cecacccaaaaaaaaebebbbbbbaaaaaaaa',
      'cecccaaaaeaaeaaebbbbbbbbaaaaaaac',
      'cccccaaaaeaeaaaabbbbbbbaaaaaaaac',
      'cccdcdaaaaaeabbbbbbbbbaaaaaaaaac',
      'ccdadaaaaaaaabbbbbaaaaaaaaaaaaaa',
      'aadadaaaaaaaabbbbbaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaeaaaaaaaaaaaaaaaaaaa',
      'aaaaeaaaaaaaeaaaaaaaaaaaaaaaaaaa',
      'aaaeaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaeaaaaaaadaaaaaaaaaaaaaaaaaaaa',
      'aaaadbbbbadbbbaaaaadaaaaaaaaaaae',
      'aaadbbbbccdbbbbaaaadaaaaaaaaaaea',
      'aaadbbcccecccbbaaaaadaadaaaaabeb',
      'bbabbcccceccccbaaaaadaadaaabbbbb',
      'beabbcccccccccaaaaaaeaaaaadbbbbb',
      'ebaabcccccccccaaaaaaeaaaadabbbbb',
      'ebaacccccccccbbdbbcccaaabdbbbbbb',
      'bdaacccccccbbbbdbbbbcbbbbbbbbbbb',
      'dbeacccdcecbbbbbbbbbbebbbbbbbbbb',
      'debaaaadaeabbbbbbbbbebbbbbbbbbbb',
      'beaaaaaaaaaaabbbbbabebbbbbbbbbbb',
      'bbbbaeaaaaaaaaaaaaabbbbbbbbbbbba',
      'bbbbbeaaaaaaaaaaaaaabbbbbbbaaaab',
      'bbbbaaaaaaaaaaaaaaaaabbbbbaaaaaa',
    ],
  },
  'tile.path': {
    pal: 'path', art: 2, flat: true,
    rows: [
      'gGhaGhgbhgbbbGhaGhgGhaGhgGhgahge',
      'gahaGagGhbGhgGhgahaGaaGhaGhaGhgG',
      'gGaaaaaahbbaaaaaaaaGhaahaahaaagG',
      'aaaaaaaaaaaaaaaaaaaaaaGaaaaaaagG',
      'gaaaaaaaaaaaaaaaaaaaaaaaaaaaaagG',
      'gaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaG',
      'gaaaaaaaaaaaaaaaaadddaaaaaaaahgG',
      'gaaaaaaaaaaaaaaaaaaaaaaaaaaaaagd',
      'gGhaaaaaaaaaaaaaaaaaaaaaaaaaaagG',
      'gaaaaaaaaaeaaaaaaaaaaaaaaaaaahaG',
      'gGhaaaaaaaeaaadaaaaadaaaaaaaaagG',
      'gbhgbaaaaaaaadaaaaadaaaaaaaaGaaG',
      'gbbbbbbaaaaaadaaaaadaaaaaaabbhgG',
      'gbbbbbbaaaaaaaaaaaaaaaaaaaabbhgb',
      'gGbbbbbaaaaaaaaaaaaaaaaabbbbbbgG',
      'bGbbbbbaaaaaadaaaabbbbbbeebbbbgG',
      'gGbbbbbbbaaadaacccbbbbbbddbbbbgG',
      'gGbbbbbbbbbbdacccccbbbbbbbbbbbbG',
      'aGbbbbbbbbbbbbcccccabbbbbbbbbbbG',
      'gGbbbbbbbbbbbbcccccabbbbbbbbbbgG',
      'gGbebbbbbbbbbbcccccabbbbbbbbbhaa',
      'gchebbbbbbbbbbcccccaabbbaaaaaaaG',
      'gGccccbbbbbbbbbcccaaaaaaaaaaaacG',
      'gGcccccaabbbbbbbaacccccaaaaaaagG',
      'gGccccaaaaabbbaaaacccccaaaaaahaa',
      'aGhaaaaaaaaaaaaaaacccccaaaaaGhgG',
      'gGhaaaaaaaaaaaaaaeeaaaaaaaaaaaaG',
      'gGhaaaaaaaaaaaaaaddaaaaaaaaaahaa',
      'gaaaaaaaaaaaaGaaaaaahaaaaaaaahgG',
      'aGeaGagGhgahaahaaagaaaahgaaaaagG',
      'gGeeeegGhgGhaGaaahaGhgahgahgaagG',
      'gehgGhaGhgGhgGhgGhgGhaGagGhgahgG',
    ],
  },

  // ---- 투사체 ----
  // 예광탄 — 총알은 길쭉해야 총알로 읽힌다. 나가는 방향으로 뒤집어 쓴다
  'bullet.0': {
    pal: 'arcane', art: 2,
    rows: [
      '.kkkkkkkkkkkk.',
      'kddddmmmwwlwwk',
      'kdddddddlllwwk',
      '.kkkkkkkkkkkk.',
    ],
  },
  'bullet.1': {
    pal: 'arcane', art: 2,
    rows: [
      '.kkkkkkkkkkk.',
      'kdddmmmwwlwwk',
      'kddddddlllwwk',
      '.kkkkkkkkkkk.',
    ],
  },
  'phase': {
    pal: 'frost', art: 2,
    rows: [
      '.......kkkkkkkkkkkkkk.',
      'kkkkkkkmmmmmllllllwwwk',
      'dddddmmmmlllmmmmmmwwww',
      'kkkkkkkdddddmmmmmmwwwk',
      '.......kkkkkkkkkkkkkk.',
    ],
  },
  'missile': {
    pal: 'missile', art: 2,
    rows: [
      '....kkk........',
      '...kdddkkkkkkk.',
      '.kkkkllllllrrrk',
      'kooyymmmmmmrrok',
      '.kkkkmmmmmmrrrk',
      '...kdddkkkkkkk.',
      '....kkk........',
    ],
  },
  'grenade': {
    pal: 'grenade', art: 2,
    rows: [
      '...kkkkk...',
      '..kwwwwyk..',
      '..kaaaak...',
      '.klaaaamk..',
      'kllllmmmdk.',
      'ddddddddddk',
      'mlmmmmddddk',
      'mmmmmdddddk',
      'kmmddddddk.',
      'ddddddddddk',
      'kkddddddkk.',
      '..kkddkk...',
    ],
  },
  'flame.0': {
    pal: 'fire', art: 2,
    rows: [
      '...kdk.....',
      '..kmmdk....',
      '.kmmmddk...',
      'kmmmmmddkk.',
      'mmmmmmddddk',
      'mmmmmmmdddk',
      'mmmmmmmdddk',
      'mmmmmmmdddk',
      'kmmlllldddk',
      'kmmlllldddk',
      'kmmlllldddk',
      '.kmmllldddk',
      '.kmmwwlddk.',
      '..kmlwlddk.',
      '...kmwlddk.',
      '...kmwldk..',
      '....klddk..',
      '.....kdk...',
    ],
  },
  'flame.1': {
    pal: 'fire', art: 2,
    rows: [
      '.....kdk.....',
      '....kmddk....',
      '...kmmmddk...',
      '..kmmmmdddk..',
      '.kmmmmmmdddk.',
      'kmmmmmmmddddk',
      'kmmmmmmmddddk',
      '.kmmmmmmdddk.',
      '.kmmlllldddk.',
      '.kmmlllldddk.',
      '.kmmlllldddk.',
      '..kmllllddk..',
      '..kmlwwlddk..',
      '..kmmwwdddk..',
      '...kmwwddk...',
      '...kmllddk...',
      '....kmddk....',
      '.....kdk.....',
    ],
  },
  'flame.2': {
    pal: 'fire', art: 2,
    rows: [
      '.....kdk...',
      '....kmddk..',
      '...kmmmddk.',
      '.kkmmmmdddk',
      'kmmmmmmdddd',
      'kmmmmmmdddd',
      'kmmmmmmdddd',
      'kmmmmmmdddd',
      'kmmlllldddk',
      'kmmlllldddk',
      'kmmlllldddk',
      'kmmllldddk.',
      '.kmlwwdddk.',
      '.kmlwlddk..',
      '.kmlwddk...',
      '..klwddk...',
      '..kmldk....',
      '...kdk.....',
    ],
  },
  'zap.0': {
    pal: 'zap', art: 2,
    rows: [
      '...klwmdk..',
      '...klwmdk..',
      '..klwmdk...',
      '..klwmdk...',
      '.klkmkdk...',
      '.klwmdk....',
      '.klwmdk....',
      'klwmdk.....',
      'klwmdk.....',
      '.klwmdk....',
      '..klwmdk...',
      '...klwmdk..',
      '....klwmdk.',
      '.....klwmdk',
      '.....klkdk.',
      '....klwmdk.',
      '...klkmkdk.',
      '...klwmdk..',
      '...klkdk...',
      '..klwmdk...',
      '.klkmkdk...',
      '.klwmdk....',
      '.klwmdk....',
      '..klwmdk...',
      '..klwmdk...',
      '..klwmdk...',
      '...klwmdk..',
      '...klwmdk..',
    ],
  },
  'zap.1': {
    pal: 'zap', art: 2,
    rows: [
      '.klwmdk....',
      '..klwmdk...',
      '..klwmdk...',
      '...klwmdk..',
      '...klwmdk..',
      '....klwmdk.',
      '....klwmdk.',
      '.....klwmdk',
      '....klwmdk.',
      '....klwmdk.',
      '...klwmdk..',
      '..klwmdk...',
      '.klwmdk....',
      '.klwmdk....',
      'klwmdk.....',
      '.klkdk.....',
      '.klwmdk....',
      '.klkmkdk...',
      '..klwmdk...',
      '...klkdk...',
      '...klwmdk..',
      '...klkmkdk.',
      '....klwmdk.',
      '...klwmdk..',
      '...klwmdk..',
      '..klwmdk...',
      '..klwmdk...',
      '.klwmdk....',
    ],
  },

  // ---- 적이 쏘는 것 ----
  // 적탄은 주황으로 통일했다 — 내 탄(노랑)과 색이 겹치면 피할 수가 없다
  'ember': {
    pal: 'ember', art: 2,
    rows: [
      '...kkkk..km',
      '..klllmk..k',
      '.kllllmmk..',
      'kllllmmmdk.',
      'kllwmmmddk.',
      'mmmmmmddddk',
      'kmmmmddddk.',
      'kddddddddk.',
      'kkddddddk..',
      'mkkddddk..k',
      'k..kkkk..km',
    ],
  },
  'spit': {
    pal: 'ember', art: 2,
    rows: [
      '.....kklllk...',
      '...kkllllllk..',
      '.kklllllllllk.',
      'kllllllllllllk',
      'kmmmmmmmmmmwmk',
      'kmmmmmmmmmmmmk',
      '.kkdddddddddk.',
      '...kkddddddk..',
      '.....kkdddk...',
    ],
  },

  // ---- 스킬 · 아이템 아이콘 ----
  // HUD 칸(11도트)에 맞춰 규격을 통일한다. flat이라 아랫줄을 더 두지 않는다.
  'skill.tap': {
    pal: 'item', art: 2,
    rows: [
      '.kkkkkkkkkkkkk...',
      'kWWWWWWWWWWWWWkk.',
      'kwwwwwwwwwwwwaaYk',
      'kwwwwwwwwwwwwaaak',
      'kwwwwwwwwwwwwwkk.',
      'kawwaaaaaakkkk...',
      'kawwaaaaaak......',
      'kawwaaakkk.......',
      'kawwaaak.........',
      'kawwaaak.........',
      '.kkkkkk..........',
    ],
  },
  'skill.phase': {
    pal: 'item', art: 2,
    rows: [
      '....kkkkkkk.........',
      '...kCCCCCCCkkkkkkkk.',
      'kkkkCCCCCCCCCCCCWWWk',
      'bbbbCCCCCCCCCCCCWWWW',
      'bbbbBBBBBBBBBBBBWWWW',
      'kbbbBBBBBBBBBBBBWWWk',
      '.kkkBBBBBBBBBBBBBBk.',
      '...kBBBBBBBkkkkkkk..',
      '....kkkkkkk.........',
    ],
  },
  'skill.suppress': {
    pal: 'item', art: 2,
    rows: [
      '....kkkkk..........',
      '...kwwwwwk...k.k.k.',
      '.kkkwwwwwk..kYkykyk',
      'kwwwwwwwwwkkkk.k.k.',
      'kaaaaaaaawwwwk.k.k.',
      'kaaaaaaaawwwwYkykyk',
      'kaaaaaaaawwwwk.k.k.',
      'kaaaaaaaaakkkk.k.k.',
      '.kaaaakkkk..kYkykyk',
      '.kaaaak......k.k.k.',
      '.kaaaak............',
      '.kaaaak............',
      '..kkkk.............',
    ],
  },
  'skill.frag': {
    pal: 'item', art: 2,
    rows: [
      '........kkkkk.',
      '.......kwwwwwk',
      '....kkkkwwwwwk',
      '...kwwwwwkkwwk',
      '...kaaaaakkwwk',
      '..kjaaaaaGkkk.',
      '.kjjjjjjGGgkk.',
      'kggggggggggggk',
      'kjjjjjGGGGggk.',
      'kjjjjGGGGgggk.',
      'kggggggggggggk',
      'kGGGGGGgggggk.',
      'kGGGGgggggggk.',
      'kggggggggggggk',
      'kgggggggggggk.',
      '.kgggggggggk..',
      '..kgggggggk...',
      '...kkkkkkk....',
    ],
  },
  'skill.dive': {
    pal: 'item', art: 2,
    rows: [
      '.......kk.........',
      '.....kkCCkk.......',
      '....kCCCCBBk......',
      '...kaaaaaBBBk.....',
      '..kCaCCCaBBbbk....',
      '..kCaaaaaBBbbk....',
      '.kBCBBBBBBbbbbk...',
      '.kBBBBBBbbbbbbk...',
      '..kBBBBbbbbbbk....',
      '..kbbbbbbbbbbkk.k.',
      '.kkkbbbbbbbbwkwkWk',
      'kaaaaaaaaaaakwkWk.',
      'kaaaaaaaaaaaawwwk.',
      '.kkkkkkkkkkkkkkk..',
    ],
  },
  'item.crowbar': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.............kkkk.',
      '............kRRRpk',
      '............kRRRRk',
      '............kRRRRk',
      '...........kpRrkk.',
      '..........kpRrk...',
      '.........kpRrk....',
      '........kpRrk.....',
      '.......kpRrk......',
      '......kpRrk.......',
      '.....kpRrk........',
      '....kpRrk.........',
      '.kkkpRrk..........',
      'kppRRrk...........',
      'kppRRk............',
      'kRRRRk............',
      'kRkRRk............',
      '.k.kk.............',
    ],
  },
  'item.hoof': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '....kkkkkkk...',
      '...kMMMMmmmk..',
      '..kMMMMMmmmmk.',
      '..kmmmmmmmmmk.',
      '..kMMMMMmmmmk.',
      '..kmmmmmmmmmk.',
      '..kMMMMMmmmmk.',
      '..kmmmmmmmmmk.',
      '..kMMMMMmmmmk.',
      '.kwwwwwwaaaaak',
      '.kwwwwwwaaaaak',
      '.kwwwwwwaaaaak',
      'kwwwwwkkaaaaaa',
      'kwwwwwkkaaaaaa',
      'kwwwwwkkaaaaaa',
      'kwwwwwkkaaaaaa',
      'kaaaaaaaaaaaaa',
      'kaaaaaaaaaaaak',
    ],
  },
  'item.bear': {
    pal: 'item', art: 2, flat: true,
    rows: [
      'knnMk..k..knnMk.',
      'nnnMmkknkknnnMmk',
      'nnMmnnnnnMMnMmmk',
      'MMmnnnnnnMMMmmmk',
      'mmnnnnnnMMMmmmmk',
      'knnnnnnMMMMmmmk.',
      'knnnnWkMMWkmmmk.',
      'kMMMMkkMMkkmmmk.',
      'kMMMMnnnnnmmmmk.',
      'kmMMMnnkknmmmmk.',
      '.kmmmnnkknmmmk..',
      '..kmmnnnnnmmk...',
      '...kmmmmmmmk....',
      '....kkkmkkk.....',
      '.......k........',
    ],
  },
  'item.syringe': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '...............kWk',
      '..............kWk.',
      '.............kWk..',
      '............kWk...',
      '...........kWWWk..',
      '..........kWWWWk..',
      '.........kWWwWWk..',
      '........kWWwWWk...',
      '.......kWWwWWk....',
      '......kYYYWWk.....',
      '.....kWYYYWk......',
      '..kkkWWYYYk.......',
      '.kaaaawWWk........',
      '.kaaaaWWk.........',
      'kwwwwaWk..........',
      'kwwwwak...........',
      'kwwwwk............',
      'kwwwwk............',
    ],
  },
  'item.ukulele': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '...........kmmmmk.',
      '..........knmmmmk.',
      '.........knWmmmmk.',
      '.........kMWMkkk..',
      '........knWMMkk...',
      '.......knWMMkkCk..',
      '.....k.kMWMk..k.k.',
      '..kkknknWMMk.k.kCk',
      '.knnnnnWMMk.kBk.k.',
      'knnnnnMWMmk..k..k.',
      'knnnnkMMMmk....kCk',
      'knnnkkkmmmk.....k.',
      'MMMMkkkmmmmk......',
      'kMMMMkmmmmk.......',
      'kmmmmmmmmmk.......',
      'kmmmmmmmmmk.......',
      '.kmmmmmmmk........',
      '..kkkmkkk.........',
    ],
  },
  'item.atg': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.kpppppppk..',
      '..kpppppk...',
      '...kRRRk....',
      '...kRRRk....',
      '..kkkRkkkk..',
      '.kwwwwaaaak.',
      '.kwwwwaaaak.',
      '.kwwwwaaaak.',
      '.kwwYYYYaak.',
      '.kwwYYYYaak.',
      '.kwwYYYYaak.',
      '.kwwwwaaaak.',
      '.kwwwwaaaak.',
      'kaaawwaaaaak',
      'kaaawwaaaaak',
      'kaaawwaaaaak',
      'kaaawwaaaaak',
      'kaaakkkkaaak',
    ],
  },
  'item.glasses': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.kkkkkkkk..kkkkkkkk.',
      'kaaaaaaaakkaaaaaaaak',
      'kaWWWCCCakkaWWWCCCak',
      'kaWWWCCCaaaaWWWCCCak',
      'kaCCCCCCaaaaCCCCCCak',
      'kaCCCCCCakkaCCCCCCak',
      'kaCCCCCCakkaCCCCCCak',
      'kaaaaaaaakkaaaaaaaak',
      '.kkkkkkkk..kkkkkkkk.',
    ],
  },
  'item.tooth': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.....k.......',
      '....kWk......',
      '....kWak.....',
      '...kWWwak....',
      '..kWWWwaak...',
      '..kWWwwaak...',
      '.kWWWwwwaak..',
      '.kWWWwwwaak..',
      '.kWWWwwwaak..',
      'kWWWWwwwaaak.',
      'kRRRRRRRRRRk.',
      'kppppppppppak',
      'kppppppppppk.',
    ],
  },
};

// ---- 5×7 비트맵 글꼴(HUD 전용) ----
// 캔버스 위 숫자·라벨은 도트로 찍는다. 한글 문구는 DOM 오버레이가 맡는다.
export const FONT = {
  0: ['01110', '10001', '10011', '10101', '11001', '10001', '01110'],
  1: ['00100', '01100', '00100', '00100', '00100', '00100', '01110'],
  2: ['01110', '10001', '00001', '00010', '00100', '01000', '11111'],
  3: ['11111', '00010', '00100', '00010', '00001', '10001', '01110'],
  4: ['00010', '00110', '01010', '10010', '11111', '00010', '00010'],
  5: ['11111', '10000', '11110', '00001', '00001', '10001', '01110'],
  6: ['00110', '01000', '10000', '11110', '10001', '10001', '01110'],
  7: ['11111', '00001', '00010', '00100', '01000', '01000', '01000'],
  8: ['01110', '10001', '10001', '01110', '10001', '10001', '01110'],
  9: ['01110', '10001', '10001', '01111', '00001', '00010', '01100'],
  A: ['01110', '10001', '10001', '11111', '10001', '10001', '10001'],
  B: ['11110', '10001', '10001', '11110', '10001', '10001', '11110'],
  C: ['01110', '10001', '10000', '10000', '10000', '10001', '01110'],
  D: ['11110', '10001', '10001', '10001', '10001', '10001', '11110'],
  E: ['11111', '10000', '10000', '11110', '10000', '10000', '11111'],
  F: ['11111', '10000', '10000', '11110', '10000', '10000', '10000'],
  G: ['01110', '10001', '10000', '10111', '10001', '10001', '01111'],
  H: ['10001', '10001', '10001', '11111', '10001', '10001', '10001'],
  I: ['01110', '00100', '00100', '00100', '00100', '00100', '01110'],
  J: ['00111', '00010', '00010', '00010', '00010', '10010', '01100'],
  K: ['10001', '10010', '10100', '11000', '10100', '10010', '10001'],
  L: ['10000', '10000', '10000', '10000', '10000', '10000', '11111'],
  M: ['10001', '11011', '10101', '10101', '10001', '10001', '10001'],
  N: ['10001', '11001', '10101', '10011', '10001', '10001', '10001'],
  O: ['01110', '10001', '10001', '10001', '10001', '10001', '01110'],
  P: ['11110', '10001', '10001', '11110', '10000', '10000', '10000'],
  Q: ['01110', '10001', '10001', '10001', '10101', '10010', '01101'],
  R: ['11110', '10001', '10001', '11110', '10100', '10010', '10001'],
  S: ['01111', '10000', '10000', '01110', '00001', '00001', '11110'],
  T: ['11111', '00100', '00100', '00100', '00100', '00100', '00100'],
  U: ['10001', '10001', '10001', '10001', '10001', '10001', '01110'],
  V: ['10001', '10001', '10001', '10001', '10001', '01010', '00100'],
  W: ['10001', '10001', '10001', '10101', '10101', '11011', '10001'],
  X: ['10001', '01010', '00100', '00100', '00100', '01010', '10001'],
  Y: ['10001', '10001', '01010', '00100', '00100', '00100', '00100'],
  Z: ['11111', '00001', '00010', '00100', '01000', '10000', '11111'],
  '+': ['00000', '00100', '00100', '11111', '00100', '00100', '00000'],
  '-': ['00000', '00000', '00000', '11111', '00000', '00000', '00000'],
  ':': ['00000', '01100', '01100', '00000', '01100', '01100', '00000'],
  '/': ['00001', '00010', '00010', '00100', '01000', '01000', '10000'],
  '!': ['00100', '00100', '00100', '00100', '00100', '00000', '00100'],
  '.': ['00000', '00000', '00000', '00000', '00000', '01100', '01100'],
  ' ': ['00000', '00000', '00000', '00000', '00000', '00000', '00000'],
};

// ---- 검증 ----
// 픽셀맵은 손으로 찍는다 — 줄 길이가 하나만 어긋나도 그림이 밀린다.
// 굽기 전에 직사각형인지, 팔레트에 없는 글자가 없는지 본다.
export function validateMaps() {
  const bad = [];
  for (const [name, m] of Object.entries(MAPS)) {
    const pal = PAL[m.pal];
    if (!pal) { bad.push(`${name}: 팔레트 '${m.pal}' 없음`); continue; }
    const w = m.rows[0].length;
    m.rows.forEach((row, y) => {
      if (row.length !== w) bad.push(`${name}: ${y}번째 줄 길이 ${row.length} (기대 ${w})`);
      for (const ch of row) {
        if (ch !== '.' && !pal[ch]) bad.push(`${name}: ${y}번째 줄에 모르는 글자 '${ch}'`);
      }
    });
  }
  return bad;
}

// ---- 굽기 ----
// 모든 프레임을 선반(shelf) 방식으로 하나의 캔버스에 채운다.
// 반환: { canvas, tinted, frames } — frames[name] = { x, y, w, h }
const SHEET_W = 384;
const GAP = 1;

// 캐릭터 프레임은 한 줄 더 높게 굽는다(lift용).
// flat은 그 여유 줄을 빼는 것 — 바닥 타일(이어 붙여야 한다)과 아이콘(가운데 정렬)에 쓴다.
// art:2인 프레임은 여유 줄도 두 줄이어야 한 월드 단위만큼 뜬다.
export function frameSize(m) {
  const art = m.art || 1;
  return {
    w: m.rows[0].length,
    h: m.rows.length + (m.flat ? 0 : art),
    art,
  };
}

function paintFrame(ctx, m, ox, oy) {
  const pal = PAL[m.pal];
  const top = oy + (m.flat || m.lift ? 0 : (m.art || 1));
  for (let y = 0; y < m.rows.length; y += 1) {
    const row = m.rows[y];
    for (let x = 0; x < row.length; x += 1) {
      const ch = row[x];
      if (ch === '.') continue;
      ctx.fillStyle = pal[ch];
      ctx.fillRect(ox + x, top + y, 1, 1);
    }
  }
}

// 외곽선('k')만 다시 찍는다 — 흰 사본에서 실루엣을 살리는 데 쓴다
function paintOutline(ctx, m, ox, oy) {
  const top = oy + (m.flat || m.lift ? 0 : (m.art || 1));
  ctx.fillStyle = PAL[m.pal].k;
  for (let y = 0; y < m.rows.length; y += 1) {
    const row = m.rows[y];
    for (let x = 0; x < row.length; x += 1) {
      if (row[x] === 'k') ctx.fillRect(ox + x, top + y, 1, 1);
    }
  }
}

export function buildSheet() {
  const problems = validateMaps();
  if (problems.length) console.error('스프라이트 픽셀맵 오류:\n' + problems.join('\n'));

  const names = Object.keys(MAPS);
  // 높은 것부터 채우면 선반 낭비가 준다
  const order = [...names].sort((a, b) => frameSize(MAPS[b]).h - frameSize(MAPS[a]).h);

  const frames = {};
  let x = GAP;
  let y = GAP;
  let shelf = 0;
  for (const name of order) {
    const { w, h, art } = frameSize(MAPS[name]);
    if (x + w + GAP > SHEET_W) { x = GAP; y += shelf + GAP; shelf = 0; }
    frames[name] = { x, y, w, h, art };
    x += w + GAP;
    if (h > shelf) shelf = h;
  }
  const height = y + shelf + GAP;

  const canvas = document.createElement('canvas');
  canvas.width = SHEET_W;
  canvas.height = height;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  for (const name of order) paintFrame(ctx, MAPS[name], frames[name].x, frames[name].y);

  // 피격 순간에 쓸 흰 사본 — 같은 좌표계라 프레임 표를 그대로 쓴다.
  // 통째로 하얗게 칠하면 형태가 사라져 옛날 게임처럼 보인다. 외곽선은 검게 남긴다.
  const tinted = document.createElement('canvas');
  tinted.width = canvas.width;
  tinted.height = canvas.height;
  const tc = tinted.getContext('2d');
  tc.drawImage(canvas, 0, 0);
  tc.globalCompositeOperation = 'source-atop';
  tc.fillStyle = 'rgba(255,255,255,.86)';
  tc.fillRect(0, 0, tinted.width, tinted.height);
  tc.globalCompositeOperation = 'source-over';
  for (const name of order) paintOutline(tc, MAPS[name], frames[name].x, frames[name].y);

  return { canvas, tinted, frames };
}
