// 도트 스프라이트 — 한 글자가 한 도트다.
// 여기서 정의한 모든 그림은 시작할 때 **하나의 스프라이트시트(아틀라스)**로 구워지고,
// 이후 렌더러는 아틀라스에서 잘라 쓰기만 한다(drawImage의 9인자 형태).
//
//   '.'  투명       'k'  외곽선(어느 팔레트든 검정 한 색이다)
//   나머지 글자의 뜻은 팔레트(PAL)마다 다르다.
//
// 그림의 규칙은 셋이다.
//
//   1) **머리가 큰 2등신.** 몸을 줄이고 머리·모자를 키운다. 화면에서 실제로 보이는 크기는
//      한 뼘 남짓이라, 사람 비례로 그리면 얼굴이 뭉개져 무엇인지 알 수 없다.
//   2) **면을 몇 개로 끊은 셀 셰이딩.** 재질마다 그늘 · 기본 · 밝음 세 단만 쓰고 경계를
//      칼같이 끊는다. 계조를 부드럽게 깔면 90년대 에어브러시처럼 보인다.
//   3) **검은 외곽선 + 진한 접지 그늘(D).** 배경이 어두워도 형태가 배경에서 떨어져 나온다.
//
// 빛은 왼쪽 위 한 곳에서만 온다. 모든 그림이 같은 광원을 쓰기 때문에 아틀라스 전체가
// 한 세트처럼 보인다. 그래서 좌우 대칭은 쓰지 않는다 — 대칭인 그림은 빛의 방향을 담지 못한다.
//
// 프레임마다 lift(0/1)를 줄 수 있다 — 굽는 캔버스가 한 줄 더 높고, 1이면 한 줄 떠 있다.
// 발밑(bottom-center) 기준으로 그리므로 lift를 번갈아 주면 걷는 동안 몸이 통통 튄다.
//
// art: 한 월드 단위를 몇 도트로 찍었는지(기본 1). art:2면 같은 크기를 네 배 촘촘하게
// 그린 것이라, 화면에서는 절반 크기로 그려 결과적으로 크기는 그대로 두고 밀도만 올린다.
// 덕분에 그림을 다시 찍어도 이동 속도·판정 반지름 같은 게임 수치는 손대지 않는다.

// ---- 팔레트 ----
export const PAL = {
  // 마법사 — 로브 5단 · 수염 3단 · 살갗 3단 · 지팡이 구슬
  // 마법사 — 로브/모자 3단 + 접지 그늘 D. 수염 · 살갗 · 지팡이 구슬
  wizard: {
    k: '#000000', d: '#3a1e7a', m: '#5a34c4', l: '#8a63f5', D: '#241350', c: '#d9a01f', C: '#ffd23f', x: '#c9825a', s: '#f5c69c', S: '#ffe6c8',
    a: '#b8c2d8', b: '#e8eefc', w: '#ffffff', n: '#6b4423', N: '#a97840', i: '#1a6ea8', o: '#3fc4ff', O: '#c8f4ff', e: '#1b1030',
  },
  // 슬라임 — 젤리 한 덩이. 속이 비쳐 보이도록 밝은 단을 넉넉히 뒀다
  slime: { k: '#000000', D: '#0b3d1c', d: '#158a3a', m: '#2fd45e', l: '#8bff9e', e: '#06210f', w: '#ffffff' },
  // 유령 — 차가운 흰빛 천. 아래로 갈수록 어두워진다
  ghost: {
    k: '#000000', D: '#3f4a8c', d: '#6b7ac4', m: '#a8b8ee',
    l: '#eef4ff', e: '#161038', q: '#4fe0ff', w: '#ffffff',
  },
  // 박쥐 — 날개막(w~V)과 털(n~M)을 따로 나눴다
  bat: {
    k: '#000000', D: '#2a1a52', d: '#4a2f9c', m: '#7a52e0', l: '#b79cff',
    n: '#3a2a5c', N: '#5e4a86', e: '#ff3b52', w: '#ffffff', F: '#ffffff',
  },
  // 해골 — 뼈 4단 + 눈구멍에서 타는 불
  bone: {
    k: '#000000', D: '#6b6350', d: '#a89c7c', m: '#ded3b0',
    l: '#fdf8e4', e: '#120c1e', q: '#ff7a1a', Q: '#ffd23f',
  },
  // 골렘 — 돌 6단, 이끼, 갈라진 틈의 용암
  stone: {
    k: '#000000', D: '#1e2f2a', d: '#3d5c52', m: '#628578', l: '#93b8a2',
    g: '#2f7a33', G: '#4fb04a', q: '#8f2a00', e: '#ff7a1a', E: '#ffd23f',
  },
  // 리치 — 로브 5단 + 뼈 4단 + 왕관의 금
  lich: {
    k: '#000000', D: '#20114a', d: '#3a1f8c', m: '#5c36cc', l: '#9068ff', a: '#b8b09a', b: '#e8e2cc',
    w: '#fffdf2', e: '#14092e', q: '#3fe6ff', Q: '#e8ffff', c: '#d9a01f', C: '#ffd23f',
  },
  gemBlue: { k: '#000000', d: '#0f3a7a', m: '#2b8de0', l: '#8fd8ff', w: '#ffffff' },
  gemGreen: { k: '#000000', d: '#0e5c2c', m: '#2fae55', l: '#8fefaa', w: '#ffffff' },
  gemRed: { k: '#000000', d: '#7a1230', m: '#e04357', l: '#ff9eb0', w: '#ffffff' },
  heart: { k: '#000000', d: '#8e1230', m: '#e8394f', l: '#ff8a9c', w: '#ffffff' },
  magnet: { k: '#000000', d: '#3a4457', m: '#7d8ba3', l: '#dbe4f2', r: '#8e1230', R: '#e8394f', p: '#ff9eb0' },
  coin: { k: '#000000', d: '#8a5c10', m: '#f0bb2c', l: '#ffe98a', w: '#ffffff' },
  // 항아리 — 구운 흙에 푸른 무늬
  pot: { k: '#000000', D: '#4a2410', d: '#8a4f22', m: '#c47b3c', l: '#eeae6f', b: '#2f6fe0', B: '#8fc4ff' },
  // 상자 — 나무 · 쇠띠 · 금자물쇠
  chest: {
    k: '#000000', D: '#2e1a06', d: '#5f380f', m: '#9c6026', l: '#d99a5a',
    i: '#2f3742', I: '#7d8b9e', c: '#d9a01f', C: '#ffd23f',
  },
  rock: { k: '#000000', D: '#1c2620', d: '#3c4c42', m: '#63776a', l: '#95a894', g: '#2f7a33', G: '#4fb04a' },
  tuft: { k: '#000000', d: '#1f5423', m: '#357a30', l: '#5aa84a' },
  fungus: { k: '#000000', D: '#5c1220', d: '#a8203a', m: '#e8394f', l: '#ff9eb0', s: '#a89a80', S: '#e8ddc4' },
  flower: { k: '#000000', d: '#a8791a', m: '#ffd23f', l: '#fff2b8', g: '#2f7a33', G: '#4fb04a' },
  bones: { k: '#000000', d: '#5c5748', m: '#8f8a76', l: '#c2bda8' },
  stump: { k: '#000000', D: '#2a1a08', d: '#4d3010', m: '#8a5423', l: '#c19a6b', g: '#2f7a33', G: '#4fb04a' },
  grave: { k: '#000000', D: '#1a2028', d: '#3b4551', m: '#697585', l: '#a3b0bf', g: '#2f7a33', G: '#4fb04a' },
  arcane: { k: '#000000', d: '#4a2ba8', m: '#8a5cf0', l: '#d9c8ff', w: '#ffffff' },
  frost: { k: '#000000', d: '#1c5a8c', m: '#4fb6e8', l: '#c8f0ff', w: '#ffffff' },
  rune: { k: '#000000', d: '#a8791a', m: '#ffd23f', l: '#fff2b8', w: '#ffffff' },
  fire: { k: '#000000', d: '#a82a00', m: '#ff7a1a', l: '#ffd23f', w: '#fff2b8' },
  zap: { k: '#000000', d: '#2b4fb8', m: '#5f9fff', l: '#cfe6ff', w: '#ffffff' },
  // 바닥 타일 — 다섯 단이 서로 가깝다. 벌어지면 칸 경계가 드러난다
  ground: { a: '#22331c', b: '#283c21', c: '#2f4726', d: '#1a2916', e: '#3a5a2e' },
  moss: { a: '#1f2f1a', b: '#25381e', c: '#2c4323', d: '#182514', e: '#355428' },
  path: {
    a: '#332a1e', b: '#3c3224', c: '#463a2a', d: '#281f16',
    e: '#54452f', g: '#22331c', G: '#283c21', h: '#1a2916',
  },
  // 아이템 아이콘 — 공격·패시브가 같은 팔레트를 나눠 쓴다
  item: {
    k: '#000000', r: '#8e1230', R: '#e8394f', p: '#ff9eb0', g: '#146b32', G: '#33b558', j: '#7fe89b', b: '#1f4e9c', B: '#3f8ae8', C: '#a8dcff', y: '#a8791a', Y: '#ffd23f', c: '#fff2b8',
    d: '#a82a00', o: '#ff7a1a', O: '#ffd23f', a: '#3a4457', w: '#8d99ad', W: '#e8eef8', m: '#4d3010', M: '#96683a', n: '#c19a6b', v: '#4a2ba8', V: '#8a5cf0', X: '#d9c8ff',
  },
};

// ---- 마법사 ----
// 서 있는 자세 하나와 걸음 둘. lift를 번갈아 주면 걷는 동안 몸이 통통 튄다.
const WIZ = {
  stand: [
    '......kmdk......................',
    '......kmddk.....................',
    '......kmmddk....................',
    '.....kmmmdddk........kkk........',
    '.....kmCmmdddk......kOOok.......',
    '.....kCwCmmdddk....kOOOoik......',
    '.....kmCmmmddddk..kOOoooiik.....',
    '.....kmmmmmmddddk.koooiiiik.....',
    '.....kmmmmmmdddddkkkiiiiik......',
    '.....kCCCCCCcccccccckiiik.......',
    '....klllllllmmmmmmddkkkk........',
    '...kDmmmmmmmmmmddddddknNk.......',
    '....kDDmmdddddddddDDDknNk.......',
    '.....kkDddddddddddkkkknNk.......',
    '.......kSSSSSSsssxk..knNk.......',
    '.......kSSSSSssssxk..knNk.......',
    '......kSSweSsswexxxk.knNk.......',
    '......kSSeessseexxxk.knNk.......',
    '......ksssssssxxxxxk.knNk.......',
    '......ksssssxxxxxxxk.knNk.......',
    '......kxwwwbbbbaaaak.knNk.......',
    '.......kwwwbbbbaaaak.knNk.......',
    '.......kxwwbbbbaaadk.knNk.......',
    '.......kmwwbbbaaaadkkknNk.......',
    '......kmmmwwbbaaammdddnNk.......',
    '......kmmmwwbbaaammdddnNk.......',
    '......kmmmmwbbaammmdddnNk.......',
    '......kmmmmmmmmddmmdSdnNk.......',
    '.....kmmmmmmmmmddmSSssnNk.......',
    '.....kmmmmmmmmmdddsssxxNk.......',
    '.....kmmmmmmmmmddddxxxnNk.......',
    '.....kmmmmmmmmmddddddknNk.......',
    '.....kCCCCCCCccccccccknNk.......',
    '....kDDDDDDDDDDDDDDDDDnNk.......',
    '.....kkkDDDDDkDDDDkkkkkk........',
    '........kkkkk.kkkk..............',
  ],
  stepA: [
    '......kmdk......................',
    '......kmddk.....................',
    '......kmmddk....................',
    '.....kmmmdddk........kkk........',
    '.....kmCmmdddk......kOOok.......',
    '.....kCwCmmdddk....kOOOoik......',
    '.....kmCmmmddddk..kOOoooiik.....',
    '.....kmmmmmmddddk.koooiiiik.....',
    '.....kmmmmmmdddddkkkiiiiik......',
    '.....kCCCCCCcccccccckiiik.......',
    '....klllllllmmmmmmddkkkk........',
    '...kDmmmmmmmmmmddddddknNk.......',
    '....kDDmmdddddddddDDDknNk.......',
    '.....kkDddddddddddkkkknNk.......',
    '.......kSSSSSSsssxk..knNk.......',
    '.......kSSSSSssssxk..knNk.......',
    '......kSSweSsswexxxk.knNk.......',
    '......kSSeessseexxxk.knNk.......',
    '......ksssssssxxxxxk.knNk.......',
    '......ksssssxxxxxxxk.knNk.......',
    '......kxwwwbbbbaaaak.knNk.......',
    '.......kwwwbbbbaaaak.knNk.......',
    '.......kxwwbbbbaaaddkknNk.......',
    '.......kmwwbbbaaaaddkknNk.......',
    '.......kmmwwbbaaammdddnNk.......',
    '.......kmmwwbbaaammdddnNk.......',
    '.......kmmmwbbaammmdddnNk.......',
    '......kmmmmmmmmddmmdSdnNk.......',
    '......kmmmmmmmmddmSSssnNk.......',
    '......kmmmmmmmmdddsssxxNk.......',
    '......kmmmmmmmmmdddxxxnNk.......',
    '......kmmmmmmmmmddddddnNk.......',
    '.....kCCCCCCCcccccccccnNk.......',
    '.....kDDDDDDDDDDDDDDDDnNk.......',
    '......kDDDDkkkDDDDkkkkkk........',
    '.......kkkk...kkkk..............',
  ],
  stepB: [
    '......kmdk......................',
    '......kmddk.....................',
    '......kmmddk....................',
    '.....kmmmdddk........kkk........',
    '.....kmCmmdddk......kOOok.......',
    '.....kCwCmmdddk....kOOOoik......',
    '.....kmCmmmddddk..kOOoooiik.....',
    '.....kmmmmmmddddk.koooiiiik.....',
    '.....kmmmmmmdddddkkkiiiiik......',
    '.....kCCCCCCcccccccckiiik.......',
    '....klllllllmmmmmmddkkkk........',
    '...kDmmmmmmmmmmddddddknNk.......',
    '....kDDmmdddddddddDDDknNk.......',
    '.....kkDddddddddddkkkknNk.......',
    '.......kSSSSSSsssxk..knNk.......',
    '.......kSSSSSssssxk..knNk.......',
    '......kSSweSsswexxxk.knNk.......',
    '......kSSeessseexxxk.knNk.......',
    '......ksssssssxxxxxk.knNk.......',
    '......ksssssxxxxxxxk.knNk.......',
    '......kxwwwbbbbaaaak.knNk.......',
    '.......kwwwbbbbaaaak.knNk.......',
    '......kmxwwbbbbaaak..knNk.......',
    '......kmmwwbbbaaaadkkknNk.......',
    '......kmmmwwbbaaammdddnNk.......',
    '.....kmmmmwwbbaaammdddnNk.......',
    '.....kmmmmmwbbaammmdddnNk.......',
    '.....kmmmmmmmmdddmmdSdnNk.......',
    '.....kmmmmmmmmdddmSSssnNk.......',
    '....kmmmmmmmmmddddsssxxNk.......',
    '....kmmmmmmmmmdddddxxxnNk.......',
    '....kmmmmmmmmmddddddkknNk.......',
    '....kCCCCCCCCccccccccknNk.......',
    '....kDDDDDDDDDDDDDDDDknNk.......',
    '.....kkkDDDDDkkDDDDkk.kk........',
    '........kkkkk..kkkk.............',
  ],
};

const wiz = (pose, lift) => ({ pal: 'wizard', art: 2, lift, rows: WIZ[pose] });

// ---- 프레임 목록 ----
// name → { pal, rows, art?, lift?, flat? }
export const MAPS = {
  'wizard.idle0': wiz('stand', 0),
  'wizard.idle1': wiz('stand', 1),
  'wizard.walk0': wiz('stepA', 1),
  'wizard.walk1': wiz('stand', 0),
  'wizard.walk2': wiz('stepB', 1),
  'wizard.walk3': wiz('stand', 0),

  // ---- 적 ----
  // 박쥐 — 날개를 올린 프레임과 내린 프레임
  'bat.0': {
    pal: 'bat', art: 2, lift: 1,
    rows: [
      'k..........k........k...........',
      'lkk.......klk......kmk.......kkk',
      'dllkk.....kllk.....kmmk....kkmmm',
      'Dmmllkk..klllkkkkkkmmmk..kkmmddD',
      'kDmmmllkkklllllllmmmmDkkkmmdddDk',
      '.kdmmmmllkkllllllmmmdkkmmdddddk.',
      '.kDdmmddmlllllllmmmmddmddddddDk.',
      '..kDdDDDdmlllllmmmmmddddDDDdDk..',
      '...kDkkkDlllweemmweedddDkkkDk...',
      '....k...kmmmeeemmeeedddk...k....',
      '........kmmmeeemmeeedddk........',
      '........kDmmmmmdddddddDk........',
      '.........kmmddddddddddk.........',
      '.........kDddddFdFdddDk.........',
      '..........kDddddddddDk..........',
      '...........kDDDDDDDDk...........',
      '............kkkkkkkk............',
    ],
  },
  'bat.1': {
    pal: 'bat', art: 2, lift: 0,
    rows: [
      '...........k........k...........',
      '..........klk......kmk..........',
      '..........kllk.....kmmk.........',
      '.........klllkkkkkkmmmk.........',
      '.........klllllllmmmmDk.........',
      '..........kllllllmmmdk..........',
      '.......kkkllllllmmmmddkkk.......',
      '..kkkkkllllllllmmmmmddmmmkkkkk..',
      'kklllllmmlllweemmweedddddmmmmmkk',
      'llmmmmmDdmmmeeemmeeeddddDdddddmm',
      'DmmmmmDkDmmmeeemmeeedddDkDdddddD',
      'kDdmdDk.kDmmmmmdddddddDk.kDdddDk',
      '.kDdDk...kmmddddddddddk...kDdDk.',
      '..kDk....kDddddFdFdddDk....kDk..',
      '...k......kDddddddddDk......k...',
      '...........kDDDDDDDDk...........',
      '............kkkkkkkk............',
    ],
  },
  // 슬라임 — 통통 튈 때 몸이 눌린다
  'slime.0': {
    pal: 'slime', art: 2,
    rows: [
      '........kkkkkkkkkk........',
      '.....kkklllllllmmmkkk.....',
      '....kllllllllllmmmmmdk....',
      '...kllllllllllmmmmmmmdk...',
      '..kllllllllllmmmmmmmmddk..',
      '.klllllllllmmmmmmmmmddddk.',
      '.kllllllweemmmmweemdddddk.',
      'kmlllllmeeemmmmeeedddddddk',
      'kmmmmmmmeeemmmmeeedddddddk',
      'kmmmmmmmeeemmmmeeedddddddk',
      'kDmmmmmmmmmmmdddddddddddDk',
      '.kmmmmmmmmeddddeddddddddk.',
      '.kDdmddddddeeeeddddddddDk.',
      '..kDddddddddddddddddddDk..',
      '...kDddddddddddddddddDk...',
      '....kDDDddddddddddDDDk....',
      '.....kkkDDDDDDDDDDkkk.....',
    ],
  },
  'slime.1': {
    pal: 'slime', art: 2,
    rows: [
      '.......kkkkkkkkkkkk.......',
      '....kkkllllllllmmmmkkk....',
      '...klllllllllllmmmmmmdk...',
      '..klllllllllllmmmmmmmddk..',
      '.kllllllllllmmmmmmmmmdddk.',
      'klllllllweemmmmweemmdddddk',
      'mllllllmeeemmmmeeemddddddd',
      'mmmmmmmmeeemmmmeeedddddddd',
      'mmmmmmmmeeemmmmeeedddddddd',
      'DmmmmmmmmmmmdddddddddddddD',
      'kDmmmmmmddeddddeddddddddDk',
      '.kDddddddddeeeeddddddddDk.',
      '..kDddddddddddddddddddDk..',
      '...kDDDddddddddddddDDDk...',
      '....kkkDDDDDDDDDDDDkkk....',
    ],
  },
  // 해골 — 다리가 번갈아 나간다
  'skeleton.0': {
    pal: 'bone', art: 2, lift: 0,
    rows: [
      '.....kkkllmkkk.....',
      '....kllllllmmmk....',
      '...klllllllmmmmk...',
      '..klllllllmmmmmdk..',
      '.klllllllmmmmmdddk.',
      '.kllQeeemmQeeedddk.',
      'kllleeeemmeeeeddddk',
      'kmmmeeeemmeeeeddddk',
      'kmmmeeeemmeeeeddddk',
      'kDmmmmmmmddddddddDk',
      '.kmmmmdddedddddddk.',
      '.kDdddddddddddddDk.',
      '..kDdddddddddddDk..',
      '...kDmmmmmmmmmDk...',
      '....kmememememk....',
      '....kDDDDDDDDDk....',
      '....kkkkkkkkkk.k...',
      '...kmkkkkmmkkkkmk..',
      '...kmllDDmmDDDkmk..',
      '...kmkkkkmmkkkkmk..',
      '...kmllDDmmDDDkmk..',
      '...kmkkkkmmkkkkmk..',
      '...kmkllDmmDDkkmk..',
      '...klkkkkmmkk.kDk..',
      '....kkmmmmmmmk.k...',
      '.....kddDDddDk.....',
      '.....kmmkkmmk......',
      '.....kmmkkmmk......',
      '....kkmmkkmmkk.....',
      '...kDDDDkkDDDDk....',
    ],
  },
  'skeleton.1': {
    pal: 'bone', art: 2, lift: 1,
    rows: [
      '.....kkkllmkkk.....',
      '....kllllllmmmk....',
      '...klllllllmmmmk...',
      '..klllllllmmmmmdk..',
      '.klllllllmmmmmdddk.',
      '.kllQeeemmQeeedddk.',
      'kllleeeemmeeeeddddk',
      'kmmmeeeemmeeeeddddk',
      'kmmmeeeemmeeeeddddk',
      'kDmmmmmmmddddddddDk',
      '.kmmmmdddedddddddk.',
      '.kDdddddddddddddDk.',
      '..kDdddddddddddDk..',
      '...kDmmmmmmmmmDk...',
      '....kmememememk....',
      '....kDDDDDDDDDk....',
      '....kkkkkkkkkk.k...',
      '...kmkkkkmmkkkkmk..',
      '...kmllDDmmDDDkmk..',
      '...kmkkkkmmkkkkmk..',
      '...kmllDDmmDDDkmk..',
      '...kmkkkkmmkkkkmk..',
      '...kmkllDmmDDkkmk..',
      '...klkkkkmmkk.kDk..',
      '....kkmmmmmmmk.k...',
      '.....kDddDDddk.....',
      '......kmmkkmmk.....',
      '......kmmkkmmk.....',
      '.....kkmmkkmmkk....',
      '....kDDDDkkDDDDk...',
    ],
  },
  // 유령 — 자락의 물결이 프레임마다 어긋난다
  'ghost.0': {
    pal: 'ghost', art: 2, lift: 0,
    rows: [
      '.......kkkkkkkkk........',
      '.....kkllllllmmmkk......',
      '....kllllllllmmmmmk.....',
      '...klllllllllmmmmmdk....',
      '..kllllllllllmmmmmddk...',
      '..klllllllllmmmmmmddk...',
      '.klllllllllmmmmmmmdddk..',
      '.klllllllmmmmmmmmddddk..',
      'klllllqeemmmmqeeddddddk.',
      'kmlllleeemmmmeeeddddddk.',
      'kmmmmmeeemmmmeeeddddddk.',
      'kllllleeelmmmeeedddddddk',
      'klllllllllmmmmmddddddddk',
      'klllllllllmmmmmddddddddk',
      'kDlllllllleeeemddddddddk',
      '.klllllllleeeemdddddddDk',
      '.kllllllllmmmmmdddddddk.',
      '.kllllllllmmmmmdddddddk.',
      '.kllllllllmmmmmdddddddk.',
      '.kllllllllmmmmmdddddddk.',
      '.kllllllllmmmmmddddddDk.',
      '.kDlllllllmmmmDDdddddk..',
      '..kllllkklmmmmkkDdddDk..',
      '..klllk.klmmmDk.kDdDk...',
      '...klk...kDmDk...kDk....',
      '....k.....kDk.....k.....',
    ],
  },
  'ghost.1': {
    pal: 'ghost', art: 2, lift: 1,
    rows: [
      '.......kkkkkkkkk........',
      '.....kkllllllmmmkk......',
      '....kllllllllmmmmmk.....',
      '...klllllllllmmmmmdk....',
      '..kllllllllllmmmmmddk...',
      '..klllllllllmmmmmmddk...',
      '.klllllllllmmmmmmmdddk..',
      '.klllllllmmmmmmmmddddk..',
      'klllllqeemmmmqeeddddddk.',
      'kmlllleeemmmmeeeddddddk.',
      'kmmmmmeeemmmmeeeddddddk.',
      'kllllleeelmmmeeedddddddk',
      'klllllllllmmmmmddddddddk',
      'klllllllllmmmmmddddddddk',
      'kDlllllllleeeemddddddddk',
      '.klllllllleeeemdddddddDk',
      '.kllllllllmmmmmdddddddk.',
      '.kllllllllmmmmmdddddddk.',
      '.kllllllllmmmmmdddddddk.',
      '.kllllllllmmmmmdddddddk.',
      '.kllllllllmmmmmdddDDddk.',
      '.kDkklllllmDmmmddDkkDDk.',
      '..k..kllllDkDmmddk..kk..',
      '.....kllllk.kDmdDk......',
      '......kllk...kmdk.......',
      '......kllk...kDDk.......',
    ],
  },
  // 골렘(엘리트) — 이끼 낀 바위 덩어리. 가슴의 균열에서 용암이 샌다
  'golem.0': {
    pal: 'stone', art: 2, lift: 0,
    rows: [
      '................kkkkkk................',
      '..............kkGGGgggkk..............',
      '.............klggggggmmdk.............',
      '.............kllllllmmmdk.............',
      '............klllllmmmmdddk............',
      '............klEeeqmmEeeqdk............',
      '............kmeeeqmmeeeqdkkkkkk.......',
      '.......kkkk.kmqqqqmdqqqqdklGGlmkk.....',
      '.....kkGGGGkkmmmdddddddddGGGGGgmdk....',
      '....kGGGGGgggddddddddddddGGggggmddk...',
      '...kllgggggggddDDDDDDDDDlllggmmdddk...',
      '...kllllmmmmdddDDDDDDDDDmmmmmdddddmk..',
      '..klmmmmmmdddddmmmddmddmmmmdddddddmdk.',
      '.kllmmmmdddddddmmmmmmdddddddddddddmdk.',
      '.kllddddddddddmmmmmmmddddddddddddmmddk',
      'klllldddddddddqmmmmmmddddddddddlmmmddk',
      'kllllmmdddddmmmemmmmmddddddddllmmmdddk',
      'klllmmmdddmmmmmqemmmmddddddddmmmmddddk',
      'kmmmmmddddmmmmmmemmmmddddddddmmmdddddk',
      'kmmmmdddddmmmmmmmemmmdddddddmmmddddddk',
      'kmmmddddddmmmmmmmqemmdddddddDddlllmmdk',
      'kddlllmddDmmmmmmmmqmmdddddddklllllmmdk',
      'klllllmmdkDmmmmmmmmqqdddddddkllllmmmdd',
      'lllllmmmdkkmmmmmmmmmmqddddddllllmmmddd',
      'llllmmmdddkmmmmmmmmmmdqddddDmmmmmmdddd',
      'mmmmmmddddkmmmmmmmmmmddddddkDmmmdddddd',
      'mmmmdddddDkmmmmmmmmmmddddddkkDdddddddD',
      'DddddddddkkmmmmmmmmmmddddddkkkDddddDDk',
      'kDdddddDDkmmmmmmmmmmdddddddddkkDDDDkk.',
      '.kDDDDDkkkmmmmmmmmDDDddddddddk.kkkk...',
      '..kkkkk..kmmmmmdddkkkmmmmddddk........',
      '.........kmmmmddddk.kmmmmddddk........',
      '.........kmmmmddddk.kmmmmddddk........',
      '.........kmmmmddddk.kmmmmddddk........',
      '.........kDDDDDDDDk.kmmmmddddk........',
      '..........kkkkkkkk..kDDDDDDDDk........',
    ],
  },
  'golem.1': {
    pal: 'stone', art: 2, lift: 1,
    rows: [
      '................kkkkkk................',
      '..............kkGGGgggkk..............',
      '.............klggggggmmdk.............',
      '.............kllllllmmmdk.............',
      '............klllllmmmmdddk............',
      '............klEeeqmmEeeqdk............',
      '.......kkkkkkmeeeqmmeeeqdk............',
      '.....kkllllmkmqqqqmdqqqqdk.kkkk.......',
      '....klGGGGGGgmmmdddddddddkkGGGgkk.....',
      '...klGGGGGggdddddddddddddGGggggmdk....',
      '...kllgggggddddDDDDDDDDDlllggmmmddk...',
      '..klmmmmmmdddddDDDDDDDDDlllmmmmdddk...',
      '.kllmmmmdddddddmmmddmmdmmmmmmmddddmk..',
      '.kllddddddddddmmmmmmmmdmmmmmddddddmdk.',
      'kllllddddddddmmmmmmmmmddddddddddddmdk.',
      'kllllmmddddmmmqmmmmmmmdddddddddddmmddk',
      'kllmmmmdddmmmmmemmmmmmdddddddddlmmmddk',
      'kmmmmmddddmmmmmqemmmmmdddddddllmmmdddk',
      'kmmmmdddddDmmmmmemmmmmdddddddmmmmddddk',
      'kmmmddddddkmmmmmmemmmddddddddmmmdddddk',
      'kdllllmddDkmmmmmmqemmddddddddmmddddddk',
      'klllllmmdkkmmmmmmmqmmddddddddddlllmddk',
      'lllllmmmdkkmmmmmmmmqqdddddddDdllllmmdk',
      'lllmmmmdddkmmmmmmmmmmqddddddkllllmmmdd',
      'mmmmmdddddkDmmmmmmmmmdqdddddllllmmmddd',
      'mmmmdddddDkkmmmmmmmmmdddddddmmmmmmdddd',
      'DdddddddDk.kmmmmmmmmmdddddddDmmmdddddd',
      'kDDddddDk.kkmmmmmmmmmdddddddkddddddddD',
      '.kkDDDDk.kmmmmmmmmmmmddddddddDDdddddDk',
      '...kkkk..kmmmmmmmmDDDddddddddkkDDDDDk.',
      '.........kmmmmmdddkkkmmmmddddk.kkkkk..',
      '.........kmmmmddddk.kmmmmddddk........',
      '.........kmmmmddddk.kmmmmddddk........',
      '.........kmmmmddddk.kmmmmddddk........',
      '.........kmmmmddddk.kDDDDDDDDk........',
      '.........kDDDDDDDDk..kkkkkkkk.........',
    ],
  },
  // 리치(보스) — 왕관 쓴 해골. 가슴의 마력 핵이 프레임마다 부푼다
  'lich.0': {
    pal: 'lich', art: 2, lift: 0,
    rows: [
      '.................k.................',
      '................kck................',
      '..........k...k.kCk..k..k..........',
      '.........kck.kckkCkkkckkck.........',
      '.........kCkklCllCllmCkkCk.........',
      '........kCCCCCCCCCCccccccck........',
      '........kccccccccccccccccck........',
      '........kllllllewwbemmmmddk........',
      '.......klllllewwwwwbbemmdddk.......',
      '.......kllllwwwwwwwbbbamdddk.......',
      '......kllllewwwwwwbbbbaeddddk......',
      '......klllewwwwwwbbbbbaaedddk......',
      '......klllewQeeebbbQeeeaedddk......',
      '......kllewweeeebbbeeeeaaeddk......',
      '......kmlebbeeeebbbeeeeaaeddk......',
      '......kmmebbeeeebbaeeeeaaeddk......',
      '......kmmebbbbbbbaaaaaaaaeddk......',
      '......kmmeebbbbaaaaaaaaaeeddk......',
      '......kmmeeaaaaaaaaaaaaaeeddk......',
      '......kDddeeaaaaaaaaaaaeeddDk......',
      '....kkkkddeeaaaaaaaaaaaeeddkkkk....',
      '..kklllldddeebbbbbbbbbeedddlllmkk..',
      '.kllllllmdddebebebebebedddlllmmmdk.',
      'kllllllmmmdddbbbbbbbbbdddlllmmmdddk',
      'klllmmmmmddddddeeeeeddddlmmmmmddddk',
      'kmmmmmmddddddddqqqqqddmmmmmmddddddk',
      'kDmdllmdddddmmqqQQQqqddmddddllmddDk',
      '.kdlllmmddddmmqQQQQQqddddddlllmmdk.',
      '.kllllmmddmmmqqQQQQQqqddddllllmmdk.',
      '.klllmmddmmmmqqQQQQQqqddddlllmmddk.',
      '.kllmmdddmmmmmqQQQQQqdddddllmmdddk.',
      '.kmmmmdddmmmmmqqQQQqqdddddmmmmdddk.',
      '.kmmdddddmmmmmmqqqqqddddddmmdddddk.',
      '.kDdwwbddmmmmmmmmmmmmdddddddwwwdDk.',
      '..kwwbaammmmmmmmmmmmmddddddwwwbak..',
      '..kbbaaammmmmmmmmmmmmddddddbbbaak..',
      '..kaaaammmmmmmmmmmmmmdddddddaaaak..',
      '...kaakmmmmmmDmmmmmmmDddddddkaakdk.',
      '....kkkDmmmmDkDmmmmmDkDddddDkkkkDk.',
      '.......kmmmDk.kDmmmDk.kDdddk....k..',
      '.......kDmDk...kmmmk...kDdDk.......',
      '........kDk....kDmDk....kDk........',
      '.........k......kDk......k.........',
      '.................k.................',
    ],
  },
  'lich.1': {
    pal: 'lich', art: 2, lift: 1,
    rows: [
      '.................k.................',
      '................kck................',
      '..........k...k.kCk..k..k..........',
      '.........kck.kckkCkkkckkck.........',
      '.........kCkklCllCllmCkkCk.........',
      '........kCCCCCCCCCCccccccck........',
      '........kccccccccccccccccck........',
      '........kllllllewwbemmmmddk........',
      '.......klllllewwwwwbbemmdddk.......',
      '.......kllllwwwwwwwbbbamdddk.......',
      '......kllllewwwwwwbbbbaeddddk......',
      '......klllewwwwwwbbbbbaaedddk......',
      '......klllewQeeebbbQeeeaedddk......',
      '......kllewweeeebbbeeeeaaeddk......',
      '......kmlebbeeeebbbeeeeaaeddk......',
      '......kmmebbeeeebbaeeeeaaeddk......',
      '......kmmebbbbbbbaaaaaaaaeddk......',
      '......kmmeebbbbaaaaaaaaaeeddk......',
      '......kmmeeaaaaaaaaaaaaaeeddk......',
      '......kDddeeaaaaaaaaaaaeeddDk......',
      '....kkkkddeeaaaaaaaaaaaeeddkkkk....',
      '..kklllldddeebbbbbbbbbeedddlllmkk..',
      '.kllllllmdddebebebebebedddlllmmmdk.',
      'kllllllmmmdddbbbbbbbbbdddlllmmmdddk',
      'klllmmmmmddddddqqqqqddddlmmmmmddddk',
      'kmmmmmmdddddddqqQQQqqdmmmmmmddddddk',
      'kDmdllmdddddmqqQQQQQqqdmddddllmddDk',
      '.kdlllmmddddmqQQQQQQQqdddddlllmmdk.',
      '.kllllmmddmmmqQQQQQQQqddddllllmmdk.',
      '.klllmmddmmmmqQQQQQQQqddddlllmmddk.',
      '.kllmmdddmmmmqQQQQQQQqddddllmmdddk.',
      '.kmmmmdddmmmmqqQQQQQqqddddmmmmdddk.',
      '.kmmdddddmmmmmqqQQQqqdddddmmdddddk.',
      '.kDdwwbddmmmmmmqqqqqmdddddddwwwdDk.',
      '..kwwbaammmmmmmmmmmmmddddddwwwbak..',
      '..kbbaaammmmmmmmmmmmmddddddbbbaak..',
      '..kaaaammDmmmmmmmmmmmddddDddaaaak..',
      '...kaammDkDmmmmmmDmmmdddDkDddaak...',
      '...kDmmDk.kmmmmmDkDmmdddk.kDddDk...',
      '....kDDk..kDmmmDk.kDmddDk..kDDk....',
      '.....kk....kmmmk...kmddk....kk.....',
      '...........kDDDk...kDDDk...........',
      '............kkk.....kkk............',
    ],
  },

  // ---- 주워 먹는 것 ----
  // 경험치 보석 — 같은 형태에 팔레트만 갈아 끼운다
  'gem.blue': {
    pal: 'gemBlue', art: 2,
    rows: [
      '.....klmmk....',
      '....kllmmk....',
      '...klllmmmk...',
      '..kwwllmmmmk..',
      '.klwlllmmmmmk.',
      'kllllmlmmmmmmk',
      'lllllmlmmmmmmm',
      'kmmmmmlddddddk',
      'kmmmmmlddddddk',
      '.kmmmmldddddk.',
      '..kmmmlddddk..',
      '..kmmmlddddk..',
      '...kmmldddk...',
      '....kmlddk....',
      '....kmlddk....',
      '.....kldk.....',
    ],
  },
  'gem.green': {
    pal: 'gemGreen', art: 2,
    rows: [
      '.....klmmk....',
      '....kllmmk....',
      '...klllmmmk...',
      '..kwwllmmmmk..',
      '.klwlllmmmmmk.',
      'kllllmlmmmmmmk',
      'lllllmlmmmmmmm',
      'kmmmmmlddddddk',
      'kmmmmmlddddddk',
      '.kmmmmldddddk.',
      '..kmmmlddddk..',
      '..kmmmlddddk..',
      '...kmmldddk...',
      '....kmlddk....',
      '....kmlddk....',
      '.....kldk.....',
    ],
  },
  'gem.red': {
    pal: 'gemRed', art: 2,
    rows: [
      '.....klmmk....',
      '....kllmmk....',
      '...klllmmmk...',
      '..kwwllmmmmk..',
      '.klwlllmmmmmk.',
      'kllllmlmmmmmmk',
      'lllllmlmmmmmmm',
      'kmmmmmlddddddk',
      'kmmmmmlddddddk',
      '.kmmmmldddddk.',
      '..kmmmlddddk..',
      '..kmmmlddddk..',
      '...kmmldddk...',
      '....kmlddk....',
      '....kmlddk....',
      '.....kldk.....',
    ],
  },
  'heart': {
    pal: 'heart', art: 2,
    rows: [
      '.kkllkk.kkllkk..',
      'kllllmmkllllmmk.',
      'lllllmmlllllmmdk',
      'llllwwdlllmmmddk',
      'llmmwwdlmmmmdddk',
      'lllmmmmmmmmddddd',
      'dlllmmmmmmdddddk',
      'kdllmmmmmmddddk.',
      '.kdllmmmmmdddk..',
      '..kllmmmmddddk..',
      '...kllmmmdddk...',
      '....klmmmddk....',
      '.....klmddk.....',
      '......kkdk......',
    ],
  },
  'magnet': {
    pal: 'magnet', art: 2,
    rows: [
      '...kdddddddk...',
      '..kddmmmmdddk..',
      '.kdmmmlllmmddk.',
      'kddmllkkkmmmddk',
      'kdmmlk...kmmddk',
      'kdmlk.....kmddk',
      'kdmlk.....klmdk',
      'kdmlk.....klmdk',
      'kdmlk.....klmdk',
      'kdmlk.....klmdk',
      'kdmlk.....klmdk',
      'krRpk.....kpRrk',
      'krRpk.....kpRrk',
      'krRpk.....kpRrk',
      '.kkk.......kkk.',
    ],
  },
  'coin': {
    pal: 'coin', art: 2,
    rows: [
      '..kllllmmk...',
      '.klllllmmmk..',
      'kllwllllmmdk.',
      'lllllllllmddk',
      'lllllldlmmddk',
      'mllllllmmmddk',
      'mmlldldmdmddk',
      'mmllmmmmmmddk',
      'dmdmmmdmmdddk',
      'kdddmmmmdddk.',
      '.kddddddddk..',
      '..kddddddk...',
      '...kkkkkk....',
    ],
  },

  // ---- 부술 수 있는 물건 ----
  // 상자 — 엘리트와 보스가 떨군다
  'chest': {
    pal: 'chest', art: 2,
    rows: [
      '.......kkkkkkkk.......',
      '.....kkllllllmmkk.....',
      '....killlllllmmmIk....',
      '...kIillllllmmmmIik...',
      '..klIilllllmmmmmIidk..',
      '.kllIilllmmmmmmmIiddk.',
      '.kllIilmmmmmmmmdIiddk.',
      'kmmmIimmmmCCCmddIidddk',
      'kDDDIiDDDDCccDDDIiDDDk',
      'kDDDDDDDDDCccDDDDDDDDk',
      'kmmmIimmmmCkcdddIidddd',
      'kmmmIimmmmCccdddIidddd',
      'kmmmIimmmmCccdddIidddd',
      'kDmmIimmmmCccdddIidddD',
      '.kmmIimmmmmmmdddIidddk',
      '.kmmIimmmmmmmdddIidddk',
      '.kmmIimmmmmmmdddIidddk',
      '.kDDIiDDDDDDDDDDIiDDDk',
      '..kkkkkkkkkkkkkkkkkkk.',
    ],
  },
  // 항아리 — 부수면 금화 · 회복 · 자석이 나온다
  'pot': {
    pal: 'pot', art: 2,
    rows: [
      '.....kkk...kkk.....',
      '...kklllkkkDDmkk...',
      '..klllkkkkkkkdddk..',
      '..kDDmmkkkkkdddDk..',
      '...kkDDDDDDDDDDk...',
      '...kDDDDDDDDDDDDk..',
      '..klmmmmmmmdddddk..',
      '.kllmmmmmmmddddddk.',
      '.klmmmmmmmmddddddk.',
      'kllllllmmmmmmdddddk',
      'kmlllmmmmmmmddddddk',
      'kmBBBBBBBbbbbbbbbbk',
      'kmbbbbbbbbbbbbbbbbk',
      'kDmmmmmddddddddddDk',
      '.kdddddddddddddddk.',
      '.kDdddddddddddddDk.',
      '..kDdddddddddddDk..',
      '...kDDDdddddDDDk...',
      '....kkkDDDDDkkk....',
    ],
  },

  // ---- 배경 장식 ----
  'rock': {
    pal: 'rock', art: 2,
    rows: [
      '....kkkkkk.....',
      '..kkllllmmkk...',
      '.kllllllmmGdk..',
      'klllllllGGGddk.',
      'kllllllmmggddk.',
      'lllllmmmmmddddk',
      'mlmmmmmmmdddddk',
      'mmmmmmmdddddddk',
      'DmmmmmdddddddDk',
      'kDDDDDDDDDDDDk.',
    ],
  },
  'tuft': {
    pal: 'tuft', art: 2,
    rows: [
      '.......k......',
      '....k.kmk.....',
      '...klkkmk...k.',
      'k..klkkmk..kmk',
      'lk.klkkmk.kmk.',
      'lk.klkkmk.kmk.',
      'klkklkkmkkmk..',
      'kldkldkmdkmdk.',
      '.kldkldmdkmdk.',
    ],
  },
  'mushroom': {
    pal: 'fungus', art: 2,
    rows: [
      '....kkkk.....',
      '..kklllmkk...',
      '.klllllmmmk..',
      'klllllmmmmdk.',
      'lllllmmmldddk',
      'mlmlmmmmddddk',
      'mmmmmmdddlddk',
      'DDDDDDlDDDDDD',
      'kkkkSSSsskkkk',
      '...kSSSssk...',
      '...kSSSssk...',
      '...kSSSssk...',
      '..kSSSSsssk..',
    ],
  },
  'flower': {
    pal: 'flower', art: 2,
    rows: [
      '....k....',
      '..kklkk..',
      '.kllmmmk.',
      '.klmmdkk.',
      'klmmddkmk',
      '.kddddkk.',
      '.klkgkmk.',
      '..kklkk..',
      '..kkgGk..',
      '.kGkgk...',
      '..kkgk...',
      '...kgk...',
    ],
  },
  'bones': {
    pal: 'bones', art: 2,
    rows: [
      'kkkk.......kkkk.',
      'llmdk.....kllmdk',
      'mmddk.....kmmddk',
      'ddddmkk..kkddddk',
      'kkkddmmkkmmddkk.',
      '...kkddmmddkk...',
      'kkkkkmmddmmkkkk.',
      'llmdmddkkddllmdk',
      'mmdddkk..kkmmddk',
      'ddddk.....kddddk',
      'kkkk.......kkkk.',
    ],
  },
  'stump': {
    pal: 'stump', art: 2,
    rows: [
      '.....kkkkk......',
      '..kkklllllkkk...',
      '.kllllmmmllllk..',
      'kllmmmlllmmmllk.',
      'kllmmmlllmmmlldk',
      'kmllmmmmmmmllddk',
      'kDDlllllllllDDDk',
      'kDDDDDDDDDDDDDDk',
      'kGGGgmmmmddddddk',
      'kGGggmmmmddddddk',
      '.kgggmmmmdddddDk',
      '.kmmmmmmmdddddk.',
      '.kmmmmmmmdddddk.',
      '.kDDDDDDDDDDDDk.',
    ],
  },
  'grave': {
    pal: 'grave', art: 2,
    rows: [
      '....kkkkkk.....',
      '...kllllmmk....',
      '..kllllmmmdk...',
      '..klllDDmddk...',
      '.kmlmmDDddddk..',
      '.kmmDDDDDDDddk.',
      '.kmmDDDDDDDddk.',
      '.kmdDDDDDDDddk.',
      '.kmmddDDdddddk.',
      '.kmmmmDDdddddk.',
      '.kGGmmDDdddddk.',
      '.kGGgmDDdddddk.',
      '.kgggmmmdddddk.',
      'kkggmmmmdddddk.',
      'DDmmmmmmdddddDk',
      'DDDDDDDDDDDDDDk',
      'kkDDDDDDDDDDkk.',
    ],
  },

  // ---- 바닥 타일 ----
  // 잡티를 칸마다 흩뿌리면 노이즈로 보인다. 덩어리로 뭉치고 결을 넣어야 풀밭이 된다.
  // 가장자리는 기본색만 남겨 이웃 타일과의 이음새를 감춘다.
  'tile.grass0': {
    pal: 'ground', art: 2, flat: true,
    rows: [
      'bbaaaaabbbbbbbbbaaaaaaaaaaaebbbb',
      'bbaaaabbbbbbbbbbaaaaeaaaaaebbbbb',
      'baaaabbbbbbbbbbbdcdeaaaaaadabbbb',
      'aaaabbbbbbbbbbbdcdceaaaaadaaaaaa',
      'aaaaabbbbbbbbbadcdccaaaaddaaaaaa',
      'aaaaaabbbbbbbaacccccaaadaaaaaaaa',
      'aaaaadaaaaaaaaaccccccccdaaaaaaaa',
      'aaaaadaaaaaaaaaccccccccccaaaaaaa',
      'aaaaabbbbbaaaaaaccccccccccaaadaa',
      'aaaabbbbbbbaaaaaacccccccccaadaaa',
      'aaaaabbbbeaaaaaaacccccccccaadaaa',
      'adaaaaaaeaaaaaaaaacccccccaaadaaa',
      'adaaaaaeeaaaaaaaaaaacceaaaaadaaa',
      'aaaaaaeaaaaaaaaaaaaaaaeaaaaaaaaa',
      'aaaabaeaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaabbbbbbaaaadaaaaaaaaaaaaabaaaa',
      'aabbbbbbbbaaadaaaaaaaaaabbbbdbba',
      'aabbbbbbbaaaaaaaaaaaaaabbbbdbbbd',
      'aabbbbbaaaaaaaaaaaaaaaabbbbdbbbd',
      'aaabbbaaaaaaaaaaaeeaaaabbbbbbbbb',
      'aaaabaaaaaaaaaaaeebbdddabbbbbbba',
      'aaaaaaaaaaaaaaadeebbddddaaabaaaa',
      'aaaaaaaaaaaaabaabbbbbddaaaaaaaaa',
      'aaaaaaaaaabbbbbbbdbbbaaaaaaaaaaa',
      'aaaaaaaaebbbbbbbbdbbbaaaaaaaaaaa',
      'aaaaaaaeaabbbbbbbbbbbbbbbaaaaaaa',
      'aaeaaaaeaaaaabaaabbbbbbbbbaeaaaa',
      'aeaaaaaaaaaaaaaaaabbbbbbbbbeaaaa',
      'bdaaaaaaaaaaaaaaaaabbbbbbbaabbbb',
      'dbaaaaaaaaaaaaaaaaaabbbbbaabbebb',
      'dbaaaaaaaaaaaaaaaaaaaaaaaaabebbb',
      'bbaaaaaaaaabaaaaaaaaaaaaaaabebbb',
    ],
  },
  'tile.grass1': {
    pal: 'ground', art: 2, flat: true,
    rows: [
      'bbbbbbbdddedddddaeaaaaaaaaaacccc',
      'ccabaadddddddddddaaaaaaaaaeccccc',
      'ccaaaaadddddddddaaaeaaaaaeaccccc',
      'ccaaeaaaadddddaaaaeaaaaaaeaccecc',
      'caaaeaaaaaaaaaaaaaeeaaaaaaaacecc',
      'caaaaaaaaaaaaaaaaaeaaaaaaaabcdcc',
      'aaaaaeaaaaaaaaaaaaeaaaaaaaaedbcb',
      'baccceaaaaaaaaaaaaaaaaaaaaeddbbb',
      'cccccccaaaaaaaaaaaaaaaaaaaebbbbb',
      'cccccccaaaaaaaaaaaaaaaaadadbbbbb',
      'ccccccdcaaaaaaaaaaaaaaadaaaabbba',
      'ccccccdcaaaaaaaaaaaaaaadaaaaaaaa',
      'ccccccccaaaaaaaaaaaaaaaaaaaaaaaa',
      'cccccccaaaaaaaaaaaaaaaaaaaaaaaaa',
      'cccccccaaaaacccccabbbbbaaaaaaaaa',
      'aaeccaaaeaaccccccbbbbbbbdaaaaaaa',
      'aeaaaaaeaaccccccbbbdbbbbdaaaaaaa',
      'aeaaaaaeaaccccccbbdbbbbbbaaeaaaa',
      'aaaaaaaaaaccccccbbdbbbbbbaaeaaaa',
      'bbbbbaaaaabbbccccbbbbebbbbaaaaaa',
      'bbbbbaaaabbbbbcccabbebbbbbbaaaaa',
      'bbbbbbaaabbbbbaaaaaaeabbbbbaaaaa',
      'bbbbbbaabbbbbbbaaaaaaabbbbbaaaaa',
      'bbbbbbdaabbbbbaaaaaaaabbbbbabaad',
      'bbbbedaaabbbbbaaaaaaaabdbbbbbbbb',
      'bbbebaaaaabbbaaaaaaaaadbbbbbbbbb',
      'bbbebbbaaaaaaaaaaaaaaadabbbbbbbe',
      'bbbbbbbbaaaaaaaaaaaaaaabbbbbbbeb',
      'bbbbbbbbaaaaabbbaaaaaaaabbbbbbee',
      'bbbbbbbbaaaabbbbbaaaaaaabbbbbbbe',
      'bbbbbbbbaaaaabbbaaaaaaaaabbbbbbb',
      'bbbbbbbbaaadaaaaaaaaaaaaaaaabaca',
    ],
  },
  'tile.moss0': {
    pal: 'moss', art: 2, flat: true,
    rows: [
      'cccccccaabbbbbddadaaaaaaaaaeeaaa',
      'cccdccccaaabaadadaaaaaaaaaaeaaaa',
      'cccdcccccaaaaaaadaeaaaaaaaaaaaac',
      'ccccccccaaaaaaaaaaeaabbbbbaaaaaa',
      'cccccccaaaaaaaaaaaabbbbbbbbbaaaa',
      'aacccaaaaaaaaaabbbbbbbbbbbbbadaa',
      'aabbbaaaaaaaaabbbbbbbbbbbbebadaa',
      'abbbbbaaaaaaabbbbbbbbbbbbbebaaae',
      'abbbbbaaaaaeaabbbbbbbbbbbbbbaaae',
      'abbbbbaaaaeaaaabbbbbbebbbbaaaaaa',
      'aabbbaaaaaeaaadddbbbeadaaaaaaaaa',
      'aaaaaaaaaaaaadddddaaedaaaaaaaaaa',
      'aaaaaaaaaaaaaddddddccdaaaaaaaaaa',
      'aaaaaaaaaaaaadddddccccaaaaaaaaaa',
      'aaaaaaaaaaaaaaddddcccccaaaaaaaaa',
      'aaaaadaaaaaaaacccccccccaaaaaaaaa',
      'addddddddeaaaaccdccccccaaaaaaaaa',
      'ddddddddeddaaaacdcccccaaaaaaaaaa',
      'adddddddedaaaaaacccccaaaaaaaaaaa',
      'aaaaadaaaaaaaaaaaadddddaaaaaaadd',
      'aaaaaaaaaaaaaaaadddddddddaaaeadd',
      'aaaaaaadaaaaaaadddddddddddbebebb',
      'baaaaadaaaaaaaaadddddddddbbebebb',
      'bbbaaadaaaaaaadeaadddddabbbbbbbb',
      'bbbaaaaaaaaaadaeaaaaaaaabbbbbbdb',
      'bbbbaaaaaaaaadaaaaaaaaaabbbbbbdb',
      'bbbaaaaaaaaadaaaaaaaaaaabbebdbbb',
      'bbbaadadaaadaaaaaaaaaaabbebbdbbb',
      'badddddddbbdbbaaaaaaaaabbebbbbbb',
      'aadddddddbbbbbdaaaaaaaabbbbbaaaa',
      'aadddddddbbbbbdaaaaaaaaaaaaaaaaa',
      'aaaaadaabbbbbbbaaaaaaaaaaaaaaaaa',
    ],
  },
  'tile.moss1': {
    pal: 'moss', art: 2, flat: true,
    rows: [
      'aaaacccaaaaaaadaaaaaaaaaaaaaaaaa',
      'aaacccccaaaaadaaaaaaaaaaaaaaaaaa',
      'aacccccccaaaadaabbbbbaaaaaaaaaaa',
      'aacccccccaaaaaabbbbbbbaaaaaaaaaa',
      'aacccccccaaaaabbbbbbbbbaaaaaaada',
      'aaecccccaaaaaaabbebbbbbbaaaaaada',
      'cecacccaaaaaaaaebebbbbbbaaaaaaaa',
      'cecccaaaaeaaeaaebbbbbbbbaaaaaaac',
      'cccccaaaaeaeaaaabbbbbbbaaaaaaaac',
      'cccdcdaaaaaeabbbbbbbbbaaaaaaaaac',
      'ccdadaaaaaaaabbbbbaaaaaaaaaaaaaa',
      'aadadaaaaaaaabbbbbaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaeaaaaaaaaaaaaaaaaaaa',
      'aaaaeaaaaaaaeaaaaaaaaaaaaaaaaaaa',
      'aaaeaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaeaaaaaaadaaaaaaaaaaaaaaaaaaaa',
      'aaaadbbbbadbbbaaaaadaaaaaaaaaaae',
      'aaadbbbbccdbbbbaaaadaaaaaaaaaaea',
      'aaadbbcccecccbbaaaaadaadaaaaabeb',
      'bbabbcccceccccbaaaaadaadaaabbbbb',
      'beabbcccccccccaaaaaaeaaaaadbbbbb',
      'ebaabcccccccccaaaaaaeaaaadabbbbb',
      'ebaacccccccccbbdbbcccaaabdbbbbbb',
      'bdaacccccccbbbbdbbbbcbbbbbbbbbbb',
      'dbeacccdcecbbbbbbbbbbebbbbbbbbbb',
      'debaaaadaeabbbbbbbbbebbbbbbbbbbb',
      'beaaaaaaaaaaabbbbbabebbbbbbbbbbb',
      'bbbbaeaaaaaaaaaaaaabbbbbbbbbbbba',
      'bbbbbeaaaaaaaaaaaaaabbbbbbbaaaab',
      'bbbbaaaaaaaaaaaaaaaaabbbbbaaaaaa',
    ],
  },
  'tile.path': {
    pal: 'path', art: 2, flat: true,
    rows: [
      'gGhaGhgbhgbbbGhaGhgGhaGhgGhgahge',
      'gahaGagGhbGhgGhgahaGaaGhaGhaGhgG',
      'gGaaaaaahbbaaaaaaaaGhaahaahaaagG',
      'aaaaaaaaaaaaaaaaaaaaaaGaaaaaaagG',
      'gaaaaaaaaaaaaaaaaaaaaaaaaaaaaagG',
      'gaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaG',
      'gaaaaaaaaaaaaaaaaadddaaaaaaaahgG',
      'gaaaaaaaaaaaaaaaaaaaaaaaaaaaaagd',
      'gGhaaaaaaaaaaaaaaaaaaaaaaaaaaagG',
      'gaaaaaaaaaeaaaaaaaaaaaaaaaaaahaG',
      'gGhaaaaaaaeaaadaaaaadaaaaaaaaagG',
      'gbhgbaaaaaaaadaaaaadaaaaaaaaGaaG',
      'gbbbbbbaaaaaadaaaaadaaaaaaabbhgG',
      'gbbbbbbaaaaaaaaaaaaaaaaaaaabbhgb',
      'gGbbbbbaaaaaaaaaaaaaaaaabbbbbbgG',
      'bGbbbbbaaaaaadaaaabbbbbbeebbbbgG',
      'gGbbbbbbbaaadaacccbbbbbbddbbbbgG',
      'gGbbbbbbbbbbdacccccbbbbbbbbbbbbG',
      'aGbbbbbbbbbbbbcccccabbbbbbbbbbbG',
      'gGbbbbbbbbbbbbcccccabbbbbbbbbbgG',
      'gGbebbbbbbbbbbcccccabbbbbbbbbhaa',
      'gchebbbbbbbbbbcccccaabbbaaaaaaaG',
      'gGccccbbbbbbbbbcccaaaaaaaaaaaacG',
      'gGcccccaabbbbbbbaacccccaaaaaaagG',
      'gGccccaaaaabbbaaaacccccaaaaaahaa',
      'aGhaaaaaaaaaaaaaaacccccaaaaaGhgG',
      'gGhaaaaaaaaaaaaaaeeaaaaaaaaaaaaG',
      'gGhaaaaaaaaaaaaaaddaaaaaaaaaahaa',
      'gaaaaaaaaaaaaGaaaaaahaaaaaaaahgG',
      'aGeaGagGhgahaahaaagaaaahgaaaaagG',
      'gGeeeegGhgGhaGaaahaGhgahgahgaagG',
      'gehgGhaGhgGhgGhgGhgGhaGagGhgahgG',
    ],
  },

  // ---- 투사체 ----
  // 마력 화살 — 어느 방향으로 날아가도 같게 보이도록 둥근 핵으로 그렸다
  'bolt.0': {
    pal: 'arcane', art: 2,
    rows: [
      '......k......',
      '....kkdkk....',
      '...kllllmk...',
      '..kllllmmdk..',
      '.klllllmmddk.',
      '.klllwwmdddk.',
      'kdmmmwwdddddk',
      '.kmmmmdddddk.',
      '.kdddddddddk.',
      '..kdddddddk..',
      '...kdddddk...',
      '....kkdkk....',
      '......k......',
    ],
  },
  'bolt.1': {
    pal: 'arcane', art: 2,
    rows: [
      '.....kkk.....',
      '...kkllmkk...',
      '..klllllmmk..',
      '.klllllmmmdk.',
      '.kllllmmmddk.',
      'kllllwwmddddk',
      'kmmmmwwdddddk',
      'kmmmmmddddddk',
      '.kdddddddddk.',
      '.kdddddddddk.',
      '..kdddddddk..',
      '...kkdddkk...',
      '.....kkk.....',
    ],
  },
  'shard': {
    pal: 'frost', art: 2,
    rows: [
      '.......kkwkk.......',
      '.....kkwwwwwkk.....',
      '...kkwwwwwwwwwkk...',
      '.kkwwwwwwwwlllllkk.',
      'kwwwwwwllllllllmmmk',
      'kwllllllllmmmmmmmmk',
      'klllllmmmmmmmdddddk',
      '.kkmmmmmmdddddddkk.',
      '...kkdddddddddkk...',
      '.....kkdddddkk.....',
      '.......kkdkk.......',
    ],
  },
  'rune.0': {
    pal: 'rune', art: 2,
    rows: [
      '...kkllmkk....',
      '..klllllmmk...',
      '.kdllllmmmdk..',
      'klldwllmmdddk.',
      'kllldmmmdmddk.',
      'mlllmdmdmddddk',
      'mmmmmmdmdddddk',
      'mmmmmddddddddk',
      'kmmmddddddddk.',
      'kdddddddddddk.',
      '.kdddddddddk..',
      '..kdddddddk...',
      '...kkdddkk....',
      '.....kkk......',
    ],
  },
  'rune.1': {
    pal: 'rune', art: 2,
    rows: [
      '...kkllmkk....',
      '..klllllmmk...',
      '.kllllddmmdk..',
      'klllwlddmmddk.',
      'kllllmddmmddk.',
      'mlllmmddmddddk',
      'mmdddddddddddk',
      'mmdddddddddddk',
      'kmmmddddddddk.',
      'kdddddddddddk.',
      '.kdddddddddk..',
      '..kdddddddk...',
      '...kkdddkk....',
      '.....kkk......',
    ],
  },
  'flame.0': {
    pal: 'fire', art: 2,
    rows: [
      '...kdk.....',
      '..kmmdk....',
      '.kmmmddk...',
      'kmmmmmddkk.',
      'mmmmmmddddk',
      'mmmmmmmdddk',
      'mmmmmmmdddk',
      'mmmmmmmdddk',
      'kmmlllldddk',
      'kmmlllldddk',
      'kmmlllldddk',
      '.kmmllldddk',
      '.kmmwwlddk.',
      '..kmlwlddk.',
      '...kmwlddk.',
      '...kmwldk..',
      '....klddk..',
      '.....kdk...',
    ],
  },
  'flame.1': {
    pal: 'fire', art: 2,
    rows: [
      '.....kdk.....',
      '....kmddk....',
      '...kmmmddk...',
      '..kmmmmdddk..',
      '.kmmmmmmdddk.',
      'kmmmmmmmddddk',
      'kmmmmmmmddddk',
      '.kmmmmmmdddk.',
      '.kmmlllldddk.',
      '.kmmlllldddk.',
      '.kmmlllldddk.',
      '..kmllllddk..',
      '..kmlwwlddk..',
      '..kmmwwdddk..',
      '...kmwwddk...',
      '...kmllddk...',
      '....kmddk....',
      '.....kdk.....',
    ],
  },
  'flame.2': {
    pal: 'fire', art: 2,
    rows: [
      '.....kdk...',
      '....kmddk..',
      '...kmmmddk.',
      '.kkmmmmdddk',
      'kmmmmmmdddd',
      'kmmmmmmdddd',
      'kmmmmmmdddd',
      'kmmmmmmdddd',
      'kmmlllldddk',
      'kmmlllldddk',
      'kmmlllldddk',
      'kmmllldddk.',
      '.kmlwwdddk.',
      '.kmlwlddk..',
      '.kmlwddk...',
      '..klwddk...',
      '..kmldk....',
      '...kdk.....',
    ],
  },
  'zap.0': {
    pal: 'zap', art: 2,
    rows: [
      '...klwmdk..',
      '...klwmdk..',
      '..klwmdk...',
      '..klwmdk...',
      '.klkmkdk...',
      '.klwmdk....',
      '.klwmdk....',
      'klwmdk.....',
      'klwmdk.....',
      '.klwmdk....',
      '..klwmdk...',
      '...klwmdk..',
      '....klwmdk.',
      '.....klwmdk',
      '.....klkdk.',
      '....klwmdk.',
      '...klkmkdk.',
      '...klwmdk..',
      '...klkdk...',
      '..klwmdk...',
      '.klkmkdk...',
      '.klwmdk....',
      '.klwmdk....',
      '..klwmdk...',
      '..klwmdk...',
      '..klwmdk...',
      '...klwmdk..',
      '...klwmdk..',
    ],
  },
  'zap.1': {
    pal: 'zap', art: 2,
    rows: [
      '.klwmdk....',
      '..klwmdk...',
      '..klwmdk...',
      '...klwmdk..',
      '...klwmdk..',
      '....klwmdk.',
      '....klwmdk.',
      '.....klwmdk',
      '....klwmdk.',
      '....klwmdk.',
      '...klwmdk..',
      '..klwmdk...',
      '.klwmdk....',
      '.klwmdk....',
      'klwmdk.....',
      '.klkdk.....',
      '.klwmdk....',
      '.klkmkdk...',
      '..klwmdk...',
      '...klkdk...',
      '...klwmdk..',
      '...klkmkdk.',
      '....klwmdk.',
      '...klwmdk..',
      '...klwmdk..',
      '..klwmdk...',
      '..klwmdk...',
      '.klwmdk....',
    ],
  },

  // ---- 아이템 아이콘 ----
  // HUD 칸(11도트)에 맞춰 규격을 통일한다. flat이라 아랫줄을 더 두지 않는다.
  'item.bolt': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '................k.',
      '.............kkkXk',
      '............kXXXk.',
      '............kXXVk.',
      '..........kkXXVVk.',
      '........kkXXXVVk..',
      '.......kXXXXVVVk..',
      '......kVVVVXVVVk..',
      '.......kkVVVVVVk..',
      '........kVVVVVk...',
      '.......kVvkVVVk...',
      '......kVvk.kVVk...',
      '.....kVvk...kVk...',
      '....kVvk.....k....',
      '.kkkVvkvk.........',
      'kvvvvvvk..........',
      '.kvvvvk...........',
      '..kvvk............',
      '...kvk............',
    ],
  },
  'item.shard': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '........kkkk........',
      '.......kWWWWk.......',
      '.....kkWWWWWWkk.....',
      '....kWWWWWWWWWWk....',
      '...kWWWWWWWWWWCCk...',
      '.kkWWWWWWWCCCCCCCkk.',
      'kWWWWCCCCCCCCCCCBBBk',
      'kCCCCCCCCCCBBBBBBBBk',
      'kCCCCCCBBBBBBBBBBbbk',
      '.kkBBBBBBBBBbbbbbkk.',
      '...kBBBBbbbbbbbbk...',
      '....kbbbbbbbbbbk....',
      '.....kkbbbbbbkk.....',
      '.......kbbbbk.......',
    ],
  },
  'item.rune': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '....kkccccYkk.....',
      '...kccccccYYYk....',
      '..kcccccmmYYYYk...',
      '.kccccccmmYYYYyk..',
      'kcccccccmmYYYyyyk.',
      'kccccmcYmmYYYyyyk.',
      'ccccccmYmmYYyyyyyk',
      'YcccYYYmmmYyyyyyyk',
      'YYmmmmmmmmmmmmmmyk',
      'YYmmmmmmmmmmmmmmyk',
      'YYYYYYYymmmyyyyyyk',
      'kYYYYyyymmymyyyyk.',
      'kyyyyyyymmyymyyyk.',
      '.kyyyyyymmyyyyyk..',
      '..kyyyyymmyyyyk...',
      '...kyyyyyyyyyk....',
      '....kkyyyyykk.....',
      '......kkkkk.......',
    ],
  },
  'item.aura': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '......kkkdkkk.......',
      '..k.kkdddddddkk.k...',
      '.kdkdddooooodddkdk..',
      '.koddooOOOOOooddok..',
      '.kddoOOOkkkOOOoddk..',
      'kddoOOkk.k.kkOOoddk.',
      'kdooOk.kkOkk.kOOodk.',
      'kdoOk.kOOOodk.kOodk.',
      'ddoOk.kOOoodk.kOoddk',
      'dkoOkkoooodddkkOokod',
      'ddoOk.koddddk.kOoddk',
      'kdoOk.kdddddk.kOodk.',
      'kdoOOk.kkdkk.kOoodk.',
      'kddoOOkk.k.kkOOoddk.',
      '.kddoOOOkkkOOOoddk..',
      '.koddooOOOOOooddok..',
      '.kdkdddooooodddkdk..',
      '..k.kkdddddddkk.k...',
      '......kkkokkk.......',
      '........kdk.........',
    ],
  },
  'item.zap': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '......kWBWk',
      '.....kWBWk.',
      '.....kWBWk.',
      '....kWBWk..',
      '....kWBWk..',
      '...kWBWk...',
      '...kWBWkkk.',
      '..kWBWBBBBk',
      '..kWBBBBWk.',
      '.kWWBBBBBk.',
      '..kkkWBWk..',
      '....kWWk...',
      '....kWWk...',
      '...kWWk....',
      '..kWWk.....',
      '..kWWk.....',
      '..kWk......',
      '.kWk.......',
      'kWWk.......',
      'kWk........',
    ],
  },
  'item.brand': {
    pal: 'item', art: 2, flat: true,
    rows: [
      'kooooooddddk',
      'kooooooddddk',
      'kooooooodddk',
      'kooooooodddk',
      'kooooooodddk',
      'koooOOOddddk',
      '.kooOOOdddk.',
      '.kooOOOdddk.',
      '..kooOoddk..',
      '..kkoOddkk..',
      '.knnnndnnnk.',
      '.kMMMMMMMMk.',
      '..kkMMmmkk..',
      '...kMMmmk...',
      '...kMMmmk...',
      '...kMMmmk...',
      '...kMMmmk...',
      '...kMMmmk...',
      '...kMMmmk...',
      '...kMMmmk...',
    ],
  },
  'item.might': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.....kkkkkkk......',
      '...kkXXXXXVVkk....',
      '..kXXXXXXXVVVVk...',
      '.kXXXXXXXXVVVVvk..',
      'kXXXWWXXXVVVVVvvk.',
      'kXXXWWXXVVVVVvvvk.',
      'XXXXXXXVVVVVVvvvvk',
      'XXXXXVVVVVVVvvvvvk',
      'VVVVVVVVVVVvvvvvvk',
      'VVVVVVVVVvvvvvvvvk',
      'VVVVVVVVvvvvvvvvvk',
      'vVVVVVvvvvvvvvvvvk',
      'kvvvvvvvvvvvXvvvk.',
      'kvvvvvXvvvvvvvvvk.',
      '.kvvvvvvvvvvvvvk..',
      '..kvvvvvvvvvvvk...',
      '...kkvvvvvvvkk....',
      '.....kkkkkkk......',
    ],
  },
  'item.swift': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '............kk.',
      '.........kkkaak',
      '.......kkwwawk.',
      '.....kkwwWwaak.',
      '....kwwwwWaaak.',
      '...kwwwwWwaak..',
      '...kwwWWWaaak..',
      '..kwwwWWawaak..',
      '.kwwwWWWawaak..',
      '.kwwWWWawaak...',
      'kwwwWWawwak....',
      'kwwWWWawaak....',
      'kwwWWawaak.....',
      'kwwWawwaak.....',
      'kwwWaaaak......',
      'kwWawaak.......',
      'kwwaaak........',
      '.kaaak.........',
      '.kakk..........',
      '..k............',
    ],
  },
  'item.vigor': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '....kkkkkkkk...',
      '...knnnnnnnnk..',
      '...kMMMMMMMMk..',
      '...kMMMMMMMMk..',
      '..kWWWWWWWWWWk.',
      '...kRRRRrrrrk..',
      '...kRRRRrrrrk..',
      '..kRRRRRRrrrrk.',
      '.kppppppRRRRrk.',
      'kpppWWpRRRRrrrk',
      'kpppWWRRRRrrrrk',
      'kRRRWWRRRrrrrrk',
      'kRRRRRRRrrrrrrk',
      'kRRRRRrrrrrrrrk',
      'krRRrrrrrrrrrrk',
      '.krrrrrrrrrrrk.',
      '..krrrrrrrrrk..',
      '...krrrrrrrk...',
      '....kkrrrkk....',
    ],
  },
  'item.regen': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '....kkkkkkkk...',
      '...knnnnnnnnk..',
      '...kMMMMMMMMk..',
      '...kMMMMMMMMk..',
      '..kWWWWWWWWWWk.',
      '...kGGGGggggk..',
      '...kGGGGggggk..',
      '..kGGGGGGggggk.',
      '.kjjjjjjGGGGgk.',
      'kjjjWWjGGGGgggk',
      'kjjjWWGGGGggggk',
      'kGGGWWGGGgggggk',
      'kGGGGGGGggggggk',
      'kGGGGGggggggggk',
      'kgGGggggggggggk',
      '.kgggggggggggk.',
      '..kgggggggggk..',
      '...kgggggggk...',
      '....kkgggkk....',
    ],
  },
  'item.focus': {
    pal: 'item', art: 2, flat: true,
    rows: [
      'knnnnnnnnnnnnk.',
      'kMMMMMMMMMMMMk.',
      'kMMMMMMMMMMMMk.',
      'kWkkkkkkkkkkWWk',
      'kWYYYYYYYYYWWk.',
      '.kWYYYYYYYWWk..',
      '..kYYYYYYYWk...',
      '..kWYYYYYWWk...',
      '...kWYYYWWk....',
      '....kYYYWk.....',
      '....kWcWWk.....',
      '....kWcWWk.....',
      '...kWWckWWk....',
      '..kWYYYYYWWk...',
      '..kWYYYYYkWk...',
      '.kWYYYYYYYWWk..',
      'kWYYYYYYYYYWWk.',
      'knnnnnnnnnnnnk.',
      'kMMMMMMMMMMMMk.',
      'kMMMMMMMMMMMMk.',
    ],
  },
  'item.area': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '....kkkCCCCBkkk.....',
      '...kCCCCCCCCBBBk....',
      '..kCCCCCCCCBBBBbk...',
      '.kCCWWCCCCCBBBBbbk..',
      'kCCCWWCCCkBBBBBbbbk.',
      'kCCCCCkkk.kkkBbbbbk.',
      'CCCCCk.......kbbbbbk',
      'BCCCBk.......kbbbbbk',
      'BBBBk.........kbbbbk',
      'BBBBBk.......kbbbbbk',
      'BBBBBk.......kbbbbbk',
      'kBBBBbkkk.kkkbbbbbk.',
      'kbbbbbbbbkbbbbbbbbk.',
      '.kbbbbbbbbbbbbbbbk..',
      '..kbbbbbbbbbbbbbk...',
      '...kbbbbbbbbbbbk....',
      '....kkkbbbbbkkk.....',
      '.......kkkkk........',
    ],
  },
  'item.wisdom': {
    pal: 'item', art: 2, flat: true,
    rows: [
      '.......kkkkk........',
      '......kWWVVWk.......',
      '....kkWWWVVwWkk.....',
      '...kWWWWWVVwwWWk....',
      '.kkWWWWWWVVwwwwWkk..',
      'kWWWaaaaWVVwaaaaWWk.',
      'kWWWWWWWWVVwwwwwwwk.',
      'kWWaaaaaWVVwaaaaawVk',
      'kWWWWWWWWVVwwwwwwwvk',
      'kWWWWWWWWVVwwwwwwwvk',
      'kWWWWWWWWVVwwwwwwwvk',
      'kvvvvvvvvVVvvvvvvvvk',
      'kvvvvvvvvvvvvvvvvvvk',
      '.kkkkkkkkkkkkkkkkkk.',
    ],
  },
};

// ---- 5×7 비트맵 글꼴(HUD 전용) ----
// 캔버스 위 숫자·라벨은 도트로 찍는다. 한글 문구는 DOM 오버레이가 맡는다.
export const FONT = {
  0: ['01110', '10001', '10011', '10101', '11001', '10001', '01110'],
  1: ['00100', '01100', '00100', '00100', '00100', '00100', '01110'],
  2: ['01110', '10001', '00001', '00010', '00100', '01000', '11111'],
  3: ['11111', '00010', '00100', '00010', '00001', '10001', '01110'],
  4: ['00010', '00110', '01010', '10010', '11111', '00010', '00010'],
  5: ['11111', '10000', '11110', '00001', '00001', '10001', '01110'],
  6: ['00110', '01000', '10000', '11110', '10001', '10001', '01110'],
  7: ['11111', '00001', '00010', '00100', '01000', '01000', '01000'],
  8: ['01110', '10001', '10001', '01110', '10001', '10001', '01110'],
  9: ['01110', '10001', '10001', '01111', '00001', '00010', '01100'],
  A: ['01110', '10001', '10001', '11111', '10001', '10001', '10001'],
  B: ['11110', '10001', '10001', '11110', '10001', '10001', '11110'],
  C: ['01110', '10001', '10000', '10000', '10000', '10001', '01110'],
  D: ['11110', '10001', '10001', '10001', '10001', '10001', '11110'],
  E: ['11111', '10000', '10000', '11110', '10000', '10000', '11111'],
  F: ['11111', '10000', '10000', '11110', '10000', '10000', '10000'],
  G: ['01110', '10001', '10000', '10111', '10001', '10001', '01111'],
  H: ['10001', '10001', '10001', '11111', '10001', '10001', '10001'],
  I: ['01110', '00100', '00100', '00100', '00100', '00100', '01110'],
  J: ['00111', '00010', '00010', '00010', '00010', '10010', '01100'],
  K: ['10001', '10010', '10100', '11000', '10100', '10010', '10001'],
  L: ['10000', '10000', '10000', '10000', '10000', '10000', '11111'],
  M: ['10001', '11011', '10101', '10101', '10001', '10001', '10001'],
  N: ['10001', '11001', '10101', '10011', '10001', '10001', '10001'],
  O: ['01110', '10001', '10001', '10001', '10001', '10001', '01110'],
  P: ['11110', '10001', '10001', '11110', '10000', '10000', '10000'],
  Q: ['01110', '10001', '10001', '10001', '10101', '10010', '01101'],
  R: ['11110', '10001', '10001', '11110', '10100', '10010', '10001'],
  S: ['01111', '10000', '10000', '01110', '00001', '00001', '11110'],
  T: ['11111', '00100', '00100', '00100', '00100', '00100', '00100'],
  U: ['10001', '10001', '10001', '10001', '10001', '10001', '01110'],
  V: ['10001', '10001', '10001', '10001', '10001', '01010', '00100'],
  W: ['10001', '10001', '10001', '10101', '10101', '11011', '10001'],
  X: ['10001', '01010', '00100', '00100', '00100', '01010', '10001'],
  Y: ['10001', '10001', '01010', '00100', '00100', '00100', '00100'],
  Z: ['11111', '00001', '00010', '00100', '01000', '10000', '11111'],
  '+': ['00000', '00100', '00100', '11111', '00100', '00100', '00000'],
  '-': ['00000', '00000', '00000', '11111', '00000', '00000', '00000'],
  ':': ['00000', '01100', '01100', '00000', '01100', '01100', '00000'],
  '/': ['00001', '00010', '00010', '00100', '01000', '01000', '10000'],
  '!': ['00100', '00100', '00100', '00100', '00100', '00000', '00100'],
  '.': ['00000', '00000', '00000', '00000', '00000', '01100', '01100'],
  ' ': ['00000', '00000', '00000', '00000', '00000', '00000', '00000'],
};

// ---- 검증 ----
// 픽셀맵은 손으로 찍는다 — 줄 길이가 하나만 어긋나도 그림이 밀린다.
// 굽기 전에 직사각형인지, 팔레트에 없는 글자가 없는지 본다.
export function validateMaps() {
  const bad = [];
  for (const [name, m] of Object.entries(MAPS)) {
    const pal = PAL[m.pal];
    if (!pal) { bad.push(`${name}: 팔레트 '${m.pal}' 없음`); continue; }
    const w = m.rows[0].length;
    m.rows.forEach((row, y) => {
      if (row.length !== w) bad.push(`${name}: ${y}번째 줄 길이 ${row.length} (기대 ${w})`);
      for (const ch of row) {
        if (ch !== '.' && !pal[ch]) bad.push(`${name}: ${y}번째 줄에 모르는 글자 '${ch}'`);
      }
    });
  }
  return bad;
}

// ---- 굽기 ----
// 모든 프레임을 선반(shelf) 방식으로 하나의 캔버스에 채운다.
// 반환: { canvas, tinted, frames } — frames[name] = { x, y, w, h }
const SHEET_W = 384;
const GAP = 1;

// 캐릭터 프레임은 한 줄 더 높게 굽는다(lift용).
// flat은 그 여유 줄을 빼는 것 — 바닥 타일(이어 붙여야 한다)과 아이콘(가운데 정렬)에 쓴다.
// art:2인 프레임은 여유 줄도 두 줄이어야 한 월드 단위만큼 뜬다.
export function frameSize(m) {
  const art = m.art || 1;
  return {
    w: m.rows[0].length,
    h: m.rows.length + (m.flat ? 0 : art),
    art,
  };
}

function paintFrame(ctx, m, ox, oy) {
  const pal = PAL[m.pal];
  const top = oy + (m.flat || m.lift ? 0 : (m.art || 1));
  for (let y = 0; y < m.rows.length; y += 1) {
    const row = m.rows[y];
    for (let x = 0; x < row.length; x += 1) {
      const ch = row[x];
      if (ch === '.') continue;
      ctx.fillStyle = pal[ch];
      ctx.fillRect(ox + x, top + y, 1, 1);
    }
  }
}

// 외곽선('k')만 다시 찍는다 — 흰 사본에서 실루엣을 살리는 데 쓴다
function paintOutline(ctx, m, ox, oy) {
  const top = oy + (m.flat || m.lift ? 0 : (m.art || 1));
  ctx.fillStyle = PAL[m.pal].k;
  for (let y = 0; y < m.rows.length; y += 1) {
    const row = m.rows[y];
    for (let x = 0; x < row.length; x += 1) {
      if (row[x] === 'k') ctx.fillRect(ox + x, top + y, 1, 1);
    }
  }
}

export function buildSheet() {
  const problems = validateMaps();
  if (problems.length) console.error('스프라이트 픽셀맵 오류:\n' + problems.join('\n'));

  const names = Object.keys(MAPS);
  // 높은 것부터 채우면 선반 낭비가 준다
  const order = [...names].sort((a, b) => frameSize(MAPS[b]).h - frameSize(MAPS[a]).h);

  const frames = {};
  let x = GAP;
  let y = GAP;
  let shelf = 0;
  for (const name of order) {
    const { w, h, art } = frameSize(MAPS[name]);
    if (x + w + GAP > SHEET_W) { x = GAP; y += shelf + GAP; shelf = 0; }
    frames[name] = { x, y, w, h, art };
    x += w + GAP;
    if (h > shelf) shelf = h;
  }
  const height = y + shelf + GAP;

  const canvas = document.createElement('canvas');
  canvas.width = SHEET_W;
  canvas.height = height;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  for (const name of order) paintFrame(ctx, MAPS[name], frames[name].x, frames[name].y);

  // 피격 순간에 쓸 흰 사본 — 같은 좌표계라 프레임 표를 그대로 쓴다.
  // 통째로 하얗게 칠하면 형태가 사라져 옛날 게임처럼 보인다. 외곽선은 검게 남긴다.
  const tinted = document.createElement('canvas');
  tinted.width = canvas.width;
  tinted.height = canvas.height;
  const tc = tinted.getContext('2d');
  tc.drawImage(canvas, 0, 0);
  tc.globalCompositeOperation = 'source-atop';
  tc.fillStyle = 'rgba(255,255,255,.86)';
  tc.fillRect(0, 0, tinted.width, tinted.height);
  tc.globalCompositeOperation = 'source-over';
  for (const name of order) paintOutline(tc, MAPS[name], frames[name].x, frames[name].y);

  return { canvas, tinted, frames };
}
